In [14]:
import pandas as pd
df = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/Correct_Figure1/Last_year_occ_q1_q4.csv')

In [15]:
# OCCLY = Q1 is our dataset for marginal effect
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,...,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,LastYearOCC
0,1,3650,3650,306603,2010,16895,3,NaN,2.009120e+13,1.0,...,0.0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0,q1
1,2,3652,3652,306605,2010,16896,3,NaN,2.009120e+13,1.0,...,8982.0,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1,q1
2,4,3660,3660,306613,2010,16901,3,NaN,2.009120e+13,1.0,...,4696.0,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4,q1
3,6,3672,3672,306625,2010,16908,3,NaN,2.010010e+13,1.0,...,6102.0,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1,q1
4,8,3684,3684,306637,2010,16918,3,NaN,2.009120e+13,1.0,...,0.0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5,q1
5,10,3691,3691,306644,2010,16921,3,NaN,2.009010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4,q1
6,12,3712,3712,306665,2010,16931,3,NaN,2.009020e+13,1.0,...,4913.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4,q1
7,13,3718,3718,306671,2010,16935,3,NaN,2.009030e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3,q1
8,14,3748,3748,306701,2010,16942,3,NaN,0.000000e+00,1.0,...,0.0,NaN,0.00,9999.99,NaN,NaN,4000.0,26.4,30.7,q1
9,16,3754,3754,306707,2010,16943,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8,q1
10,17,3755,3755,306708,2010,16943,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4250.0,22.5,28.6,q1
11,18,3764,3764,306717,2010,16944,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4060.0,15.3,21.1,q1
12,20,3777,3777,308233,2010,17609,3,NaN,2.009120e+13,1.0,...,0.0,NaN,10.00,370.00,NaN,NaN,9140.0,22.0,28.1,q1
13,22,3797,3797,308253,2010,17619,3,NaN,2.010010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9640.0,28.4,22.1,q1
14,23,3798,3798,308254,2010,17620,3,NaN,2.010010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,6200.0,50.3,53.2,q1
15,24,3812,3812,308268,2010,17628,3,NaN,2.010010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0,q1
16,25,3834,3834,308290,2010,17635,3,NaN,2.010020e+13,1.0,...,2585.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0,q1
17,26,3853,3853,308309,2010,17648,3,NaN,2.010030e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5,q1
18,27,3870,3870,308326,2010,17656,3,NaN,2.008120e+13,1.0,...,7631.0,NaN,14.00,560.00,NaN,NaN,5510.0,19.1,22.3,q1
19,28,3886,3886,308342,2010,17664,3,NaN,2.009010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3,q1
20,29,3893,3893,308349,2010,17667,3,NaN,2.009020e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4,q1
21,30,3897,3897,308353,2010,17667,3,NaN,2.009020e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4,q1
22,31,3911,3911,308367,2010,17676,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,5610.0,29.2,34.9,q1
23,33,3920,3920,308376,2010,17679,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0,q1
24,34,3927,3927,308383,2010,17683,3,NaN,0.000000e+00,1.0,...,8596.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4,q1
25,35,3928,3928,308384,2010,17683,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0,q1
26,36,3945,3945,308401,2010,17688,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3,q1
27,39,3955,3955,308411,2010,17693,3,NaN,0.000000e+00,1.0,...,8983.0,NaN,99.99,9999.99,NaN,NaN,6200.0,50.3,53.2,q1
28,40,3956,3956,308412,2010,17693,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9100.0,32.4,32.1,q1
29,41,3960,3960,308416,2010,17694,3,NaN,0.000000e+00,1.0,...,6512.0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4,q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7814,2087,177193,177193,12935919,2017,14866,3,NaN,0.000000e+00,1.0,...,5616.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5,q4
7815,2089,177210,177210,12935936,2017,14870,3,NaN,0.000000e+00,1.0,...,5820.0,NaN,99.99,9999.99,NaN,NaN,3130.0,61.5,66.5,q4
7816,2090,177211,177211,12935937,2017,14875,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1,q4
7817,2091,177213,177213,12935939,2017,14875,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,520.0,50.0,50.1,q4
7818,2094,177268,177268,12935994,2017,14908,3,NaN,0.000000e+00,1.0,...,5719.0,NaN,99.99,9999.99,NaN,NaN,2200.0,78.3,73.5,q4
7819,2096,177297,177297,12936023,2017,14918,3,NaN,0.000000e+00,1.0,...,1716.0,NaN,99.99,9999.99,NaN,NaN,2040.0,69.0,63.3,q4
7820,2099,177346,177346,12936072,2017,14942,3,NaN,0.000000e+00,1.0,...,7752.0,NaN,99.99,9999.99,NaN,NaN,30.0,50.0,56.9,q4
7821,2100,177347,177347,12936073,2017,14942,3,NaN,0.000000e+00,1.0,...,4676.0,NaN,99.99,9999.99,NaN,NaN,30.0,50.0,56.9,q4
7822,2101,177349,177349,12936075,2017,14943,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,1410.0,69.4,64.2,q4
7823,2102,177354,177354,12936080,2017,14945,3,NaN,0.000000e+00,1.0,...,3710.0,NaN,99.99,9999.99,NaN,NaN,3130.0,61.5,66.5,q4
7824,2103,177371,177371,12936941,2017,15417,3,NaN,2.016031e+13,1.0,...,5697.0,NaN,99.99,9999.99,NaN,NaN,3130.0,61.5,66.5,q4
7825,2104,177377,177377,12936947,2017,15419,3,NaN,2.016011e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5,q4
7826,2105,177380,177380,12936950,2017,15421,3,NaN,2.016121e+13,1.0,...,0.0,NaN,10.00,250.00,NaN,NaN,4110.0,20.3,28.1,q4
7827,2106,177381,177381,12936951,2017,15421,3,NaN,2.016121e+13,1.0,...,6376.0,NaN,99.99,500.00,NaN,NaN,430.0,50.3,56.5,q4
7828,2107,177394,177394,12936964,2017,15427,3,NaN,2.016021e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,2200.0,78.3,73.5,q4
7829,2108,177411,177411,12936981,2017,15436,3,NaN,2.017031e+13,1.0,...,4745.0,NaN,99.99,9999.99,NaN,NaN,2340.0,46.0,45.7,q4
7830,2110,177448,177448,12937018,2017,15452,3,NaN,2.017011e+13,1.0,...,9457.0,NaN,99.99,9999.99,NaN,NaN,3130.0,61.5,66.5,q4
7831,2111,177461,177461,12937031,2017,15456,3,NaN,2.017031e+13,1.0,...,3346.0,NaN,99.99,9999.99,NaN,NaN,3130.0,61.5,66.5,q4
7832,2112,177485,177485,12937055,2017,15469,3,NaN,0.000000e+00,1.0,...,3930.0,NaN,99.99,9999.99,NaN,NaN,3130.0,61.5,66.5,q4
7833,2113,177497,177497,12937067,2017,15474,3,NaN,0.000000e+00,1.0,...,7980.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4,q4
7834,2114,177514,177514,12937084,2017,15481,3,NaN,0.000000e+00,1.0,...,9189.0,NaN,99.99,9999.99,NaN,NaN,30.0,50.0,56.9,q4
7835,2117,177552,177552,12937456,2017,15653,3,NaN,2.017031e+13,1.0,...,9349.0,NaN,99.99,9999.99,NaN,NaN,3130.0,61.5,66.5,q4
7836,2120,177568,177568,12937472,2017,15663,3,NaN,2.016011e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5,q4
7837,2121,177579,177579,12937483,2017,15667,3,NaN,2.016031e+13,1.0,...,2221.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1,q4
7838,2122,177585,177585,12937489,2017,15674,3,NaN,2.017011e+13,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5,q4
7839,2127,177652,177652,12937556,2017,15711,3,NaN,0.000000e+00,1.0,...,9052.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1,q4
7840,2128,177668,177668,12937572,2017,15716,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,0.00,9999.99,NaN,NaN,1410.0,69.4,64.2,q4
7841,2129,177672,177672,12937576,2017,15717,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,850.0,50.6,48.4,q4
7842,2130,177684,177684,12937588,2017,15721,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5,q4
7843,2131,177685,177685,12937589,2017,15721,3,NaN,0.000000e+00,1.0,...,6047.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5,q4

In [16]:
q1 = df[df['LastYearOCC']=='q1']

In [17]:
q1
#  2365 obs for Marginal Effect

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,...,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,LastYearOCC
0,1,3650,3650,306603,2010,16895,3,NaN,2.009120e+13,1.0,...,0.0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0,q1
1,2,3652,3652,306605,2010,16896,3,NaN,2.009120e+13,1.0,...,8982.0,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1,q1
2,4,3660,3660,306613,2010,16901,3,NaN,2.009120e+13,1.0,...,4696.0,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4,q1
3,6,3672,3672,306625,2010,16908,3,NaN,2.010010e+13,1.0,...,6102.0,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1,q1
4,8,3684,3684,306637,2010,16918,3,NaN,2.009120e+13,1.0,...,0.0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5,q1
5,10,3691,3691,306644,2010,16921,3,NaN,2.009010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4,q1
6,12,3712,3712,306665,2010,16931,3,NaN,2.009020e+13,1.0,...,4913.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4,q1
7,13,3718,3718,306671,2010,16935,3,NaN,2.009030e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3,q1
8,14,3748,3748,306701,2010,16942,3,NaN,0.000000e+00,1.0,...,0.0,NaN,0.00,9999.99,NaN,NaN,4000.0,26.4,30.7,q1
9,16,3754,3754,306707,2010,16943,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8,q1
10,17,3755,3755,306708,2010,16943,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4250.0,22.5,28.6,q1
11,18,3764,3764,306717,2010,16944,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4060.0,15.3,21.1,q1
12,20,3777,3777,308233,2010,17609,3,NaN,2.009120e+13,1.0,...,0.0,NaN,10.00,370.00,NaN,NaN,9140.0,22.0,28.1,q1
13,22,3797,3797,308253,2010,17619,3,NaN,2.010010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9640.0,28.4,22.1,q1
14,23,3798,3798,308254,2010,17620,3,NaN,2.010010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,6200.0,50.3,53.2,q1
15,24,3812,3812,308268,2010,17628,3,NaN,2.010010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0,q1
16,25,3834,3834,308290,2010,17635,3,NaN,2.010020e+13,1.0,...,2585.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0,q1
17,26,3853,3853,308309,2010,17648,3,NaN,2.010030e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5,q1
18,27,3870,3870,308326,2010,17656,3,NaN,2.008120e+13,1.0,...,7631.0,NaN,14.00,560.00,NaN,NaN,5510.0,19.1,22.3,q1
19,28,3886,3886,308342,2010,17664,3,NaN,2.009010e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3,q1
20,29,3893,3893,308349,2010,17667,3,NaN,2.009020e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4,q1
21,30,3897,3897,308353,2010,17667,3,NaN,2.009020e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4,q1
22,31,3911,3911,308367,2010,17676,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,5610.0,29.2,34.9,q1
23,33,3920,3920,308376,2010,17679,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0,q1
24,34,3927,3927,308383,2010,17683,3,NaN,0.000000e+00,1.0,...,8596.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4,q1
25,35,3928,3928,308384,2010,17683,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0,q1
26,36,3945,3945,308401,2010,17688,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3,q1
27,39,3955,3955,308411,2010,17693,3,NaN,0.000000e+00,1.0,...,8983.0,NaN,99.99,9999.99,NaN,NaN,6200.0,50.3,53.2,q1
28,40,3956,3956,308412,2010,17693,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,9100.0,32.4,32.1,q1
29,41,3960,3960,308416,2010,17694,3,NaN,0.000000e+00,1.0,...,6512.0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4,q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,1462,128948,128948,9308651,2015,16281,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2336,1467,128965,128965,9308668,2015,16285,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2337,1497,129213,129213,9308916,2015,16399,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2338,1513,129372,129372,9309075,2015,16452,3,NaN,2.015031e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2339,1514,129373,129373,9309076,2015,16452,3,NaN,2.015031e+13,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2340,1515,129376,129376,9309079,2015,16453,3,NaN,2.015031e+13,1.0,...,8374.0,NaN,99.99,9999.99,NaN,NaN,2810.0,52.5,59.8,q1
2341,1540,129528,129528,9309231,2015,16535,3,NaN,2.014011e+13,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2342,1550,129609,129609,9309312,2015,16571,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2343,1614,130320,130320,9310023,2015,16995,3,NaN,0.000000e+00,1.0,...,3153.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1,q1
2344,1730,151896,151896,11064689,2016,14302,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2345,1732,151904,151904,11064697,2016,14305,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2346,1768,152080,152080,11064873,2016,14390,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2347,1771,152131,152131,11064924,2016,14412,3,NaN,0.000000e+00,1.0,...,6573.0,NaN,99.99,9999.99,NaN,NaN,3030.0,52.1,55.6,q1
2348,1775,152144,152144,11064937,2016,14416,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2349,1778,152148,152148,11064941,2016,14417,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2350,1790,152195,152195,11064988,2016,14436,3,NaN,2.015031e+13,1.0,...,7510.0,NaN,99.99,9999.99,NaN,NaN,2810.0,52.5,59.8,q1
2351,1798,152236,152236,11065029,2016,14464,3,NaN,2.014121e+13,1.0,...,0.0,NaN,99.99,2885.00,NaN,NaN,3060.0,81.5,86.1,q1
2352,1806,152311,152311,11065104,2016,14493,3,NaN,2.015031e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2353,1807,152312,152312,11065105,2016,14493,3,NaN,2.015031e+13,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2354,1871,152860,152860,11065653,2016,14768,3,NaN,2.016021e+13,1.0,...,5915.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2355,1893,153223,153223,11066877,2016,15432,3,NaN,2.016031e+13,1.0,...,6766.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1,q1
2356,1990,176240,176240,12934966,2017,14319,3,NaN,0.000000e+00,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2357,2012,176387,176387,12935113,2017,14382,3,NaN,2.017021e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1,q1
2358,2027,176483,176483,12935209,2017,14435,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2359,2070,176862,176862,12935588,2017,14629,3,NaN,2.016021e+13,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2360,2092,177232,177232,12935958,2017,14884,3,NaN,0.000000e+00,1.0,...,9997.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2361,2095,177285,177285,12936011,2017,14914,3,NaN,0.000000e+00,1.0,...,2627.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2362,2097,177344,177344,12936070,2017,14941,3,NaN,0.000000e+00,1.0,...,9455.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2363,2098,177345,177345,12936071,2017,14941,3,NaN,0.000000e+00,1.0,...,5618.0,NaN,99.99,9999.99,NaN,NaN,3060.0,81.5,86.1,q1
2364,2124,177607,177607,12937511,2017,15684,3,NaN,2.016031e+13,1.0,...,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1,q1

# dummy variable

In [28]:
data = q1.loc[:, ['SEX','AGE','MARST','RACE','EDUC','IND','EMPSTAT','OCC','OCCLY','INDLY']]

In [29]:
data

      SEX  AGE  MARST  RACE  EDUC   IND  EMPSTAT   OCC   OCCLY   INDLY
0       2   45      1   100    73  1290       10  9620  9620.0  1290.0
1       2   59      1   100    73  7860       10  9120  9120.0  7860.0
2       1   49      6   100    73  6390       10  9130  9130.0  6390.0
3       2   24      6   100    60  1170       10  8800  8800.0  1170.0
4       2   25      6   100   111  8680       10  4040  4040.0  8680.0
5       1   42      1   100    73  2570       10  9130  9130.0  2570.0
6       1   53      1   100    73  4470       10  9130  9130.0  4470.0
7       1   53      1   100    81  7280       10  4220  4220.0  7280.0
8       1   55      1   100    81  8680       10  4020  4020.0  8680.0
9       2   23      6   100    73  4980       12  4030  4030.0  4980.0
10      2   21      6   100    73  4580       10  4250  4030.0  8680.0
11      1   20      6   100    81  8680       10  4060  4060.0  8680.0
12      1   28      4   100    73  8660       10  9140  9140.0  8660.0
13      1   29      6   100    73  5590       10  9640  9640.0  5590.0
14      1   46      1   100    73   770       10  6200  6200.0   770.0
15      1   21      6   100    92  4880       12  9620  4760.0  5270.0
16      1   27      6   100   111     0       34     0  9620.0  6380.0
17      2   19      6   100    73  9590       10  4720  4720.0  9590.0
18      1   49      1   100    73  8180       10  5510  9130.0  2290.0
19      1   55      3   200    73  8590       10  4220  4220.0  8590.0
20      1   43      1   200    81  4090       10  9600  9600.0  4090.0
21      1   25      6   200    60  4090       10  9600  9600.0  4090.0
22      2   52      6   100    50  5380       21  5610  5610.0  5380.0
23      1   54      1   200    73  9370       10  9620  9620.0  9370.0
24      1   35      1   100    40  7790       10  9130  9130.0  7790.0
25      1   19      6   100    73  4470       21  9620  9620.0  4470.0
26      1   34      6   200    73  7690       10  4220  4220.0  7690.0
27      1   53      1   100    73   770       10  6200  6200.0   770.0
28      2   50      1   100    81  7860       10  9120  9120.0  7860.0
29      1   43      1   100    73  4170       10  9600  9600.0  4170.0
...   ...  ...    ...   ...   ...   ...      ...   ...     ...     ...
2335    2   57      1   100   124  7970       10  3060  3060.0  7970.0
2336    1   42      1   100   124  8190       10  3060  3060.0  8190.0
2337    1   49      1   100   124  8180       10  3060  3060.0  8180.0
2338    2   39      1   100   124  8090       10  3060  3060.0  8090.0
2339    1   40      1   100   124  8190       10  3060  3060.0  8190.0
2340    2   30      1   100   123  6470       10  2810  2810.0  6470.0
2341    1   59      1   100   124  8190       10  3060  3060.0  8190.0
2342    1   44      1   100   124  7970       10  3060  3060.0  7970.0
2343    1   50      6   100    73  8270       10  4620  4620.0  8270.0
2344    1   43      1   100   125  8190       10  3060  3060.0  8190.0
2345    2   55      1   651   125  7580       10  3060  3060.0  7580.0
2346    1   50      1   100   124  7970       10  3060  3060.0  8190.0
2347    2   57      6   200    91  8270       10  3030  3060.0  7970.0
2348    1   49      1   100   124  7970       10  3060  3060.0  7970.0
2349    2   50      1   651   124  8190       10  3060  3060.0  8190.0
2350    2   31      1   100   123  7460       12  2810  2810.0  7460.0
2351    1   58      1   100   124  7970       10  3060  3060.0  7970.0
2352    2   40      1   100   124  8190       10  3060  3060.0  8090.0
2353    1   40      1   100   124  8190       10  3060  3060.0  8190.0
2354    2   47      1   100   124  8190       10  3060  3060.0  8190.0
2355    2   50      4   100   111  8290       10  4620  4620.0  8290.0
2356    2   56      1   651   124  7580       10  3060  3060.0  7580.0
2357    2   21      6   100    81  7860       10  4620  4620.0  7860.0
2358    2   51      1   651   124  8190       12  3060  3060.0  8180.0
2359    2   48      1   100   124  8190       10  3060  3060.0  8190.0
2360    2   37      6   651   125  7970       10  3060  3060.0  7970.0
2361    2   27      6   200   124  8190       10  3060  3060.0  8190.0
2362    2   30      1   651   124  8190       10  3060  3060.0  8190.0
2363    1   30      1   651   124  8190       10  3060  3060.0  8190.0
2364    2   42      1   100   111  8270       10  4620  4620.0  8270.0

[2365 rows x 10 columns]

In [30]:
data['male'] = data['SEX']
data.loc[data['male'] != 1 , 'male'] = 0

data['age'] = data['AGE']

data['Married'] = data['MARST']
data.loc[data['Married'].isin([1,2]),'Married'] =1
data.loc[data['Married']!= 1, 'Married'] = 0

#white
data['White'] = data['RACE']
data.loc[data['RACE'] == 100, 'White'] =1
data.loc[data['White'] !=1, 'White'] = 0

# Non-White
data['Non_white'] = data['RACE']
data.loc[data['Non_white']!= 100, 'Non_white'] = 1
data.loc[data['Non_white'] !=1, 'Non_white'] = 0

In [31]:
data['education'] = data['EDUC']
#four_year_college
data.loc[data['EDUC'].isin([123,111,125,124]),'education']=4
# som_college
data.loc[data['EDUC'].isin([80,90,100,110,120,122,81,92,91]),'education']=3
#high_school
data.loc[data['EDUC']==73,'education']=2
# less than high school
data.loc[~data['education'].isin([4,2,3]),'education']=1

# merge Industry

In [32]:
data['ind1'] = data['IND']
# industry replace 0 with INDLY
data.ind1[data.ind1 == 0] = data.INDLY

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [33]:
data.ind1.value_counts().sort_index()

170       5
180       3
390       1
580       1
670       1
680       2
770      82
1070      1
1080     11
1090      9
1170      4
1180     14
1190     12
1270     11
1280     11
1290      1
1370      5
1480      1
1590      2
1680      5
1790      1
1870      6
1880      4
1890      4
1990      8
2070      1
2090      1
2170      1
2190      7
2280      4
       ...
8470      2
8560      8
8570      6
8580      1
8590     45
8660     31
8670      5
8680    361
8690      8
8770     23
8780      1
8790      1
8870     13
8970      2
8980      3
8990      2
9070      2
9080      1
9090      6
9160      6
9170      4
9190      1
9290     18
9370     18
9390      1
9470     11
9480      3
9490      3
9570      6
9590      7
Name: ind1, Length: 203, dtype: int64

In [35]:

data.loc[(data['ind1'] <= 291) & (data['ind1'] >1), 'ind1'] = 1
data.loc[(data['ind1'] >=370) & (data['ind1'] < 491), 'ind1'] = 2
data.loc[(data['ind1'] >=570) & (data['ind1'] < 691), 'ind1'] = 3
data.loc[data['ind1'] == 770, 'ind1'] = 4
data.loc[(data['ind1'] >=1070) & (data['ind1'] < 3991), 'ind1'] = 5
data.loc[(data['ind1'] >=4070) & (data['ind1'] < 4591), 'ind1'] = 6
data.loc[(data['ind1'] >=4670) & (data['ind1'] < 5791), 'ind1'] = 7
data.loc[(data['ind1'] >=6070) & (data['ind1'] < 6391), 'ind1'] = 8
data.loc[(data['ind1'] >=6470) & (data['ind1'] < 6791), 'ind1'] = 9
data.loc[(data['ind1'] >=6870) & (data['ind1'] < 7191), 'ind1'] = 10
data.loc[(data['ind1'] >=7270) & (data['ind1'] < 7791), 'ind1'] = 11
data.loc[(data['ind1'] >=7860) & (data['ind1'] < 8471), 'ind1'] = 12
data.loc[(data['ind1'] >=8560) & (data['ind1'] < 8691), 'ind1'] = 13
data.loc[(data['ind1'] >=8770) & (data['ind1'] < 9291), 'ind1'] = 14
data.loc[(data['ind1'] >=9370) & (data['ind1'] < 9591), 'ind1'] = 15
data.loc[(data['ind1'] >=9670) & (data['ind1'] < 9891), 'ind1'] = 16

# move result

In [36]:

data.loc[(data['EMPSTAT'] == 32) |(data['EMPSTAT'] == 34) |(data['EMPSTAT'] == 36), 'move_result'] = 1

data.loc[((data['EMPSTAT'] == 21) |(data['EMPSTAT'] == 22), 'move_result')] = 2

In [37]:
data.move_result.value_counts().sort_index()

1.0    180
2.0    143
Name: move_result, dtype: int64

In [40]:
# same occ 3
data.loc[(data['OCC']==data['OCCLY']) & (~data['move_result'].isin([1,2])), 'move_result'] = 3

In [41]:
data.move_result.value_counts().sort_index()

1.0     180
2.0     143
3.0    1813
Name: move_result, dtype: int64

In [42]:
# diffrent Low wage job 4



occ_list = pd.read_excel('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q1_q4_occ_list_correct.xlsx')
q1_occ = occ_list['OCC_q1']
q1_occ = pd.DataFrame(q1_occ)
q1_lis = list(q1_occ.values.flatten())
data.loc[(data['OCC'].isin(q1_lis)) &(~data['move_result'].isin([1,2,3])), 'move_result']=4

In [48]:
# Better Job
data.loc[~data['move_result'].isin([1,2,3,4]), 'move_result']=8

In [49]:
data

,SEX,AGE,MARST,RACE,EDUC,IND,EMPSTAT,OCC,OCCLY,INDLY,male,age,Married,White,Non_white,education,ind1,move_result
0,2,45,1,100,73,1290,10,9620,9620.0,1290.0,0,45,1,1,0,2,5,3.0
1,2,59,1,100,73,7860,10,9120,9120.0,7860.0,0,59,1,1,0,2,12,3.0
2,1,49,6,100,73,6390,10,9130,9130.0,6390.0,1,49,0,1,0,2,8,3.0
3,2,24,6,100,60,1170,10,8800,8800.0,1170.0,0,24,0,1,0,1,5,3.0
4,2,25,6,100,111,8680,10,4040,4040.0,8680.0,0,25,0,1,0,4,13,3.0
5,1,42,1,100,73,2570,10,9130,9130.0,2570.0,1,42,1,1,0,2,5,3.0
6,1,53,1,100,73,4470,10,9130,9130.0,4470.0,1,53,1,1,0,2,6,3.0
7,1,53,1,100,81,7280,10,4220,4220.0,7280.0,1,53,1,1,0,3,11,3.0
8,1,55,1,100,81,8680,10,4020,4020.0,8680.0,1,55,1,1,0,3,13,3.0
9,2,23,6,100,73,4980,12,4030,4030.0,4980.0,0,23,0,1,0,2,7,3.0
10,2,21,6,100,73,4580,10,4250,4030.0,8680.0,0,21,0,1,0,2,6,4.0
11,1,20,6,100,81,8680,10,4060,4060.0,8680.0,1,20,0,1,0,3,13,3.0
12,1,28,4,100,73,8660,10,9140,9140.0,8660.0,1,28,0,1,0,2,13,3.0
13,1,29,6,100,73,5590,10,9640,9640.0,5590.0,1,29,0,1,0,2,7,3.0
14,1,46,1,100,73,770,10,6200,6200.0,770.0,1,46,1,1,0,2,4,3.0
15,1,21,6,100,92,4880,12,9620,4760.0,5270.0,1,21,0,1,0,3,7,4.0
16,1,27,6,100,111,0,34,0,9620.0,6380.0,1,27,0,1,0,4,8,1.0
17,2,19,6,100,73,9590,10,4720,4720.0,9590.0,0,19,0,1,0,2,15,3.0
18,1,49,1,100,73,8180,10,5510,9130.0,2290.0,1,49,1,1,0,2,12,4.0
19,1,55,3,200,73,8590,10,4220,4220.0,8590.0,1,55,0,0,1,2,13,3.0
20,1,43,1,200,81,4090,10,9600,9600.0,4090.0,1,43,1,0,1,3,6,3.0
21,1,25,6,200,60,4090,10,9600,9600.0,4090.0,1,25,0,0,1,1,6,3.0
22,2,52,6,100,50,5380,21,5610,5610.0,5380.0,0,52,0,1,0,1,7,2.0
23,1,54,1,200,73,9370,10,9620,9620.0,9370.0,1,54,1,0,1,2,15,3.0
24,1,35,1,100,40,7790,10,9130,9130.0,7790.0,1,35,1,1,0,1,11,3.0
25,1,19,6,100,73,4470,21,9620,9620.0,4470.0,1,19,0,1,0,2,6,2.0
26,1,34,6,200,73,7690,10,4220,4220.0,7690.0,1,34,0,0,1,2,11,3.0
27,1,53,1,100,73,770,10,6200,6200.0,770.0,1,53,1,1,0,2,4,3.0
28,2,50,1,100,81,7860,10,9120,9120.0,7860.0,0,50,1,1,0,3,12,3.0
29,1,43,1,100,73,4170,10,9600,9600.0,4170.0,1,43,1,1,0,2,6,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,2,57,1,100,124,7970,10,3060,3060.0,7970.0,0,57,1,1,0,4,12,3.0
2336,1,42,1,100,124,8190,10,3060,3060.0,8190.0,1,42,1,1,0,4,12,3.0
2337,1,49,1,100,124,8180,10,3060,3060.0,8180.0,1,49,1,1,0,4,12,3.0
2338,2,39,1,100,124,8090,10,3060,3060.0,8090.0,0,39,1,1,0,4,12,3.0
2339,1,40,1,100,124,8190,10,3060,3060.0,8190.0,1,40,1,1,0,4,12,3.0
2340,2,30,1,100,123,6470,10,2810,2810.0,6470.0,0,30,1,1,0,4,9,3.0
2341,1,59,1,100,124,8190,10,3060,3060.0,8190.0,1,59,1,1,0,4,12,3.0
2342,1,44,1,100,124,7970,10,3060,3060.0,7970.0,1,44,1,1,0,4,12,3.0
2343,1,50,6,100,73,8270,10,4620,4620.0,8270.0,1,50,0,1,0,2,12,3.0
2344,1,43,1,100,125,8190,10,3060,3060.0,8190.0,1,43,1,1,0,4,12,3.0
2345,2,55,1,651,125,7580,10,3060,3060.0,7580.0,0,55,1,0,1,4,11,3.0
2346,1,50,1,100,124,7970,10,3060,3060.0,8190.0,1,50,1,1,0,4,12,3.0
2347,2,57,6,200,91,8270,10,3030,3060.0,7970.0,0,57,0,0,1,3,12,8.0
2348,1,49,1,100,124,7970,10,3060,3060.0,7970.0,1,49,1,1,0,4,12,3.0
2349,2,50,1,651,124,8190,10,3060,3060.0,8190.0,0,50,1,0,1,4,12,3.0
2350,2,31,1,100,123,7460,12,2810,2810.0,7460.0,0,31,1,1,0,4,11,3.0
2351,1,58,1,100,124,7970,10,3060,3060.0,7970.0,1,58,1,1,0,4,12,3.0
2352,2,40,1,100,124,8190,10,3060,3060.0,8090.0,0,40,1,1,0,4,12,3.0
2353,1,40,1,100,124,8190,10,3060,3060.0,8190.0,1,40,1,1,0,4,12,3.0
2354,2,47,1,100,124,8190,10,3060,3060.0,8190.0,0,47,1,1,0,4,12,3.0
2355,2,50,4,100,111,8290,10,4620,4620.0,8290.0,0,50,0,1,0,4,12,3.0
2356,2,56,1,651,124,7580,10,3060,3060.0,7580.0,0,56,1,0,1,4,11,3.0
2357,2,21,6,100,81,7860,10,4620,4620.0,7860.0,0,21,0,1,0,3,12,3.0
2358,2,51,1,651,124,8190,12,3060,3060.0,8180.0,0,51,1,0,1,4,12,3.0
2359,2,48,1,100,124,8190,10,3060,3060.0,8190.0,0,48,1,1,0,4,12,3.0
2360,2,37,6,651,125,7970,10,3060,3060.0,7970.0,0,37,0,0,1,4,12,3.0
2361,2,27,6,200,124,8190,10,3060,3060.0,8190.0,0,27,0,0,1,4,12,3.0
2362,2,30,1,651,124,8190,10,3060,3060.0,8190.0,0,30,1,0,1,4,12,3.0
2363,1,30,1,651,124,8190,10,3060,3060.0,8190.0,1,30,1,0,1,4,12,3.0
2364,2,42,1,100,111,8270,10,4620,4620.0,8270.0,0,42,1,1,0,4,12,3.0

In [56]:
# pick up industry base
inds = data.ind1.value_counts().sort_index()
inds = pd.DataFrame(inds)
inds.columns = ['num_of_employee']
inds = inds.reset_index()
inds['%_of_employee_in_iND']= inds.num_of_employee/2365 *100
inds

    index  num_of_employee  %_of_employee_in_iND
0       1                8              0.338266
1       2                1              0.042283
2       3                4              0.169133
3       4               82              3.467230
4       5              271             11.458774
5       6              116              4.904863
6       7              483             20.422833
7       8              202              8.541226
8       9               31              1.310782
9      10               60              2.536998
10     11              224              9.471459
11     12              286             12.093023
12     13              465             19.661734
13     14               83              3.509514
14     15               49              2.071882

In [57]:
inds.num_of_employee.sum()

2365

In [58]:
# set industry 1 as base industry
data['Ind_with_base'] = data['ind1']
data.loc[data['ind1'].isin([1,2,3,4,6,9,10,14,15]), 'Ind_with_base']= 1

In [59]:
data

,SEX,AGE,MARST,RACE,EDUC,IND,EMPSTAT,OCC,OCCLY,INDLY,male,age,Married,White,Non_white,education,ind1,move_result,Ind_with_base
0,2,45,1,100,73,1290,10,9620,9620.0,1290.0,0,45,1,1,0,2,5,3.0,5
1,2,59,1,100,73,7860,10,9120,9120.0,7860.0,0,59,1,1,0,2,12,3.0,12
2,1,49,6,100,73,6390,10,9130,9130.0,6390.0,1,49,0,1,0,2,8,3.0,8
3,2,24,6,100,60,1170,10,8800,8800.0,1170.0,0,24,0,1,0,1,5,3.0,5
4,2,25,6,100,111,8680,10,4040,4040.0,8680.0,0,25,0,1,0,4,13,3.0,13
5,1,42,1,100,73,2570,10,9130,9130.0,2570.0,1,42,1,1,0,2,5,3.0,5
6,1,53,1,100,73,4470,10,9130,9130.0,4470.0,1,53,1,1,0,2,6,3.0,1
7,1,53,1,100,81,7280,10,4220,4220.0,7280.0,1,53,1,1,0,3,11,3.0,11
8,1,55,1,100,81,8680,10,4020,4020.0,8680.0,1,55,1,1,0,3,13,3.0,13
9,2,23,6,100,73,4980,12,4030,4030.0,4980.0,0,23,0,1,0,2,7,3.0,7
10,2,21,6,100,73,4580,10,4250,4030.0,8680.0,0,21,0,1,0,2,6,4.0,1
11,1,20,6,100,81,8680,10,4060,4060.0,8680.0,1,20,0,1,0,3,13,3.0,13
12,1,28,4,100,73,8660,10,9140,9140.0,8660.0,1,28,0,1,0,2,13,3.0,13
13,1,29,6,100,73,5590,10,9640,9640.0,5590.0,1,29,0,1,0,2,7,3.0,7
14,1,46,1,100,73,770,10,6200,6200.0,770.0,1,46,1,1,0,2,4,3.0,1
15,1,21,6,100,92,4880,12,9620,4760.0,5270.0,1,21,0,1,0,3,7,4.0,7
16,1,27,6,100,111,0,34,0,9620.0,6380.0,1,27,0,1,0,4,8,1.0,8
17,2,19,6,100,73,9590,10,4720,4720.0,9590.0,0,19,0,1,0,2,15,3.0,1
18,1,49,1,100,73,8180,10,5510,9130.0,2290.0,1,49,1,1,0,2,12,4.0,12
19,1,55,3,200,73,8590,10,4220,4220.0,8590.0,1,55,0,0,1,2,13,3.0,13
20,1,43,1,200,81,4090,10,9600,9600.0,4090.0,1,43,1,0,1,3,6,3.0,1
21,1,25,6,200,60,4090,10,9600,9600.0,4090.0,1,25,0,0,1,1,6,3.0,1
22,2,52,6,100,50,5380,21,5610,5610.0,5380.0,0,52,0,1,0,1,7,2.0,7
23,1,54,1,200,73,9370,10,9620,9620.0,9370.0,1,54,1,0,1,2,15,3.0,1
24,1,35,1,100,40,7790,10,9130,9130.0,7790.0,1,35,1,1,0,1,11,3.0,11
25,1,19,6,100,73,4470,21,9620,9620.0,4470.0,1,19,0,1,0,2,6,2.0,1
26,1,34,6,200,73,7690,10,4220,4220.0,7690.0,1,34,0,0,1,2,11,3.0,11
27,1,53,1,100,73,770,10,6200,6200.0,770.0,1,53,1,1,0,2,4,3.0,1
28,2,50,1,100,81,7860,10,9120,9120.0,7860.0,0,50,1,1,0,3,12,3.0,12
29,1,43,1,100,73,4170,10,9600,9600.0,4170.0,1,43,1,1,0,2,6,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,2,57,1,100,124,7970,10,3060,3060.0,7970.0,0,57,1,1,0,4,12,3.0,12
2336,1,42,1,100,124,8190,10,3060,3060.0,8190.0,1,42,1,1,0,4,12,3.0,12
2337,1,49,1,100,124,8180,10,3060,3060.0,8180.0,1,49,1,1,0,4,12,3.0,12
2338,2,39,1,100,124,8090,10,3060,3060.0,8090.0,0,39,1,1,0,4,12,3.0,12
2339,1,40,1,100,124,8190,10,3060,3060.0,8190.0,1,40,1,1,0,4,12,3.0,12
2340,2,30,1,100,123,6470,10,2810,2810.0,6470.0,0,30,1,1,0,4,9,3.0,1
2341,1,59,1,100,124,8190,10,3060,3060.0,8190.0,1,59,1,1,0,4,12,3.0,12
2342,1,44,1,100,124,7970,10,3060,3060.0,7970.0,1,44,1,1,0,4,12,3.0,12
2343,1,50,6,100,73,8270,10,4620,4620.0,8270.0,1,50,0,1,0,2,12,3.0,12
2344,1,43,1,100,125,8190,10,3060,3060.0,8190.0,1,43,1,1,0,4,12,3.0,12
2345,2,55,1,651,125,7580,10,3060,3060.0,7580.0,0,55,1,0,1,4,11,3.0,11
2346,1,50,1,100,124,7970,10,3060,3060.0,8190.0,1,50,1,1,0,4,12,3.0,12
2347,2,57,6,200,91,8270,10,3030,3060.0,7970.0,0,57,0,0,1,3,12,8.0,12
2348,1,49,1,100,124,7970,10,3060,3060.0,7970.0,1,49,1,1,0,4,12,3.0,12
2349,2,50,1,651,124,8190,10,3060,3060.0,8190.0,0,50,1,0,1,4,12,3.0,12
2350,2,31,1,100,123,7460,12,2810,2810.0,7460.0,0,31,1,1,0,4,11,3.0,11
2351,1,58,1,100,124,7970,10,3060,3060.0,7970.0,1,58,1,1,0,4,12,3.0,12
2352,2,40,1,100,124,8190,10,3060,3060.0,8090.0,0,40,1,1,0,4,12,3.0,12
2353,1,40,1,100,124,8190,10,3060,3060.0,8190.0,1,40,1,1,0,4,12,3.0,12
2354,2,47,1,100,124,8190,10,3060,3060.0,8190.0,0,47,1,1,0,4,12,3.0,12
2355,2,50,4,100,111,8290,10,4620,4620.0,8290.0,0,50,0,1,0,4,12,3.0,12
2356,2,56,1,651,124,7580,10,3060,3060.0,7580.0,0,56,1,0,1,4,11,3.0,11
2357,2,21,6,100,81,7860,10,4620,4620.0,7860.0,0,21,0,1,0,3,12,3.0,12
2358,2,51,1,651,124,8190,12,3060,3060.0,8180.0,0,51,1,0,1,4,12,3.0,12
2359,2,48,1,100,124,8190,10,3060,3060.0,8190.0,0,48,1,1,0,4,12,3.0,12
2360,2,37,6,651,125,7970,10,3060,3060.0,7970.0,0,37,0,0,1,4,12,3.0,12
2361,2,27,6,200,124,8190,10,3060,3060.0,8190.0,0,27,0,0,1,4,12,3.0,12
2362,2,30,1,651,124,8190,10,3060,3060.0,8190.0,0,30,1,0,1,4,12,3.0,12
2363,1,30,1,651,124,8190,10,3060,3060.0,8190.0,1,30,1,0,1,4,12,3.0,12
2364,2,42,1,100,111,8270,10,4620,4620.0,8270.0,0,42,1,1,0,4,12,3.0,12

In [60]:
data.to_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/Correct_Table4_Dataset_STATA.csv')