In [1]:
import pandas as pd
df = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/All_obs_10counties_presitige.csv')

In [2]:
df = df.loc[(df['AGE']>= 18)& (df['AGE']<=60)]

In [3]:
df.INCTOT.value_counts().sort_index()

-9999.0          5
-9991.0          1
-9985.0          1
-9846.0          1
-2999.0          1
-2000.0          3
-1693.0          1
-1000.0          1
-500.0           1
-153.0           1
 0.0          1246
 1.0            24
 2.0            17
 3.0             9
 4.0             2
 5.0            14
 6.0             4
 7.0             3
 8.0             3
 10.0            8
 11.0            6
 12.0            2
 13.0            1
 14.0            1
 15.0            1
 16.0            5
 17.0            2
 18.0            2
 20.0            4
 21.0            6
              ...
 423711.0        1
 430000.0        1
 433715.0        1
 441364.0        1
 456700.0        1
 474999.0        1
 500145.0        1
 500349.0        1
 500640.0        1
 500943.0        1
 501600.0        1
 504457.0        1
 505134.0        1
 506370.0        1
 506460.0        1
 524500.0        1
 545150.0        1
 550050.0        1
 703121.0        1
 780000.0        1
 801550.0        1
 910000.0        1
 1000240.0       2
 1036066.0       1
 1099999.0       1
 1100001.0       1
 1100499.0       1
 1126109.0       1
 1260002.0       1
 1260202.0       1
Name: INCTOT, Length: 5839, dtype: int64

In [4]:
import numpy as np
d1 = df
d1.loc[d1['INCTOT'].isin([-9999, 0,99999999.0]), 'INCTOT'] =np.nan

In [5]:
d1 = d1[d1['INCTOT'].notnull()]

In [6]:
d1

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
3646,3646,306599,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3647,3647,306600,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6830.0,32.1,37.5
3648,3648,306601,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,900.00,NaN,NaN,6260.0,17.5,36.4
3649,3649,306602,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3650,3650,306603,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0
3652,3652,306605,2010,16896,3,NaN,20091201589500,1.0,NaN,2700.93,...,21.0,8982.0,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1
3653,3653,306606,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,10.0,0.0,NaN,17.60,804.00,NaN,NaN,NaN,NaN,NaN
3654,3654,306607,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,0.0,0.0,NaN,11.00,440.00,NaN,NaN,4510.0,35.0,36.1
3659,3659,306612,2010,16900,3,NaN,20091201589700,1.0,NaN,1485.64,...,0.0,0.0,NaN,17.65,610.00,NaN,NaN,5240.0,35.5,40.4
3660,3660,306613,2010,16901,3,NaN,20091205019000,1.0,NaN,2933.76,...,21.0,4696.0,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4
3663,3663,306616,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,22.0,4051.0,NaN,99.99,9999.99,NaN,NaN,910.0,50.3,48.4
3664,3664,306617,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,21.0,3020.0,NaN,99.99,9999.99,NaN,NaN,7700.0,45.3,47.0
3668,3668,306621,2010,16906,3,NaN,20100102955500,1.0,NaN,2794.72,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3669,3669,306622,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,22.0,6114.0,NaN,99.99,9999.99,NaN,NaN,7840.0,28.4,29.6
3672,3672,306625,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,0.0,6102.0,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1
3673,3673,306626,2010,16909,3,NaN,20100102955600,1.0,NaN,1654.07,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3674,3674,306627,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1
3675,3675,306628,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
3676,3676,306629,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,4138.0,NaN,99.99,9999.99,NaN,NaN,3740.0,43.8,54.1
3677,3677,306630,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,3240.0,NaN,99.99,9999.99,NaN,NaN,NaN,NaN,NaN
3678,3678,306631,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,21.0,4640.0,NaN,99.99,9999.99,NaN,NaN,2010.0,52.4,51.5
3679,3679,306632,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7
3681,3681,306634,2010,16916,3,NaN,20100305524100,1.0,NaN,3162.61,...,21.0,5342.0,NaN,99.99,9999.99,NaN,NaN,4210.0,45.3,36.1
3682,3682,306635,2010,16916,3,NaN,20100305524100,1.0,NaN,3162.61,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3684,3684,306637,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5
3685,3685,306638,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7750.0,28.4,34.0
3687,3687,306640,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,300.00,NaN,NaN,3500.0,41.9,60.0
3688,3688,306641,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3690,3690,306643,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7800.0,34.2,34.9
3691,3691,306644,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177617,177617,12937521,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2720.0,53.2,64.7
177618,177618,12937522,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,16.00,500.00,NaN,NaN,3950.0,14.7,37.2
177625,177625,12937529,2017,15695,3,NaN,20170305706700,1.0,NaN,3981.57,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,5550.0,42.3,47.0
177633,177633,12937537,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,21.0,5832.0,NaN,99.99,9999.99,NaN,NaN,7900.0,47.0,48.3
177634,177634,12937538,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5620.0,35.5,27.4
177635,177635,12937539,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,21.0,3880.0,NaN,10.00,600.00,NaN,NaN,9620.0,17.5,24.0
177636,177636,12937540,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,0.0,0.0,NaN,13.75,550.00,NaN,NaN,4000.0,26.4,30.7
177637,177637,12937541,2017,15707,3,NaN,0,1.0,NaN,1685.76,...,21.0,9047.0,NaN,99.99,9999.99,NaN,NaN,7855.0,28.4,31.7
177639,177639,12937543,2017,15707,3,NaN,0,1.0,NaN,1685.76,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
177642,177642,12937546,2017,15708,3,NaN,0,1.0,NaN,2368.52,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6050.0,18.4,24.5
177647,177647,12937551,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,21.0,9096.0,NaN,99.99,9999.99,NaN,NaN,2320.0,59.6,66.4
177648,177648,12937552,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,10.0,50.3,70.5
177651,177651,12937555,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4840.0,32.8,36.6
177652,177652,12937556,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,21.0,9052.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1
177657,177657,12937561,2017,15712,3,NaN,0,1.0,NaN,2330.46,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
177660,177660,12937564,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,1220.0,50.6,53.0
177661,177661,12937565,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
177664,177664,12937568,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,0.0,0.0,NaN,0.00,9999.99,NaN,NaN,3320.0,61.0,58.5
177665,177665,12937569,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
177668,177668,12937572,2017,15716,3,NaN,0,1.0,NaN,2438.32,...,21.0,9997.0,NaN,0.00,9999.99,NaN,NaN,1410.0,69.4,64.2
177671,177671,12937575,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,3160.0,36.7,61.5
177672,177672,12937576,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,850.0,50.6,48.4
177678,177678,12937582,2017,15719,3,NaN,0,1.0,NaN,2369.66,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4700.0,50.3,44.2
177681,177681,12937585,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,21.0,6883.0,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
177682,177682,12937586,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
177684,177684,12937588,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177685,177685,12937589,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,21.0,6047.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177686,177686,12937590,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177690,177690,12937594,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2630.0,58.2,46.5
177691,177691,12937595,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,10.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7

In [7]:
d1.UHRSWORKT.value_counts().sort_index()

0         7
1         2
2         5
3         6
4        13
5        15
6        18
7         4
8        37
9         7
10       63
11        2
12       37
13        6
14       10
15       87
16       52
17        6
18       24
19        3
20      262
21       12
22        8
23       12
24       66
25      113
26       13
27        7
28       32
29        3
       ...
55      144
56       22
57        6
58        9
59        2
60      265
62        8
63        6
64        8
65       38
66        5
68        3
70       63
72        8
73        2
75       10
76        6
78        5
79        1
80       32
82        1
84        3
85        3
90        4
99        4
100       2
109       1
140       1
997     509
999    2267
Name: UHRSWORKT, Length: 85, dtype: int64

In [8]:
d1.loc[d1['UHRSWORKT'].isin([997,999,0]), 'UHRSWORKT']= np.nan
d1 = d1.loc[d1['UHRSWORKT'].notnull()]
d1

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
3647,3647,306600,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6830.0,32.1,37.5
3648,3648,306601,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,900.00,NaN,NaN,6260.0,17.5,36.4
3650,3650,306603,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0
3652,3652,306605,2010,16896,3,NaN,20091201589500,1.0,NaN,2700.93,...,21.0,8982.0,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1
3653,3653,306606,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,10.0,0.0,NaN,17.60,804.00,NaN,NaN,NaN,NaN,NaN
3654,3654,306607,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,0.0,0.0,NaN,11.00,440.00,NaN,NaN,4510.0,35.0,36.1
3659,3659,306612,2010,16900,3,NaN,20091201589700,1.0,NaN,1485.64,...,0.0,0.0,NaN,17.65,610.00,NaN,NaN,5240.0,35.5,40.4
3660,3660,306613,2010,16901,3,NaN,20091205019000,1.0,NaN,2933.76,...,21.0,4696.0,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4
3663,3663,306616,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,22.0,4051.0,NaN,99.99,9999.99,NaN,NaN,910.0,50.3,48.4
3664,3664,306617,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,21.0,3020.0,NaN,99.99,9999.99,NaN,NaN,7700.0,45.3,47.0
3669,3669,306622,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,22.0,6114.0,NaN,99.99,9999.99,NaN,NaN,7840.0,28.4,29.6
3672,3672,306625,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,0.0,6102.0,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1
3674,3674,306627,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1
3675,3675,306628,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
3676,3676,306629,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,4138.0,NaN,99.99,9999.99,NaN,NaN,3740.0,43.8,54.1
3677,3677,306630,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,3240.0,NaN,99.99,9999.99,NaN,NaN,NaN,NaN,NaN
3678,3678,306631,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,21.0,4640.0,NaN,99.99,9999.99,NaN,NaN,2010.0,52.4,51.5
3679,3679,306632,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7
3681,3681,306634,2010,16916,3,NaN,20100305524100,1.0,NaN,3162.61,...,21.0,5342.0,NaN,99.99,9999.99,NaN,NaN,4210.0,45.3,36.1
3684,3684,306637,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5
3687,3687,306640,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,300.00,NaN,NaN,3500.0,41.9,60.0
3690,3690,306643,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7800.0,34.2,34.9
3693,3693,306646,2010,16922,3,NaN,20090102799100,1.0,NaN,2734.63,...,21.0,4610.0,NaN,99.99,9999.99,NaN,NaN,3620.0,47.8,61.5
3694,3694,306647,2010,16923,3,NaN,20090101460800,1.0,NaN,2829.80,...,21.0,4092.0,NaN,99.99,9999.99,NaN,NaN,4510.0,35.0,36.1
3696,3696,306649,2010,16924,3,NaN,20090103898900,1.0,NaN,2826.59,...,21.0,5661.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
3697,3697,306650,2010,16924,3,NaN,20090103898900,1.0,NaN,2826.59,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,220.0,50.3,56.5
3699,3699,306652,2010,16927,3,NaN,20090103899000,1.0,NaN,1490.52,...,21.0,5472.0,NaN,99.99,9999.99,NaN,NaN,7210.0,36.7,43.6
3700,3700,306653,2010,16927,3,NaN,20090103899000,1.0,NaN,1490.52,...,21.0,5787.0,NaN,99.99,9999.99,NaN,NaN,NaN,NaN,NaN
3703,3703,306656,2010,16928,3,NaN,20090101461000,1.0,NaN,2871.82,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
3707,3707,306660,2010,16930,3,NaN,20090205551000,1.0,NaN,1544.79,...,21.0,8622.0,NaN,99.99,9999.99,NaN,NaN,7020.0,39.2,37.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177607,177607,12937511,2017,15684,3,NaN,20160305717600,1.0,NaN,1998.66,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1
177608,177608,12937512,2017,15684,3,NaN,20160305717600,1.0,NaN,1998.66,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,7300.0,32.8,35.7
177611,177611,12937515,2017,15685,3,NaN,20160305669900,1.0,NaN,3765.30,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,8140.0,40.1,41.9
177612,177612,12937516,2017,15685,3,NaN,20160305669900,1.0,NaN,3765.30,...,21.0,6629.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177613,177613,12937517,2017,15686,3,NaN,20160305692000,1.0,NaN,3755.61,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6355.0,49.2,51.0
177618,177618,12937522,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,16.00,500.00,NaN,NaN,3950.0,14.7,37.2
177625,177625,12937529,2017,15695,3,NaN,20170305706700,1.0,NaN,3981.57,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,5550.0,42.3,47.0
177633,177633,12937537,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,21.0,5832.0,NaN,99.99,9999.99,NaN,NaN,7900.0,47.0,48.3
177634,177634,12937538,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5620.0,35.5,27.4
177635,177635,12937539,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,21.0,3880.0,NaN,10.00,600.00,NaN,NaN,9620.0,17.5,24.0
177636,177636,12937540,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,0.0,0.0,NaN,13.75,550.00,NaN,NaN,4000.0,26.4,30.7
177637,177637,12937541,2017,15707,3,NaN,0,1.0,NaN,1685.76,...,21.0,9047.0,NaN,99.99,9999.99,NaN,NaN,7855.0,28.4,31.7
177642,177642,12937546,2017,15708,3,NaN,0,1.0,NaN,2368.52,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6050.0,18.4,24.5
177647,177647,12937551,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,21.0,9096.0,NaN,99.99,9999.99,NaN,NaN,2320.0,59.6,66.4
177648,177648,12937552,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,10.0,50.3,70.5
177651,177651,12937555,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4840.0,32.8,36.6
177652,177652,12937556,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,21.0,9052.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1
177660,177660,12937564,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,1220.0,50.6,53.0
177661,177661,12937565,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
177664,177664,12937568,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,0.0,0.0,NaN,0.00,9999.99,NaN,NaN,3320.0,61.0,58.5
177665,177665,12937569,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
177668,177668,12937572,2017,15716,3,NaN,0,1.0,NaN,2438.32,...,21.0,9997.0,NaN,0.00,9999.99,NaN,NaN,1410.0,69.4,64.2
177672,177672,12937576,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,850.0,50.6,48.4
177678,177678,12937582,2017,15719,3,NaN,0,1.0,NaN,2369.66,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4700.0,50.3,44.2
177681,177681,12937585,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,21.0,6883.0,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
177682,177682,12937586,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
177685,177685,12937589,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,21.0,6047.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177686,177686,12937590,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177690,177690,12937594,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2630.0,58.2,46.5
177691,177691,12937595,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,10.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7

In [9]:
len(d1)

7852

In [10]:
d1.loc[:, ['UHRSWORKT','INCTOT']]

        UHRSWORKT    INCTOT
3647         50.0   60000.0
3648         60.0   30000.0
3650         40.0   23350.0
3652         52.0   90337.0
3653         40.0   11700.0
3654         40.0   23000.0
3659         40.0   60700.0
3660         46.0   56050.0
3663         45.0   30004.0
3664         40.0   45001.0
3669         40.0   41000.0
3672         40.0   33000.0
3674         30.0   10264.0
3675         45.0   45931.0
3676         58.0   71977.0
3677         39.0   60000.0
3678         40.0   35100.0
3679         40.0   32100.0
3681         60.0   40010.0
3684         45.0   17000.0
3687         20.0   19100.0
3690         20.0   10605.0
3693         37.0   69897.0
3694         24.0    7580.0
3696         40.0   38616.0
3697         40.0   30000.0
3699         45.0   60455.0
3700         32.0   40005.0
3703         16.0    7537.0
3707         40.0   30500.0
...           ...       ...
177607       40.0   60404.0
177608       40.0   75404.0
177611       46.0   59000.0
177612       40.0   28000.0
177613       40.0   45000.0
177618       10.0   10000.0
177625       50.0   50006.0
177633       65.0   67577.0
177634       40.0   13000.0
177635       40.0   29074.0
177636       45.0   32800.0
177637       40.0   45024.0
177642       35.0   38000.0
177647       40.0   80001.0
177648       50.0  250873.0
177651       20.0   35249.0
177652       60.0   85151.0
177660       40.0   88042.0
177661       30.0   27042.0
177664       24.0   66000.0
177665       40.0  150000.0
177668       60.0  115000.0
177672        8.0  176048.0
177678       60.0   50103.0
177681       40.0   28001.0
177682       10.0    5000.0
177685       40.0   58085.0
177686       25.0    4200.0
177690       50.0   57817.0
177691       42.0   37373.0

[7852 rows x 2 columns]

In [11]:
# d12
d1 = df
d1.loc[d1['INCTOT'].isin([-9999, 0,99999999.0]), 'INCTOT'] =np.nan
d1 = d1[d1['INCTOT'].notnull()]

In [12]:
d1.loc[d1['WKSWORK1']==0, 'WKSWORK1']=np.nan

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [13]:
d12 = d1.loc[d1['WKSWORK1'].notnull()]

In [14]:
len(d12)

9117

In [15]:
d12.loc[:, ['WKSWORK1','INCTOT']]

        WKSWORK1    INCTOT
3646        52.0   19200.0
3647        52.0   60000.0
3648        40.0   30000.0
3650        32.0   23350.0
3652        52.0   90337.0
3653        52.0   11700.0
3654        52.0   23000.0
3659        52.0   60700.0
3660        52.0   56050.0
3663        52.0   30004.0
3664        52.0   45001.0
3669        52.0   41000.0
3672        52.0   33000.0
3674        50.0   10264.0
3675        52.0   45931.0
3676        52.0   71977.0
3677        52.0   60000.0
3678        52.0   35100.0
3679        52.0   32100.0
3681        52.0   40010.0
3684        52.0   17000.0
3685        35.0   20000.0
3687        52.0   19100.0
3690        43.0   10605.0
3691        52.0   30715.0
3693        52.0   69897.0
3694        40.0    7580.0
3696        52.0   38616.0
3697        52.0   30000.0
3699        33.0   60455.0
...          ...       ...
177612      52.0   28000.0
177613      52.0   45000.0
177617      30.0   20440.0
177618      16.0   10000.0
177625      52.0   50006.0
177633      52.0   67577.0
177634      51.0   13000.0
177635      52.0   29074.0
177636      52.0   32800.0
177637      52.0   45024.0
177642      52.0   38000.0
177647      41.0   80001.0
177648      52.0  250873.0
177651      50.0   35249.0
177652      42.0   85151.0
177660      52.0   88042.0
177661      52.0   27042.0
177664      52.0   66000.0
177665      52.0  150000.0
177668      52.0  115000.0
177671      44.0   53058.0
177672      50.0  176048.0
177678      52.0   50103.0
177681      52.0   28001.0
177682      52.0    5000.0
177684      50.0   18026.0
177685      52.0   58085.0
177686      15.0    4200.0
177690      52.0   57817.0
177691      52.0   37373.0

[9117 rows x 2 columns]

In [16]:
# d13
d1.INCTOT.value_counts().sort_index()

-9991.0        1
-9985.0        1
-9846.0        1
-2999.0        1
-2000.0        3
-1693.0        1
-1000.0        1
-500.0         1
-153.0         1
 1.0          24
 2.0          17
 3.0           9
 4.0           2
 5.0          14
 6.0           4
 7.0           3
 8.0           3
 10.0          8
 11.0          6
 12.0          2
 13.0          1
 14.0          1
 15.0          1
 16.0          5
 17.0          2
 18.0          2
 20.0          4
 21.0          6
 23.0          1
 25.0          5
              ..
 423711.0      1
 430000.0      1
 433715.0      1
 441364.0      1
 456700.0      1
 474999.0      1
 500145.0      1
 500349.0      1
 500640.0      1
 500943.0      1
 501600.0      1
 504457.0      1
 505134.0      1
 506370.0      1
 506460.0      1
 524500.0      1
 545150.0      1
 550050.0      1
 703121.0      1
 780000.0      1
 801550.0      1
 910000.0      1
 1000240.0     2
 1036066.0     1
 1099999.0     1
 1100001.0     1
 1100499.0     1
 1126109.0     1
 1260002.0     1
 1260202.0     1
Name: INCTOT, Length: 5837, dtype: int64

In [17]:
d1[d1['INCTOT'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, YEAR, SERIAL, MONTH, HWTFINL, CPSID, ASECFLAG, HFLAG, ASECWTH, STATEFIP, COUNTY, PERNUM, WTFINL, CPSIDP, ASECWT, AGE, SEX, RACE, MARST, EMPSTAT, OCC, OCC2010_x, IND, CLASSWKR, UHRSWORKT, EDUC, EDUC99, EDDIPGED, OCCLY, INDLY, OCC90LY, IND90LY, OCC10LY, CLASSWLY, WORKLY, WKSWORK1, UHRSWORKLY, WKSUNEM1, WKXPNS, INCTOT, INCWAGE, PAIDGH, EMCONTRB, JTOCC, HOURWAGE, EARNWEEK, UHRSWORKORG, WKSWORKORG, OCC2010_y, PRESGL, PRENT]
Index: []

[0 rows x 52 columns]

In [18]:
d1

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
3646,3646,306599,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3647,3647,306600,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6830.0,32.1,37.5
3648,3648,306601,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,900.00,NaN,NaN,6260.0,17.5,36.4
3649,3649,306602,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3650,3650,306603,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0
3652,3652,306605,2010,16896,3,NaN,20091201589500,1.0,NaN,2700.93,...,21.0,8982.0,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1
3653,3653,306606,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,10.0,0.0,NaN,17.60,804.00,NaN,NaN,NaN,NaN,NaN
3654,3654,306607,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,0.0,0.0,NaN,11.00,440.00,NaN,NaN,4510.0,35.0,36.1
3659,3659,306612,2010,16900,3,NaN,20091201589700,1.0,NaN,1485.64,...,0.0,0.0,NaN,17.65,610.00,NaN,NaN,5240.0,35.5,40.4
3660,3660,306613,2010,16901,3,NaN,20091205019000,1.0,NaN,2933.76,...,21.0,4696.0,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4
3663,3663,306616,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,22.0,4051.0,NaN,99.99,9999.99,NaN,NaN,910.0,50.3,48.4
3664,3664,306617,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,21.0,3020.0,NaN,99.99,9999.99,NaN,NaN,7700.0,45.3,47.0
3668,3668,306621,2010,16906,3,NaN,20100102955500,1.0,NaN,2794.72,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3669,3669,306622,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,22.0,6114.0,NaN,99.99,9999.99,NaN,NaN,7840.0,28.4,29.6
3672,3672,306625,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,0.0,6102.0,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1
3673,3673,306626,2010,16909,3,NaN,20100102955600,1.0,NaN,1654.07,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3674,3674,306627,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1
3675,3675,306628,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
3676,3676,306629,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,4138.0,NaN,99.99,9999.99,NaN,NaN,3740.0,43.8,54.1
3677,3677,306630,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,3240.0,NaN,99.99,9999.99,NaN,NaN,NaN,NaN,NaN
3678,3678,306631,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,21.0,4640.0,NaN,99.99,9999.99,NaN,NaN,2010.0,52.4,51.5
3679,3679,306632,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7
3681,3681,306634,2010,16916,3,NaN,20100305524100,1.0,NaN,3162.61,...,21.0,5342.0,NaN,99.99,9999.99,NaN,NaN,4210.0,45.3,36.1
3682,3682,306635,2010,16916,3,NaN,20100305524100,1.0,NaN,3162.61,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3684,3684,306637,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5
3685,3685,306638,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7750.0,28.4,34.0
3687,3687,306640,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,300.00,NaN,NaN,3500.0,41.9,60.0
3688,3688,306641,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3690,3690,306643,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7800.0,34.2,34.9
3691,3691,306644,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177617,177617,12937521,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2720.0,53.2,64.7
177618,177618,12937522,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,16.00,500.00,NaN,NaN,3950.0,14.7,37.2
177625,177625,12937529,2017,15695,3,NaN,20170305706700,1.0,NaN,3981.57,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,5550.0,42.3,47.0
177633,177633,12937537,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,21.0,5832.0,NaN,99.99,9999.99,NaN,NaN,7900.0,47.0,48.3
177634,177634,12937538,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5620.0,35.5,27.4
177635,177635,12937539,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,21.0,3880.0,NaN,10.00,600.00,NaN,NaN,9620.0,17.5,24.0
177636,177636,12937540,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,0.0,0.0,NaN,13.75,550.00,NaN,NaN,4000.0,26.4,30.7
177637,177637,12937541,2017,15707,3,NaN,0,1.0,NaN,1685.76,...,21.0,9047.0,NaN,99.99,9999.99,NaN,NaN,7855.0,28.4,31.7
177639,177639,12937543,2017,15707,3,NaN,0,1.0,NaN,1685.76,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
177642,177642,12937546,2017,15708,3,NaN,0,1.0,NaN,2368.52,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6050.0,18.4,24.5
177647,177647,12937551,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,21.0,9096.0,NaN,99.99,9999.99,NaN,NaN,2320.0,59.6,66.4
177648,177648,12937552,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,10.0,50.3,70.5
177651,177651,12937555,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4840.0,32.8,36.6
177652,177652,12937556,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,21.0,9052.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1
177657,177657,12937561,2017,15712,3,NaN,0,1.0,NaN,2330.46,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
177660,177660,12937564,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,1220.0,50.6,53.0
177661,177661,12937565,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
177664,177664,12937568,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,0.0,0.0,NaN,0.00,9999.99,NaN,NaN,3320.0,61.0,58.5
177665,177665,12937569,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
177668,177668,12937572,2017,15716,3,NaN,0,1.0,NaN,2438.32,...,21.0,9997.0,NaN,0.00,9999.99,NaN,NaN,1410.0,69.4,64.2
177671,177671,12937575,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,3160.0,36.7,61.5
177672,177672,12937576,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,850.0,50.6,48.4
177678,177678,12937582,2017,15719,3,NaN,0,1.0,NaN,2369.66,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4700.0,50.3,44.2
177681,177681,12937585,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,21.0,6883.0,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
177682,177682,12937586,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
177684,177684,12937588,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177685,177685,12937589,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,21.0,6047.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177686,177686,12937590,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177690,177690,12937594,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2630.0,58.2,46.5
177691,177691,12937595,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,10.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7

In [19]:
d1['UHRSWORKLY'].value_counts().sort_index()

1.0         3
2.0         7
3.0        10
4.0        22
5.0        15
6.0        34
7.0         8
8.0        45
9.0         6
10.0       91
11.0        1
12.0       50
13.0        8
14.0       12
15.0      127
16.0       51
17.0        8
18.0       28
19.0        4
20.0      389
21.0       12
22.0       10
23.0       15
24.0       85
25.0      181
26.0        6
27.0       11
28.0       25
30.0      293
31.0        5
         ...
49.0        7
50.0      629
52.0       74
53.0        5
54.0        7
55.0      154
56.0       16
57.0        1
58.0        8
60.0      309
62.0        3
63.0        6
64.0        4
65.0       45
66.0        1
67.0        1
68.0        4
70.0       71
72.0        8
73.0        1
74.0        1
75.0       17
76.0        4
78.0        1
80.0       32
84.0        3
88.0        2
90.0        3
99.0        7
999.0    1518
Name: UHRSWORKLY, Length: 77, dtype: int64

In [20]:
d1.loc[d1['UHRSWORKLY']==999, 'UHRSWORKLY']=np.nan
d13 = d1.loc[d1['UHRSWORKLY'].notnull()]
d13

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
3646,3646,306599,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3647,3647,306600,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6830.0,32.1,37.5
3648,3648,306601,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,900.00,NaN,NaN,6260.0,17.5,36.4
3650,3650,306603,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0
3652,3652,306605,2010,16896,3,NaN,20091201589500,1.0,NaN,2700.93,...,21.0,8982.0,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1
3653,3653,306606,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,10.0,0.0,NaN,17.60,804.00,NaN,NaN,NaN,NaN,NaN
3654,3654,306607,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,0.0,0.0,NaN,11.00,440.00,NaN,NaN,4510.0,35.0,36.1
3659,3659,306612,2010,16900,3,NaN,20091201589700,1.0,NaN,1485.64,...,0.0,0.0,NaN,17.65,610.00,NaN,NaN,5240.0,35.5,40.4
3660,3660,306613,2010,16901,3,NaN,20091205019000,1.0,NaN,2933.76,...,21.0,4696.0,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4
3663,3663,306616,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,22.0,4051.0,NaN,99.99,9999.99,NaN,NaN,910.0,50.3,48.4
3664,3664,306617,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,21.0,3020.0,NaN,99.99,9999.99,NaN,NaN,7700.0,45.3,47.0
3669,3669,306622,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,22.0,6114.0,NaN,99.99,9999.99,NaN,NaN,7840.0,28.4,29.6
3672,3672,306625,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,0.0,6102.0,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1
3674,3674,306627,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1
3675,3675,306628,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
3676,3676,306629,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,4138.0,NaN,99.99,9999.99,NaN,NaN,3740.0,43.8,54.1
3677,3677,306630,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,3240.0,NaN,99.99,9999.99,NaN,NaN,NaN,NaN,NaN
3678,3678,306631,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,21.0,4640.0,NaN,99.99,9999.99,NaN,NaN,2010.0,52.4,51.5
3679,3679,306632,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7
3681,3681,306634,2010,16916,3,NaN,20100305524100,1.0,NaN,3162.61,...,21.0,5342.0,NaN,99.99,9999.99,NaN,NaN,4210.0,45.3,36.1
3684,3684,306637,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5
3685,3685,306638,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7750.0,28.4,34.0
3687,3687,306640,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,300.00,NaN,NaN,3500.0,41.9,60.0
3690,3690,306643,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7800.0,34.2,34.9
3691,3691,306644,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
3693,3693,306646,2010,16922,3,NaN,20090102799100,1.0,NaN,2734.63,...,21.0,4610.0,NaN,99.99,9999.99,NaN,NaN,3620.0,47.8,61.5
3694,3694,306647,2010,16923,3,NaN,20090101460800,1.0,NaN,2829.80,...,21.0,4092.0,NaN,99.99,9999.99,NaN,NaN,4510.0,35.0,36.1
3696,3696,306649,2010,16924,3,NaN,20090103898900,1.0,NaN,2826.59,...,21.0,5661.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
3697,3697,306650,2010,16924,3,NaN,20090103898900,1.0,NaN,2826.59,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,220.0,50.3,56.5
3699,3699,306652,2010,16927,3,NaN,20090103899000,1.0,NaN,1490.52,...,21.0,5472.0,NaN,99.99,9999.99,NaN,NaN,7210.0,36.7,43.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177612,177612,12937516,2017,15685,3,NaN,20160305669900,1.0,NaN,3765.30,...,21.0,6629.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177613,177613,12937517,2017,15686,3,NaN,20160305692000,1.0,NaN,3755.61,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6355.0,49.2,51.0
177617,177617,12937521,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2720.0,53.2,64.7
177618,177618,12937522,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,16.00,500.00,NaN,NaN,3950.0,14.7,37.2
177625,177625,12937529,2017,15695,3,NaN,20170305706700,1.0,NaN,3981.57,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,5550.0,42.3,47.0
177633,177633,12937537,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,21.0,5832.0,NaN,99.99,9999.99,NaN,NaN,7900.0,47.0,48.3
177634,177634,12937538,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5620.0,35.5,27.4
177635,177635,12937539,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,21.0,3880.0,NaN,10.00,600.00,NaN,NaN,9620.0,17.5,24.0
177636,177636,12937540,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,0.0,0.0,NaN,13.75,550.00,NaN,NaN,4000.0,26.4,30.7
177637,177637,12937541,2017,15707,3,NaN,0,1.0,NaN,1685.76,...,21.0,9047.0,NaN,99.99,9999.99,NaN,NaN,7855.0,28.4,31.7
177642,177642,12937546,2017,15708,3,NaN,0,1.0,NaN,2368.52,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6050.0,18.4,24.5
177647,177647,12937551,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,21.0,9096.0,NaN,99.99,9999.99,NaN,NaN,2320.0,59.6,66.4
177648,177648,12937552,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,10.0,50.3,70.5
177651,177651,12937555,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4840.0,32.8,36.6
177652,177652,12937556,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,21.0,9052.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1
177660,177660,12937564,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,1220.0,50.6,53.0
177661,177661,12937565,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
177664,177664,12937568,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,0.0,0.0,NaN,0.00,9999.99,NaN,NaN,3320.0,61.0,58.5
177665,177665,12937569,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
177668,177668,12937572,2017,15716,3,NaN,0,1.0,NaN,2438.32,...,21.0,9997.0,NaN,0.00,9999.99,NaN,NaN,1410.0,69.4,64.2
177671,177671,12937575,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,3160.0,36.7,61.5
177672,177672,12937576,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,850.0,50.6,48.4
177678,177678,12937582,2017,15719,3,NaN,0,1.0,NaN,2369.66,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4700.0,50.3,44.2
177681,177681,12937585,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,21.0,6883.0,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
177682,177682,12937586,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
177684,177684,12937588,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177685,177685,12937589,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,21.0,6047.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177686,177686,12937590,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177690,177690,12937594,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2630.0,58.2,46.5
177691,177691,12937595,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,10.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7

In [21]:
d13['UHRSWORKLY'].value_counts().sort_index()

1.0       3
2.0       7
3.0      10
4.0      22
5.0      15
6.0      34
7.0       8
8.0      45
9.0       6
10.0     91
11.0      1
12.0     50
13.0      8
14.0     12
15.0    127
16.0     51
17.0      8
18.0     28
19.0      4
20.0    389
21.0     12
22.0     10
23.0     15
24.0     85
25.0    181
26.0      6
27.0     11
28.0     25
30.0    293
31.0      5
       ...
48.0     79
49.0      7
50.0    629
52.0     74
53.0      5
54.0      7
55.0    154
56.0     16
57.0      1
58.0      8
60.0    309
62.0      3
63.0      6
64.0      4
65.0     45
66.0      1
67.0      1
68.0      4
70.0     71
72.0      8
73.0      1
74.0      1
75.0     17
76.0      4
78.0      1
80.0     32
84.0      3
88.0      2
90.0      3
99.0      7
Name: UHRSWORKLY, Length: 76, dtype: int64

In [22]:
d13.loc[d13['UHRSWORKLY'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, YEAR, SERIAL, MONTH, HWTFINL, CPSID, ASECFLAG, HFLAG, ASECWTH, STATEFIP, COUNTY, PERNUM, WTFINL, CPSIDP, ASECWT, AGE, SEX, RACE, MARST, EMPSTAT, OCC, OCC2010_x, IND, CLASSWKR, UHRSWORKT, EDUC, EDUC99, EDDIPGED, OCCLY, INDLY, OCC90LY, IND90LY, OCC10LY, CLASSWLY, WORKLY, WKSWORK1, UHRSWORKLY, WKSUNEM1, WKXPNS, INCTOT, INCWAGE, PAIDGH, EMCONTRB, JTOCC, HOURWAGE, EARNWEEK, UHRSWORKORG, WKSWORKORG, OCC2010_y, PRESGL, PRENT]
Index: []

[0 rows x 52 columns]

In [23]:
len(d13)

9117

In [24]:
d13.loc[:, ['INCTOT','UHRSWORKLY']]

          INCTOT  UHRSWORKLY
3646     19200.0        20.0
3647     60000.0        50.0
3648     30000.0        40.0
3650     23350.0        40.0
3652     90337.0        50.0
3653     11700.0        40.0
3654     23000.0        40.0
3659     60700.0        40.0
3660     56050.0        46.0
3663     30004.0        45.0
3664     45001.0        40.0
3669     41000.0        40.0
3672     33000.0        40.0
3674     10264.0        10.0
3675     45931.0        40.0
3676     71977.0        42.0
3677     60000.0        38.0
3678     35100.0        40.0
3679     32100.0        40.0
3681     40010.0        60.0
3684     17000.0        45.0
3685     20000.0        50.0
3687     19100.0        20.0
3690     10605.0        20.0
3691     30715.0        40.0
3693     69897.0        37.0
3694      7580.0        11.0
3696     38616.0        40.0
3697     30000.0        40.0
3699     60455.0        40.0
...          ...         ...
177612   28000.0        40.0
177613   45000.0        40.0
177617   20440.0        20.0
177618   10000.0         6.0
177625   50006.0        45.0
177633   67577.0        55.0
177634   13000.0        28.0
177635   29074.0        40.0
177636   32800.0        40.0
177637   45024.0        45.0
177642   38000.0        35.0
177647   80001.0        40.0
177648  250873.0        40.0
177651   35249.0        20.0
177652   85151.0        40.0
177660   88042.0        40.0
177661   27042.0        30.0
177664   66000.0        24.0
177665  150000.0        40.0
177668  115000.0        60.0
177671   53058.0         6.0
177672  176048.0        40.0
177678   50103.0        60.0
177681   28001.0        40.0
177682    5000.0        10.0
177684   18026.0        30.0
177685   58085.0        40.0
177686    4200.0        25.0
177690   57817.0        50.0
177691   37373.0        40.0

[9117 rows x 2 columns]

In [25]:
# d14
d1['WKSUNEM1'].value_counts().sort_index()

0.0     1187
1.0       27
2.0       34
3.0       10
4.0       53
5.0       11
6.0       27
7.0       17
8.0       52
9.0       10
10.0      21
11.0       3
12.0     117
13.0      16
14.0       7
15.0       3
16.0      37
17.0      19
18.0       7
19.0       5
20.0      36
22.0      28
23.0       1
24.0      16
25.0       2
26.0      64
27.0      12
28.0      30
30.0      10
32.0      35
34.0       6
35.0       6
36.0      29
37.0       6
38.0       8
39.0       9
40.0      28
41.0       1
42.0      11
43.0       3
44.0      23
45.0       3
46.0      14
47.0       3
48.0      12
49.0       5
50.0       7
51.0       5
99.0    8559
Name: WKSUNEM1, dtype: int64

In [26]:
d1.loc[d1['WKSUNEM1'].isin([0,99]), 'WKSUNEM1']= np.nan
d14 = d1.loc[d1['WKSUNEM1'].notnull()]

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [27]:
d14.loc[:, ['WKSUNEM1', 'INCTOT']]

        WKSUNEM1   INCTOT
3685        17.0  20000.0
3699        19.0  60455.0
3728         4.0  15012.0
3771        32.0  11375.0
3776        12.0  43264.0
3870        28.0  28050.0
3911        12.0  29000.0
3928         4.0   5300.0
3935        40.0  15180.0
3939        28.0  50000.0
3945         1.0  12000.0
3956        18.0  37622.0
3973        46.0  58000.0
3990        12.0  10325.0
4009        44.0  11603.0
4010        20.0   7096.0
4062        12.0  54100.0
4155         1.0  11053.0
4210         1.0   2030.0
4223        12.0  15800.0
4253        36.0  14316.0
4333        12.0  10800.0
4360         4.0  25459.0
4375        12.0  62362.0
4380         7.0  82750.0
4389        44.0  14387.0
4395         1.0   2000.0
4477        10.0  50361.0
4481        26.0   2530.0
4553        44.0   8600.0
...          ...      ...
176819       4.0  28000.0
176853      12.0  26400.0
176875       6.0  59249.0
176895      32.0  14016.0
176913      36.0  36000.0
176991       4.0  33450.0
176992      13.0  11750.0
177019      28.0   6113.0
177033      12.0   9000.0
177047       6.0  11680.0
177072       3.0   6484.0
177120      16.0   5472.0
177163       8.0   4000.0
177165      26.0   7900.0
177171       2.0  22000.0
177214      24.0   4500.0
177215      24.0   2618.0
177218       4.0  60000.0
177319      12.0  10000.0
177355      26.0  32484.0
177447      48.0   1500.0
177453       2.0  12800.0
177466       4.0  41000.0
177491       4.0  22000.0
177496      13.0  28020.0
177516      26.0   1013.0
177520       4.0  60000.0
177527      32.0   7000.0
177536      42.0  15905.0
177597      20.0    600.0

[889 rows x 2 columns]

In [28]:
len(d14)

889

In [29]:
# d21
d2 = df
d2['INCWAGE'].value_counts().sort_index()

0.0          3100
40.0            1
78.0            1
85.0            1
99.0            1
100.0           1
150.0           4
170.0           1
180.0           1
200.0           5
210.0           1
238.0           1
250.0           2
300.0          14
315.0           1
325.0           1
350.0           1
360.0           1
384.0           1
400.0           4
414.0           1
450.0           2
480.0           2
485.0           1
500.0          16
513.0           1
550.0           1
572.0           1
580.0           1
600.0          15
             ...
274766.0        1
280000.0        8
285000.0        1
300000.0       27
310000.0        3
320000.0        3
330000.0        1
335000.0        1
340000.0        2
350000.0        4
355000.0        1
360000.0        1
390000.0        1
400000.0       10
409068.0        8
415929.0        1
420000.0        1
427000.0        1
430000.0        1
433605.0        1
500000.0        7
501600.0        1
520000.0        1
550000.0        1
700000.0        1
780000.0        1
800000.0        1
910000.0        1
1000000.0       2
1099999.0       6
Name: INCWAGE, Length: 1121, dtype: int64

In [30]:
d2.loc[d2['INCWAGE'].isin([0, 9999999.0 ]), 'INCWAGE']= np.nan

In [31]:
d21 = d2.loc[d2['INCWAGE'].notnull()]

In [32]:
d21

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
3646,3646,306599,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
3648,3648,306601,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,900.00,NaN,NaN,6260.0,17.5,36.4
3650,3650,306603,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0
3652,3652,306605,2010,16896,3,NaN,20091201589500,1.0,NaN,2700.93,...,21.0,8982.0,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1
3653,3653,306606,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,10.0,0.0,NaN,17.60,804.00,NaN,NaN,NaN,NaN,NaN
3654,3654,306607,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,0.0,0.0,NaN,11.00,440.00,NaN,NaN,4510.0,35.0,36.1
3659,3659,306612,2010,16900,3,NaN,20091201589700,1.0,NaN,1485.64,...,0.0,0.0,NaN,17.65,610.00,NaN,NaN,5240.0,35.5,40.4
3660,3660,306613,2010,16901,3,NaN,20091205019000,1.0,NaN,2933.76,...,21.0,4696.0,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4
3663,3663,306616,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,22.0,4051.0,NaN,99.99,9999.99,NaN,NaN,910.0,50.3,48.4
3664,3664,306617,2010,16903,3,NaN,20100104127000,1.0,NaN,2822.73,...,21.0,3020.0,NaN,99.99,9999.99,NaN,NaN,7700.0,45.3,47.0
3669,3669,306622,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,22.0,6114.0,NaN,99.99,9999.99,NaN,NaN,7840.0,28.4,29.6
3672,3672,306625,2010,16908,3,NaN,20100101534200,1.0,NaN,1321.94,...,0.0,6102.0,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1
3674,3674,306627,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1
3675,3675,306628,2010,16910,3,NaN,20100205511500,1.0,NaN,2690.84,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
3676,3676,306629,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,4138.0,NaN,99.99,9999.99,NaN,NaN,3740.0,43.8,54.1
3677,3677,306630,2010,16911,3,NaN,20100205511600,1.0,NaN,3164.93,...,21.0,3240.0,NaN,99.99,9999.99,NaN,NaN,NaN,NaN,NaN
3678,3678,306631,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,21.0,4640.0,NaN,99.99,9999.99,NaN,NaN,2010.0,52.4,51.5
3679,3679,306632,2010,16913,3,NaN,20100205550300,1.0,NaN,2896.49,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7
3681,3681,306634,2010,16916,3,NaN,20100305524100,1.0,NaN,3162.61,...,21.0,5342.0,NaN,99.99,9999.99,NaN,NaN,4210.0,45.3,36.1
3684,3684,306637,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5
3685,3685,306638,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7750.0,28.4,34.0
3687,3687,306640,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,300.00,NaN,NaN,3500.0,41.9,60.0
3690,3690,306643,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,7800.0,34.2,34.9
3691,3691,306644,2010,16921,3,NaN,20090101460700,1.0,NaN,2822.73,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
3693,3693,306646,2010,16922,3,NaN,20090102799100,1.0,NaN,2734.63,...,21.0,4610.0,NaN,99.99,9999.99,NaN,NaN,3620.0,47.8,61.5
3694,3694,306647,2010,16923,3,NaN,20090101460800,1.0,NaN,2829.80,...,21.0,4092.0,NaN,99.99,9999.99,NaN,NaN,4510.0,35.0,36.1
3696,3696,306649,2010,16924,3,NaN,20090103898900,1.0,NaN,2826.59,...,21.0,5661.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
3697,3697,306650,2010,16924,3,NaN,20090103898900,1.0,NaN,2826.59,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,220.0,50.3,56.5
3699,3699,306652,2010,16927,3,NaN,20090103899000,1.0,NaN,1490.52,...,21.0,5472.0,NaN,99.99,9999.99,NaN,NaN,7210.0,36.7,43.6
3700,3700,306653,2010,16927,3,NaN,20090103899000,1.0,NaN,1490.52,...,21.0,5787.0,NaN,99.99,9999.99,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177607,177607,12937511,2017,15684,3,NaN,20160305717600,1.0,NaN,1998.66,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4620.0,48.6,38.1
177608,177608,12937512,2017,15684,3,NaN,20160305717600,1.0,NaN,1998.66,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,7300.0,32.8,35.7
177611,177611,12937515,2017,15685,3,NaN,20160305669900,1.0,NaN,3765.30,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,8140.0,40.1,41.9
177612,177612,12937516,2017,15685,3,NaN,20160305669900,1.0,NaN,3765.30,...,21.0,6629.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177613,177613,12937517,2017,15686,3,NaN,20160305692000,1.0,NaN,3755.61,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6355.0,49.2,51.0
177618,177618,12937522,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,16.00,500.00,NaN,NaN,3950.0,14.7,37.2
177625,177625,12937529,2017,15695,3,NaN,20170305706700,1.0,NaN,3981.57,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,5550.0,42.3,47.0
177633,177633,12937537,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,21.0,5832.0,NaN,99.99,9999.99,NaN,NaN,7900.0,47.0,48.3
177634,177634,12937538,2017,15701,3,NaN,20170305724500,1.0,NaN,3756.46,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5620.0,35.5,27.4
177635,177635,12937539,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,21.0,3880.0,NaN,10.00,600.00,NaN,NaN,9620.0,17.5,24.0
177636,177636,12937540,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,0.0,0.0,NaN,13.75,550.00,NaN,NaN,4000.0,26.4,30.7
177637,177637,12937541,2017,15707,3,NaN,0,1.0,NaN,1685.76,...,21.0,9047.0,NaN,99.99,9999.99,NaN,NaN,7855.0,28.4,31.7
177642,177642,12937546,2017,15708,3,NaN,0,1.0,NaN,2368.52,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,6050.0,18.4,24.5
177647,177647,12937551,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,21.0,9096.0,NaN,99.99,9999.99,NaN,NaN,2320.0,59.6,66.4
177648,177648,12937552,2017,15710,3,NaN,0,1.0,NaN,2109.00,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,10.0,50.3,70.5
177651,177651,12937555,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4840.0,32.8,36.6
177652,177652,12937556,2017,15711,3,NaN,0,1.0,NaN,1925.11,...,21.0,9052.0,NaN,99.99,9999.99,NaN,NaN,2310.0,59.6,64.1
177660,177660,12937564,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,1220.0,50.6,53.0
177661,177661,12937565,2017,15714,3,NaN,0,1.0,NaN,2015.71,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,5240.0,35.5,40.4
177664,177664,12937568,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,0.0,0.0,NaN,0.00,9999.99,NaN,NaN,3320.0,61.0,58.5
177665,177665,12937569,2017,15715,3,NaN,0,1.0,NaN,2054.02,...,21.0,9997.0,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
177668,177668,12937572,2017,15716,3,NaN,0,1.0,NaN,2438.32,...,21.0,9997.0,NaN,0.00,9999.99,NaN,NaN,1410.0,69.4,64.2
177671,177671,12937575,2017,15717,3,NaN,0,1.0,NaN,2046.93,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,3160.0,36.7,61.5
177678,177678,12937582,2017,15719,3,NaN,0,1.0,NaN,2369.66,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4700.0,50.3,44.2
177681,177681,12937585,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,21.0,6883.0,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
177682,177682,12937586,2017,15720,3,NaN,0,1.0,NaN,1897.19,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
177685,177685,12937589,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,21.0,6047.0,NaN,99.99,9999.99,NaN,NaN,430.0,50.3,56.5
177686,177686,12937590,2017,15721,3,NaN,0,1.0,NaN,2110.95,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177690,177690,12937594,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,0.0,0.0,NaN,99.99,9999.99,NaN,NaN,2630.0,58.2,46.5
177691,177691,12937595,2017,15722,3,NaN,0,1.0,NaN,1906.75,...,10.0,0.0,NaN,99.99,9999.99,NaN,NaN,5000.0,50.3,50.7

In [33]:
d21[d21.INCWAGE.isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, YEAR, SERIAL, MONTH, HWTFINL, CPSID, ASECFLAG, HFLAG, ASECWTH, STATEFIP, COUNTY, PERNUM, WTFINL, CPSIDP, ASECWT, AGE, SEX, RACE, MARST, EMPSTAT, OCC, OCC2010_x, IND, CLASSWKR, UHRSWORKT, EDUC, EDUC99, EDDIPGED, OCCLY, INDLY, OCC90LY, IND90LY, OCC10LY, CLASSWLY, WORKLY, WKSWORK1, UHRSWORKLY, WKSUNEM1, WKXPNS, INCTOT, INCWAGE, PAIDGH, EMCONTRB, JTOCC, HOURWAGE, EARNWEEK, UHRSWORKORG, WKSWORKORG, OCC2010_y, PRESGL, PRENT]
Index: []

[0 rows x 52 columns]

In [34]:
d2 = d21

In [35]:
d2.UHRSWORKT.value_counts().sort_index()

0        7
1        1
2        5
3        5
4       12
5       13
6       14
7        4
8       33
9        6
10      54
11       2
12      33
13       6
14      10
15      79
16      46
17       4
18      21
19       3
20     246
21      12
22       8
23      11
24      63
25     105
26      13
27       7
28      31
29       3
      ...
54      10
55     134
56      21
57       6
58       9
59       2
60     243
62       8
63       5
64       8
65      36
66       5
68       3
70      56
72       6
73       2
75       7
76       4
78       3
79       1
80      26
82       1
84       3
85       3
90       1
99       4
100      2
109      1
997    427
999    820
Name: UHRSWORKT, Length: 84, dtype: int64

In [36]:
d2.loc[d2.UHRSWORKT.isin([0,997,999]), 'UHRSWORKT'] = np.nan
d21 = d2.loc[d2['UHRSWORKT'].notnull()]

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [37]:
d21.loc[:, ['UHRSWORKT', 'INCWAGE']]

        UHRSWORKT   INCWAGE
3648         60.0   30000.0
3650         40.0   20800.0
3652         52.0   90000.0
3653         40.0   11000.0
3654         40.0   23000.0
3659         40.0   31700.0
3660         46.0   56000.0
3663         45.0   30000.0
3664         40.0   45000.0
3669         40.0   41000.0
3672         40.0   33000.0
3674         30.0   10103.0
3675         45.0   45831.0
3676         58.0   70000.0
3677         39.0   60000.0
3678         40.0   35000.0
3679         40.0   32000.0
3681         60.0   40000.0
3684         45.0   14000.0
3687         20.0   18000.0
3690         20.0    9890.0
3693         37.0   18000.0
3694         24.0    5000.0
3696         40.0   38600.0
3697         40.0   30000.0
3699         45.0   50000.0
3700         32.0   40000.0
3703         16.0    7200.0
3707         40.0   30000.0
3708         40.0   25000.0
...           ...       ...
177606       70.0  110000.0
177607       40.0   60000.0
177608       40.0   75000.0
177611       46.0   37000.0
177612       40.0   28000.0
177613       40.0   45000.0
177618       10.0    6000.0
177625       50.0   50000.0
177633       65.0   67000.0
177634       40.0   13000.0
177635       40.0   29073.0
177636       45.0   32800.0
177637       40.0   45000.0
177642       35.0   38000.0
177647       40.0   80000.0
177648       50.0  150000.0
177651       20.0   35000.0
177652       60.0   75000.0
177660       40.0   88000.0
177661       30.0   27000.0
177664       24.0   66000.0
177665       40.0  150000.0
177668       60.0  115000.0
177678       60.0   50000.0
177681       40.0   28000.0
177682       10.0    5000.0
177685       40.0   50000.0
177686       25.0    3000.0
177690       50.0   57816.0
177691       42.0   37372.0

[7532 rows x 2 columns]

In [38]:
len(d21)

7532

In [39]:
# d21
d2[d2.INCWAGE.isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, YEAR, SERIAL, MONTH, HWTFINL, CPSID, ASECFLAG, HFLAG, ASECWTH, STATEFIP, COUNTY, PERNUM, WTFINL, CPSIDP, ASECWT, AGE, SEX, RACE, MARST, EMPSTAT, OCC, OCC2010_x, IND, CLASSWKR, UHRSWORKT, EDUC, EDUC99, EDDIPGED, OCCLY, INDLY, OCC90LY, IND90LY, OCC10LY, CLASSWLY, WORKLY, WKSWORK1, UHRSWORKLY, WKSUNEM1, WKXPNS, INCTOT, INCWAGE, PAIDGH, EMCONTRB, JTOCC, HOURWAGE, EARNWEEK, UHRSWORKORG, WKSWORKORG, OCC2010_y, PRESGL, PRENT]
Index: []

[0 rows x 52 columns]

In [40]:
d2['WKSWORK1'].value_counts().sort_index()

1.0       14
2.0       18
3.0       11
4.0       37
5.0        5
6.0       35
7.0       12
8.0       66
9.0       10
10.0      46
11.0       3
12.0     115
13.0      18
14.0      14
15.0      25
16.0      67
17.0      15
18.0      12
19.0       2
20.0      84
21.0       1
22.0      11
23.0       1
24.0      60
25.0      27
26.0     133
27.0       4
28.0      36
29.0       4
30.0      71
31.0       4
32.0      48
33.0       5
34.0      13
35.0      41
36.0      72
37.0       6
38.0      15
39.0      31
40.0     215
41.0       5
42.0      41
43.0      15
44.0      75
45.0      38
46.0      41
47.0      11
48.0     107
49.0      26
50.0     158
51.0      49
52.0    6813
Name: WKSWORK1, dtype: int64

In [41]:
d21 = d2[d2['WKSWORK1'].notnull()]

In [42]:
d21.loc[:, ['WKSWORK1', 'INCWAGE']]

        WKSWORK1   INCWAGE
3646        52.0   19000.0
3648        40.0   30000.0
3650        32.0   20800.0
3652        52.0   90000.0
3653        52.0   11000.0
3654        52.0   23000.0
3659        52.0   31700.0
3660        52.0   56000.0
3663        52.0   30000.0
3664        52.0   45000.0
3669        52.0   41000.0
3672        52.0   33000.0
3674        50.0   10103.0
3675        52.0   45831.0
3676        52.0   70000.0
3677        52.0   60000.0
3678        52.0   35000.0
3679        52.0   32000.0
3681        52.0   40000.0
3684        52.0   14000.0
3685        35.0   10000.0
3687        52.0   18000.0
3690        43.0    9890.0
3691        52.0   30000.0
3693        52.0   18000.0
3694        40.0    5000.0
3696        52.0   38600.0
3697        52.0   30000.0
3699        33.0   50000.0
3700        52.0   40000.0
...          ...       ...
177607      52.0   60000.0
177608      52.0   75000.0
177611      48.0   37000.0
177612      52.0   28000.0
177613      52.0   45000.0
177618      16.0    6000.0
177625      52.0   50000.0
177633      52.0   67000.0
177634      51.0   13000.0
177635      52.0   29073.0
177636      52.0   32800.0
177637      52.0   45000.0
177642      52.0   38000.0
177647      41.0   80000.0
177648      52.0  150000.0
177651      50.0   35000.0
177652      42.0   75000.0
177660      52.0   88000.0
177661      52.0   27000.0
177664      52.0   66000.0
177665      52.0  150000.0
177668      52.0  115000.0
177671      44.0    5000.0
177678      52.0   50000.0
177681      52.0   28000.0
177682      52.0    5000.0
177685      52.0   50000.0
177686      15.0    3000.0
177690      52.0   57816.0
177691      52.0   37372.0

[8786 rows x 2 columns]

In [43]:
len(d21)

8786

In [44]:
# d23
d2.UHRSWORKLY.value_counts().sort_index()

1.0       2
2.0       6
3.0       9
4.0      20
5.0      15
6.0      31
7.0       8
8.0      41
9.0       6
10.0     84
11.0      1
12.0     48
13.0      8
14.0     12
15.0    115
16.0     49
17.0      8
18.0     27
19.0      4
20.0    368
21.0     12
22.0     10
23.0     15
24.0     83
25.0    172
26.0      5
27.0     11
28.0     25
30.0    278
31.0      5
       ...
47.0      8
48.0     76
49.0      7
50.0    602
52.0     72
53.0      5
54.0      6
55.0    143
56.0     15
57.0      1
58.0      8
60.0    290
62.0      3
63.0      5
64.0      4
65.0     41
66.0      1
67.0      1
68.0      4
70.0     61
72.0      6
73.0      1
74.0      1
75.0     13
76.0      2
80.0     26
84.0      3
88.0      2
90.0      2
99.0      7
Name: UHRSWORKLY, Length: 75, dtype: int64

In [45]:
d23 = d2.loc[d2.UHRSWORKLY.notnull()]

In [46]:
d23.loc[:, ['UHRSWORKLY', 'INCWAGE']]

        UHRSWORKLY   INCWAGE
3646          20.0   19000.0
3648          40.0   30000.0
3650          40.0   20800.0
3652          50.0   90000.0
3653          40.0   11000.0
3654          40.0   23000.0
3659          40.0   31700.0
3660          46.0   56000.0
3663          45.0   30000.0
3664          40.0   45000.0
3669          40.0   41000.0
3672          40.0   33000.0
3674          10.0   10103.0
3675          40.0   45831.0
3676          42.0   70000.0
3677          38.0   60000.0
3678          40.0   35000.0
3679          40.0   32000.0
3681          60.0   40000.0
3684          45.0   14000.0
3685          50.0   10000.0
3687          20.0   18000.0
3690          20.0    9890.0
3691          40.0   30000.0
3693          37.0   18000.0
3694          11.0    5000.0
3696          40.0   38600.0
3697          40.0   30000.0
3699          40.0   50000.0
3700          32.0   40000.0
...            ...       ...
177607        40.0   60000.0
177608        40.0   75000.0
177611        46.0   37000.0
177612        40.0   28000.0
177613        40.0   45000.0
177618         6.0    6000.0
177625        45.0   50000.0
177633        55.0   67000.0
177634        28.0   13000.0
177635        40.0   29073.0
177636        40.0   32800.0
177637        45.0   45000.0
177642        35.0   38000.0
177647        40.0   80000.0
177648        40.0  150000.0
177651        20.0   35000.0
177652        40.0   75000.0
177660        40.0   88000.0
177661        30.0   27000.0
177664        24.0   66000.0
177665        40.0  150000.0
177668        60.0  115000.0
177671         6.0    5000.0
177678        60.0   50000.0
177681        40.0   28000.0
177682        10.0    5000.0
177685        40.0   50000.0
177686        25.0    3000.0
177690        50.0   57816.0
177691        40.0   37372.0

[8786 rows x 2 columns]

In [47]:
len(d23)

8786

In [48]:
# d24
d2['WKSUNEM1'].value_counts().sort_index()

0.0     1121
1.0       26
2.0       32
3.0       10
4.0       52
5.0       11
6.0       26
7.0       17
8.0       51
9.0        9
10.0      21
11.0       3
12.0     115
13.0      16
14.0       7
15.0       3
16.0      35
17.0      17
18.0       7
19.0       4
20.0      34
22.0      27
23.0       1
24.0      15
25.0       2
26.0      59
27.0      11
28.0      28
30.0      10
32.0      34
34.0       5
35.0       6
36.0      28
37.0       6
38.0       8
39.0       8
40.0      27
41.0       1
42.0      11
43.0       3
44.0      22
45.0       3
46.0      13
47.0       2
48.0      11
49.0       3
50.0       7
51.0       5
99.0    6813
Name: WKSUNEM1, dtype: int64

In [49]:
d2.loc[d2['WKSUNEM1'].isin([0,99]), 'WKSUNEM1']= np.nan
d24 = d2.loc[d2['WKSUNEM1'].notnull()]

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [50]:
d24.loc[:, ['WKSUNEM1', 'INCWAGE']]

        WKSUNEM1  INCWAGE
3685        17.0  10000.0
3699        19.0  50000.0
3728         4.0  15000.0
3771        32.0   8000.0
3776        12.0  34000.0
3870        28.0  28000.0
3911        12.0  29000.0
3928         4.0   5300.0
3935        40.0   7000.0
3939        28.0  50000.0
3945         1.0  12000.0
3956        18.0  11002.0
3973        46.0  18000.0
3990        12.0   9000.0
4009        44.0   1600.0
4010        20.0   4228.0
4062        12.0  54000.0
4155         1.0  10000.0
4210         1.0   1430.0
4223        12.0  15800.0
4253        36.0   3202.0
4333        12.0  10000.0
4360         4.0  25000.0
4375        12.0  55000.0
4380         7.0  80000.0
4389        44.0    500.0
4395         1.0   2000.0
4477        10.0  45000.0
4481        26.0   2530.0
4553        44.0   2600.0
...          ...      ...
176819       4.0  28000.0
176853      12.0  20000.0
176875       6.0  55000.0
176895      32.0  10000.0
176913      36.0  36000.0
176991       4.0  33150.0
176992      13.0  11100.0
177019      28.0   6000.0
177033      12.0   9000.0
177047       6.0  11000.0
177072       3.0   3040.0
177120      16.0   1200.0
177163       8.0   4000.0
177165      26.0   7000.0
177171       2.0  22000.0
177214      24.0   4500.0
177215      24.0   2618.0
177218       4.0  60000.0
177319      12.0  10000.0
177355      26.0  20000.0
177447      48.0   1500.0
177453       2.0  12800.0
177466       4.0  41000.0
177491       4.0  19000.0
177496      13.0  28000.0
177516      26.0    970.0
177520       4.0  60000.0
177527      32.0   7000.0
177536      42.0  12000.0
177597      20.0    600.0

[852 rows x 2 columns]

In [51]:
len(d24)

852

In [52]:
# d31
d3 = df
d3.HOURWAGE.value_counts().sort_index()

0.00        381
1.00          3
1.48          2
1.89          3
2.00          6
2.12          1
2.13          4
2.15          1
2.17          1
2.22          1
2.25          1
2.30          1
2.33          1
2.37          2
2.39          1
2.50          4
2.60          1
2.65          1
2.70          1
2.75          6
2.80          4
2.83         31
2.85          2
3.00         15
3.25          1
3.27          2
3.33          4
3.38          1
3.47          1
3.50          3
          ...
56.67         2
56.89         2
57.00         6
57.69         5
58.00         4
58.25         2
58.45         1
59.01         2
60.00        14
60.40         1
60.41         1
61.00         1
62.40         1
63.00         1
64.00         1
65.00         2
65.40         1
67.00         2
68.20         1
68.68         1
70.00         3
70.73         1
72.12         9
74.00         3
75.00         2
82.42         1
87.50         2
90.00         4
99.00         1
99.99    100728
Name: HOURWAGE, Length: 1341, dtype: int64

In [53]:
d3.loc[d3['HOURWAGE'].isin([0, 99.99, 99.97]), 'HOURWAGE']=np.nan

In [54]:
d3 = d3[d3['HOURWAGE'].notnull()]

In [55]:
d3[d3['HOURWAGE'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, YEAR, SERIAL, MONTH, HWTFINL, CPSID, ASECFLAG, HFLAG, ASECWTH, STATEFIP, COUNTY, PERNUM, WTFINL, CPSIDP, ASECWT, AGE, SEX, RACE, MARST, EMPSTAT, OCC, OCC2010_x, IND, CLASSWKR, UHRSWORKT, EDUC, EDUC99, EDDIPGED, OCCLY, INDLY, OCC90LY, IND90LY, OCC10LY, CLASSWLY, WORKLY, WKSWORK1, UHRSWORKLY, WKSUNEM1, WKXPNS, INCTOT, INCWAGE, PAIDGH, EMCONTRB, JTOCC, HOURWAGE, EARNWEEK, UHRSWORKORG, WKSWORKORG, OCC2010_y, PRESGL, PRENT]
Index: []

[0 rows x 52 columns]

In [56]:
d3.UHRSWORKT.value_counts().sort_index()

0        9
1        3
2        8
3        8
4       21
5       19
6       24
7        9
8       57
9        9
10      97
11       1
12      73
13      10
14      15
15     121
16      99
17       8
18      41
19       2
20     467
21      15
22      20
23      17
24     142
25     246
26      18
27      24
28      56
29      15
      ...
53       9
54       7
55      93
56      43
57       5
58      11
59       3
60     123
61       1
62       5
63       2
64       6
65      25
66       3
68       1
69       1
70      18
72       7
73       2
75       4
76       1
77       2
78       2
79       1
80       9
84       1
90       3
96       1
100      2
997    658
Name: UHRSWORKT, Length: 83, dtype: int64

In [57]:
d3.loc[d3['UHRSWORKT'].isin([0,997,999]), 'UHRSWORKT']= np.nan

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [58]:
d31 = d3[d3['UHRSWORKT'].notnull()]

In [59]:
d31.loc[:, ['UHRSWORKT', 'HOURWAGE']]

        UHRSWORKT  HOURWAGE
6            40.0     20.70
76           50.0      9.30
84           25.0     30.00
100          40.0      7.25
102          40.0     14.00
103          40.0     25.00
117          40.0     16.85
119          36.0      7.25
138          35.0      7.25
142          41.0     33.11
192          40.0     22.00
201          40.0     19.00
248          42.0     38.00
249          38.0     13.50
250          40.0     32.00
271          40.0      9.50
273          32.0     12.00
285          12.0     35.00
318          40.0     12.00
321          20.0     37.50
322          40.0     38.50
344          51.0     39.00
349          40.0     16.74
433          45.0     20.00
436          20.0      7.25
469          40.0     12.60
470          40.0      8.96
487          25.0      5.00
488          40.0     12.00
531          40.0     18.80
...           ...       ...
199530       40.0     14.83
199531       38.0     13.00
199534       40.0     26.00
199559       32.0     18.62
199575       44.0     20.59
199607       36.0     10.00
199648       40.0     12.98
199649       56.0     11.00
199683       40.0     23.00
199686       40.0     15.30
199721       40.0     10.50
199725       40.0     11.50
199726       60.0     21.00
199745       40.0     12.98
199746       40.0     12.50
199748       40.0     20.00
199753       40.0     12.95
199763       30.0      3.63
199793       18.0     30.00
199810       18.0     17.00
199961       40.0      1.00
199985       40.0     25.44
200002       40.0     15.70
200003       40.0     15.50
200028       40.0     24.01
200029       40.0      8.75
200049       30.0      3.47
200051       40.0     20.00
200052       25.0     13.00
200055       42.0     25.25

[9881 rows x 2 columns]

In [60]:
len(d31)

9881

In [61]:
d31

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
6,6,4366,2010,2613,1,3683.7540,20091200281200,NaN,NaN,NaN,...,NaN,NaN,0.0,20.70,769.23,999.0,52.0,NaN,NaN,NaN
76,76,4505,2010,2701,1,2635.4699,20091000264100,NaN,NaN,NaN,...,NaN,NaN,0.0,9.30,465.00,50.0,0.0,3600.0,36.3,41.7
84,84,4513,2010,2704,1,3786.7243,20081005433500,NaN,NaN,NaN,...,NaN,NaN,0.0,30.00,800.00,999.0,50.0,4520.0,35.0,36.1
100,100,4529,2010,2708,1,2745.0915,20091002928100,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,290.00,40.0,0.0,5850.0,35.5,31.9
102,102,4531,2010,2710,1,2544.1069,20091006186600,NaN,NaN,NaN,...,NaN,NaN,3800.0,14.00,560.00,40.0,0.0,2000.0,50.6,56.7
103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,NaN,...,NaN,NaN,0.0,25.00,1000.00,40.0,0.0,9100.0,32.4,32.1
117,117,4558,2010,2731,1,3561.0132,20091004063000,NaN,NaN,NaN,...,NaN,NaN,0.0,16.85,700.00,999.0,0.0,NaN,NaN,NaN
119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,234.50,999.0,0.0,4060.0,15.3,21.1
138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,253.75,35.0,0.0,4060.0,15.3,21.1
142,142,4638,2010,2780,1,2770.8363,20091100293600,NaN,NaN,NaN,...,NaN,NaN,0.0,33.11,1326.92,999.0,52.0,NaN,NaN,NaN
192,192,4763,2010,2860,1,3075.0249,20081005553300,NaN,NaN,NaN,...,NaN,NaN,8540.0,22.00,880.00,40.0,0.0,NaN,NaN,NaN
201,201,4772,2010,2867,1,2388.6063,20091005633400,NaN,NaN,NaN,...,NaN,NaN,0.0,19.00,760.00,40.0,0.0,NaN,NaN,NaN
248,248,11999,2010,6258,1,3813.9774,20081005464300,NaN,NaN,NaN,...,NaN,NaN,2000.0,38.00,800.00,999.0,0.0,8630.0,26.3,42.9
249,249,12000,2010,6258,1,3813.9774,20081005464300,NaN,NaN,NaN,...,NaN,NaN,2000.0,13.50,600.00,999.0,0.0,2000.0,50.6,56.7
250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,NaN,...,NaN,NaN,0.0,32.00,1280.00,40.0,0.0,6200.0,50.3,53.2
271,271,12031,2010,6271,1,2861.4301,20091001515500,NaN,NaN,NaN,...,NaN,NaN,0.0,9.50,380.00,40.0,0.0,2010.0,52.4,51.5
273,273,12033,2010,6272,1,2605.6782,20091001515700,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,361.11,999.0,36.0,2540.0,50.6,45.7
285,285,12067,2010,6288,1,4051.7611,20081005550100,NaN,NaN,NaN,...,NaN,NaN,0.0,35.00,576.92,999.0,52.0,NaN,NaN,NaN
318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,480.00,40.0,0.0,4220.0,16.1,22.3
321,321,12122,2010,6314,1,2880.4128,20081005357400,NaN,NaN,NaN,...,NaN,NaN,0.0,37.50,750.00,20.0,0.0,2340.0,46.0,45.7
322,322,12123,2010,6314,1,2880.4128,20081005357400,NaN,NaN,NaN,...,NaN,NaN,0.0,38.50,730.76,999.0,52.0,2440.0,41.3,29.3
344,344,12169,2010,6333,1,3819.5067,20091005633300,NaN,NaN,NaN,...,NaN,NaN,0.0,39.00,1462.50,999.0,0.0,3150.0,36.7,56.0
349,349,12174,2010,6335,1,3604.7769,20091004935500,NaN,NaN,NaN,...,NaN,NaN,0.0,16.74,350.00,999.0,0.0,NaN,NaN,NaN
433,433,28940,2010,15235,1,2734.2554,20091005624000,NaN,NaN,NaN,...,NaN,NaN,0.0,20.00,950.00,40.0,0.0,8910.0,41.2,38.2
436,436,28943,2010,15236,1,2721.6624,20091006184300,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,145.00,20.0,0.0,4720.0,30.9,29.5
469,469,29027,2010,15296,1,2807.5127,20081005550700,NaN,NaN,NaN,...,NaN,NaN,0.0,12.60,550.00,999.0,0.0,5620.0,35.5,27.4
470,470,29028,2010,15296,1,2807.5127,20081005550700,NaN,NaN,NaN,...,NaN,NaN,0.0,8.96,358.40,40.0,0.0,5240.0,35.5,40.4
487,487,29045,2010,15303,1,4079.5181,20091002927800,NaN,NaN,NaN,...,NaN,NaN,0.0,5.00,725.00,25.0,0.0,4040.0,19.9,24.5
488,488,29046,2010,15303,1,4079.5181,20091002927800,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,480.00,40.0,0.0,NaN,NaN,NaN
531,531,29089,2010,15325,1,2906.0264,20091006532300,NaN,NaN,NaN,...,NaN,NaN,0.0,18.80,530.00,999.0,0.0,100.0,50.3,56.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199530,199530,14831415,2018,54598,5,3398.0577,20170205691500,NaN,NaN,NaN,...,NaN,NaN,NaN,14.83,593.20,40.0,0.0,9620.0,17.5,24.0
199531,199531,14831416,2018,54598,5,3398.0577,20170205691500,NaN,NaN,NaN,...,NaN,NaN,NaN,13.00,494.00,38.0,0.0,4220.0,16.1,22.3
199534,199534,14831419,2018,54600,5,3444.6243,20170205691900,NaN,NaN,NaN,...,NaN,NaN,NaN,26.00,1040.00,40.0,0.0,6230.0,39.9,38.9
199559,199559,14831473,2018,54629,5,4550.2334,20180205516200,NaN,NaN,NaN,...,NaN,NaN,NaN,18.62,595.84,32.0,0.0,2340.0,46.0,45.7
199575,199575,14831499,2018,54645,5,4987.8438,20170205697400,NaN,NaN,NaN,...,NaN,NaN,NaN,20.59,823.60,40.0,0.0,8100.0,28.4,33.7
199607,199607,14831550,2018,54676,5,4503.2797,20170205700800,NaN,NaN,NaN,...,NaN,NaN,NaN,10.00,360.00,36.0,0.0,310.0,50.3,41.0
199648,199648,14831609,2018,54704,5,4972.5775,20170205703700,NaN,NaN,NaN,...,NaN,NaN,NaN,12.98,519.20,40.0,0.0,2010.0,52.4,51.5
199649,199649,14831610,2018,54704,5,4972.5775,20170205703700,NaN,NaN,NaN,...,NaN,NaN,NaN,11.00,616.00,56.0,0.0,8965.0,28.4,31.7
199683,199683,14831669,2018,54738,5,3329.9105,20170205707700,NaN,NaN,NaN,...,NaN,NaN,NaN,23.00,1038.46,999.0,52.0,7750.0,28.4,34.0
199686,199686,14831678,2018,54745,5,3398.0577,20170205708600,NaN,NaN,NaN,...,NaN,NaN,NaN,15.30,612.00,40.0,0.0,5520.0,33.5,34.8
199721,199721,14831726,2018,54763,5,4501.2560,20170205709600,NaN,NaN,NaN,...,NaN,NaN,NaN,10.50,420.00,40.0,0.0,4140.0,17.6,16.8
199725,199725,14831732,2018,54771,5,4815.9518,20180205529300,NaN,NaN,NaN,...,NaN,NaN,NaN,11.50,460.00,40.0,0.0,5620.0,35.5,27.4
199726,199726,14831733,2018,54771,5,4815.9518,20180205529300,NaN,NaN,NaN,...,NaN,NaN,NaN,21.00,945.00,40.0,0.0,5610.0,29.2,34.9
199745,199745,14831758,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,12.98,519.20,40.0,0.0,2630.0,58.2,46.5
199746,199746,14831759,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,12.50,500.00,40.0,0.0,8740.0,28.4,32.8
199748,199748,14831761,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,20.00,800.00,40.0,0.0,1610.0,67.7,73.1
199753,199753,14831766,2018,54788,5,3398.0577,20170205712200,NaN,NaN,NaN,...,NaN,NaN,NaN,12.95,923.00,999.0,0.0,5700.0,44.5,46.1
199763,199763,14831786,2018,54796,5,3487.2109,20180205533100,NaN,NaN,NaN,...,NaN,NaN,NaN,3.63,350.00,999.0,0.0,4110.0,20.3,28.1
199793,199793,14831832,2018,54828,5,3268.4282,20170205716400,NaN,NaN,NaN,...,NaN,NaN,NaN,30.00,540.00,18.0,0.0,2440.0,41.3,29.3
199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,NaN,...,NaN,NaN,NaN,17.00,306.00,18.0,0.0,2310.0,59.6,64.1
199961,199961,14832109,2018,54987,5,5755.4387,20180205553000,NaN,NaN,NaN,...,NaN,NaN,NaN,1.00,40.00,40.0,0.0,5240.0,35.5,40.4
199985,199985,14832153,2018,55007,5,4548.1886,20180205554800,NaN,NaN,NaN,...,NaN,NaN,NaN,25.44,1250.00,999.0,52.0,1060.0,50.6,73.7
200002,200002,14832190,2018,55029,5,5399.0825,20180205556700,NaN,NaN,NaN,...,NaN,NaN,NaN,15.70,628.00,40.0,0.0,7750.0,28.4,34.0
200003,200003,14832191,2018,55029,5,5399.0825,20180205556700,NaN,NaN,NaN,...,NaN,NaN,NaN,15.50,620.00,40.0,0.0,7330.0,32.8,29.5
200028,200028,14832236,2018,55056,5,3398.0577,20170205738900,NaN,NaN,NaN,...,NaN,NaN,NaN,24.01,960.40,40.0,0.0,8640.0,28.4,29.7
200029,200029,14832237,2018,55056,5,3398.0577,20170205738900,NaN,NaN,NaN,...,NaN,NaN,NaN,8.75,350.00,40.0,0.0,6820.0,26.3,39.8
200049,200049,14832277,2018,55077,5,3399.8890,20180205560300,NaN,NaN,NaN,...,NaN,NaN,NaN,3.47,314.10,30.0,0.0,4110.0,20.3,28.1
200051,200051,14832289,2018,55083,5,4336.0718,20180205560800,NaN,NaN,NaN,...,NaN,NaN,NaN,20.00,500.00,999.0,0.0,9600.0,28.4,30.4
200052,200052,14832290,2018,55083,5,4336.0718,20180205560800,NaN,NaN,NaN,...,NaN,NaN,NaN,13.00,230.76,999.0,0.0,4220.0,16.1,22.3
200055,200055,14832293,2018,55085,5,3284.8946,20170205741300,NaN,NaN,NaN,...,NaN,NaN,NaN,25.25,2060.50,42.0,0.0,8965.0,28.4,31.7

In [62]:
len(d31.PRESGL.isnull())

9881

In [63]:
d31 = d31[d31.PRESGL.notnull()]

In [64]:
d31

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
76,76,4505,2010,2701,1,2635.4699,20091000264100,NaN,NaN,NaN,...,NaN,NaN,0.0,9.30,465.00,50.0,0.0,3600.0,36.3,41.7
84,84,4513,2010,2704,1,3786.7243,20081005433500,NaN,NaN,NaN,...,NaN,NaN,0.0,30.00,800.00,999.0,50.0,4520.0,35.0,36.1
100,100,4529,2010,2708,1,2745.0915,20091002928100,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,290.00,40.0,0.0,5850.0,35.5,31.9
102,102,4531,2010,2710,1,2544.1069,20091006186600,NaN,NaN,NaN,...,NaN,NaN,3800.0,14.00,560.00,40.0,0.0,2000.0,50.6,56.7
103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,NaN,...,NaN,NaN,0.0,25.00,1000.00,40.0,0.0,9100.0,32.4,32.1
119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,234.50,999.0,0.0,4060.0,15.3,21.1
138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,253.75,35.0,0.0,4060.0,15.3,21.1
248,248,11999,2010,6258,1,3813.9774,20081005464300,NaN,NaN,NaN,...,NaN,NaN,2000.0,38.00,800.00,999.0,0.0,8630.0,26.3,42.9
249,249,12000,2010,6258,1,3813.9774,20081005464300,NaN,NaN,NaN,...,NaN,NaN,2000.0,13.50,600.00,999.0,0.0,2000.0,50.6,56.7
250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,NaN,...,NaN,NaN,0.0,32.00,1280.00,40.0,0.0,6200.0,50.3,53.2
271,271,12031,2010,6271,1,2861.4301,20091001515500,NaN,NaN,NaN,...,NaN,NaN,0.0,9.50,380.00,40.0,0.0,2010.0,52.4,51.5
273,273,12033,2010,6272,1,2605.6782,20091001515700,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,361.11,999.0,36.0,2540.0,50.6,45.7
318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,480.00,40.0,0.0,4220.0,16.1,22.3
321,321,12122,2010,6314,1,2880.4128,20081005357400,NaN,NaN,NaN,...,NaN,NaN,0.0,37.50,750.00,20.0,0.0,2340.0,46.0,45.7
322,322,12123,2010,6314,1,2880.4128,20081005357400,NaN,NaN,NaN,...,NaN,NaN,0.0,38.50,730.76,999.0,52.0,2440.0,41.3,29.3
344,344,12169,2010,6333,1,3819.5067,20091005633300,NaN,NaN,NaN,...,NaN,NaN,0.0,39.00,1462.50,999.0,0.0,3150.0,36.7,56.0
433,433,28940,2010,15235,1,2734.2554,20091005624000,NaN,NaN,NaN,...,NaN,NaN,0.0,20.00,950.00,40.0,0.0,8910.0,41.2,38.2
436,436,28943,2010,15236,1,2721.6624,20091006184300,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,145.00,20.0,0.0,4720.0,30.9,29.5
469,469,29027,2010,15296,1,2807.5127,20081005550700,NaN,NaN,NaN,...,NaN,NaN,0.0,12.60,550.00,999.0,0.0,5620.0,35.5,27.4
470,470,29028,2010,15296,1,2807.5127,20081005550700,NaN,NaN,NaN,...,NaN,NaN,0.0,8.96,358.40,40.0,0.0,5240.0,35.5,40.4
487,487,29045,2010,15303,1,4079.5181,20091002927800,NaN,NaN,NaN,...,NaN,NaN,0.0,5.00,725.00,25.0,0.0,4040.0,19.9,24.5
531,531,29089,2010,15325,1,2906.0264,20091006532300,NaN,NaN,NaN,...,NaN,NaN,0.0,18.80,530.00,999.0,0.0,100.0,50.3,56.5
532,532,29090,2010,15325,1,2906.0264,20091006532300,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,300.00,999.0,0.0,5160.0,49.5,43.3
550,550,29130,2010,15343,1,3916.7585,20081005528100,NaN,NaN,NaN,...,NaN,NaN,410.0,13.75,550.00,999.0,0.0,5240.0,35.5,40.4
553,553,29133,2010,15344,1,3979.2145,20081005535800,NaN,NaN,NaN,...,NaN,NaN,0.0,16.67,616.79,37.0,0.0,5610.0,29.2,34.9
554,554,29134,2010,15344,1,3979.2145,20081005535800,NaN,NaN,NaN,...,NaN,NaN,0.0,8.00,200.00,25.0,0.0,4010.0,50.3,30.7
577,577,29185,2010,15370,1,2659.9043,20081005556000,NaN,NaN,NaN,...,NaN,NaN,0.0,8.00,64.00,8.0,0.0,4150.0,26.4,25.4
637,637,29355,2010,15440,1,2281.2721,20081005382200,NaN,NaN,NaN,...,NaN,NaN,0.0,30.00,1200.00,40.0,0.0,6230.0,39.9,38.9
659,659,29377,2010,15451,1,2852.4104,20091004933100,NaN,NaN,NaN,...,NaN,NaN,0.0,18.00,720.00,40.0,0.0,3400.0,61.0,56.7
703,703,36322,2010,18803,1,2659.9043,20091000263900,NaN,NaN,NaN,...,NaN,NaN,0.0,22.00,264.00,12.0,0.0,940.0,50.3,48.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199530,199530,14831415,2018,54598,5,3398.0577,20170205691500,NaN,NaN,NaN,...,NaN,NaN,NaN,14.83,593.20,40.0,0.0,9620.0,17.5,24.0
199531,199531,14831416,2018,54598,5,3398.0577,20170205691500,NaN,NaN,NaN,...,NaN,NaN,NaN,13.00,494.00,38.0,0.0,4220.0,16.1,22.3
199534,199534,14831419,2018,54600,5,3444.6243,20170205691900,NaN,NaN,NaN,...,NaN,NaN,NaN,26.00,1040.00,40.0,0.0,6230.0,39.9,38.9
199559,199559,14831473,2018,54629,5,4550.2334,20180205516200,NaN,NaN,NaN,...,NaN,NaN,NaN,18.62,595.84,32.0,0.0,2340.0,46.0,45.7
199575,199575,14831499,2018,54645,5,4987.8438,20170205697400,NaN,NaN,NaN,...,NaN,NaN,NaN,20.59,823.60,40.0,0.0,8100.0,28.4,33.7
199607,199607,14831550,2018,54676,5,4503.2797,20170205700800,NaN,NaN,NaN,...,NaN,NaN,NaN,10.00,360.00,36.0,0.0,310.0,50.3,41.0
199648,199648,14831609,2018,54704,5,4972.5775,20170205703700,NaN,NaN,NaN,...,NaN,NaN,NaN,12.98,519.20,40.0,0.0,2010.0,52.4,51.5
199649,199649,14831610,2018,54704,5,4972.5775,20170205703700,NaN,NaN,NaN,...,NaN,NaN,NaN,11.00,616.00,56.0,0.0,8965.0,28.4,31.7
199683,199683,14831669,2018,54738,5,3329.9105,20170205707700,NaN,NaN,NaN,...,NaN,NaN,NaN,23.00,1038.46,999.0,52.0,7750.0,28.4,34.0
199686,199686,14831678,2018,54745,5,3398.0577,20170205708600,NaN,NaN,NaN,...,NaN,NaN,NaN,15.30,612.00,40.0,0.0,5520.0,33.5,34.8
199721,199721,14831726,2018,54763,5,4501.2560,20170205709600,NaN,NaN,NaN,...,NaN,NaN,NaN,10.50,420.00,40.0,0.0,4140.0,17.6,16.8
199725,199725,14831732,2018,54771,5,4815.9518,20180205529300,NaN,NaN,NaN,...,NaN,NaN,NaN,11.50,460.00,40.0,0.0,5620.0,35.5,27.4
199726,199726,14831733,2018,54771,5,4815.9518,20180205529300,NaN,NaN,NaN,...,NaN,NaN,NaN,21.00,945.00,40.0,0.0,5610.0,29.2,34.9
199745,199745,14831758,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,12.98,519.20,40.0,0.0,2630.0,58.2,46.5
199746,199746,14831759,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,12.50,500.00,40.0,0.0,8740.0,28.4,32.8
199748,199748,14831761,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,20.00,800.00,40.0,0.0,1610.0,67.7,73.1
199753,199753,14831766,2018,54788,5,3398.0577,20170205712200,NaN,NaN,NaN,...,NaN,NaN,NaN,12.95,923.00,999.0,0.0,5700.0,44.5,46.1
199763,199763,14831786,2018,54796,5,3487.2109,20180205533100,NaN,NaN,NaN,...,NaN,NaN,NaN,3.63,350.00,999.0,0.0,4110.0,20.3,28.1
199793,199793,14831832,2018,54828,5,3268.4282,20170205716400,NaN,NaN,NaN,...,NaN,NaN,NaN,30.00,540.00,18.0,0.0,2440.0,41.3,29.3
199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,NaN,...,NaN,NaN,NaN,17.00,306.00,18.0,0.0,2310.0,59.6,64.1
199961,199961,14832109,2018,54987,5,5755.4387,20180205553000,NaN,NaN,NaN,...,NaN,NaN,NaN,1.00,40.00,40.0,0.0,5240.0,35.5,40.4
199985,199985,14832153,2018,55007,5,4548.1886,20180205554800,NaN,NaN,NaN,...,NaN,NaN,NaN,25.44,1250.00,999.0,52.0,1060.0,50.6,73.7
200002,200002,14832190,2018,55029,5,5399.0825,20180205556700,NaN,NaN,NaN,...,NaN,NaN,NaN,15.70,628.00,40.0,0.0,7750.0,28.4,34.0
200003,200003,14832191,2018,55029,5,5399.0825,20180205556700,NaN,NaN,NaN,...,NaN,NaN,NaN,15.50,620.00,40.0,0.0,7330.0,32.8,29.5
200028,200028,14832236,2018,55056,5,3398.0577,20170205738900,NaN,NaN,NaN,...,NaN,NaN,NaN,24.01,960.40,40.0,0.0,8640.0,28.4,29.7
200029,200029,14832237,2018,55056,5,3398.0577,20170205738900,NaN,NaN,NaN,...,NaN,NaN,NaN,8.75,350.00,40.0,0.0,6820.0,26.3,39.8
200049,200049,14832277,2018,55077,5,3399.8890,20180205560300,NaN,NaN,NaN,...,NaN,NaN,NaN,3.47,314.10,30.0,0.0,4110.0,20.3,28.1
200051,200051,14832289,2018,55083,5,4336.0718,20180205560800,NaN,NaN,NaN,...,NaN,NaN,NaN,20.00,500.00,999.0,0.0,9600.0,28.4,30.4
200052,200052,14832290,2018,55083,5,4336.0718,20180205560800,NaN,NaN,NaN,...,NaN,NaN,NaN,13.00,230.76,999.0,0.0,4220.0,16.1,22.3
200055,200055,14832293,2018,55085,5,3284.8946,20170205741300,NaN,NaN,NaN,...,NaN,NaN,NaN,25.25,2060.50,42.0,0.0,8965.0,28.4,31.7

In [65]:
len(d31)

9684

In [66]:
d312 = d31[d31.PAIDGH.notnull()]

In [67]:
d312

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
3648,3648,306601,2010,16894,3,NaN,20091201589400,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,900.0,NaN,NaN,6260.0,17.5,36.4
3650,3650,306603,2010,16895,3,NaN,20091203081900,1.0,NaN,2909.74,...,0.0,0.0,NaN,10.00,400.0,NaN,NaN,9620.0,17.5,24.0
3654,3654,306607,2010,16898,3,NaN,20091203082100,1.0,NaN,1357.92,...,0.0,0.0,NaN,11.00,440.0,NaN,NaN,4510.0,35.0,36.1
3659,3659,306612,2010,16900,3,NaN,20091201589700,1.0,NaN,1485.64,...,0.0,0.0,NaN,17.65,610.0,NaN,NaN,5240.0,35.5,40.4
3684,3684,306637,2010,16918,3,NaN,20091201589900,1.0,NaN,2546.10,...,0.0,0.0,NaN,5.00,575.0,NaN,NaN,4040.0,19.9,24.5
3687,3687,306640,2010,16919,3,NaN,20081204016600,1.0,NaN,2700.93,...,0.0,0.0,NaN,15.00,300.0,NaN,NaN,3500.0,41.9,60.0
3771,3771,308227,2010,17607,3,NaN,20091201584100,1.0,NaN,2761.25,...,0.0,0.0,NaN,26.87,1075.0,NaN,NaN,6460.0,33.2,34.9
3772,3772,308228,2010,17607,3,NaN,20091201584100,1.0,NaN,2761.25,...,0.0,0.0,NaN,13.39,509.0,NaN,NaN,5700.0,44.5,46.1
3775,3775,308231,2010,17608,3,NaN,20091201584200,1.0,NaN,2710.49,...,21.0,1466.0,NaN,8.65,346.0,NaN,NaN,5620.0,35.5,27.4
3777,3777,308233,2010,17609,3,NaN,20091205016600,1.0,NaN,3071.90,...,0.0,0.0,NaN,10.00,370.0,NaN,NaN,9140.0,22.0,28.1
3785,3785,308241,2010,17613,3,NaN,20091206249000,1.0,NaN,2761.25,...,21.0,7073.0,NaN,13.00,520.0,NaN,NaN,3820.0,47.8,59.7
3868,3868,308324,2010,17655,3,NaN,20081206426500,1.0,NaN,2477.24,...,22.0,5417.0,NaN,15.00,480.0,NaN,NaN,5120.0,47.6,46.6
3870,3870,308326,2010,17656,3,NaN,20081205582000,1.0,NaN,1586.52,...,21.0,7631.0,NaN,14.00,560.0,NaN,NaN,5510.0,19.1,22.3
3871,3871,308327,2010,17656,3,NaN,20081205582000,1.0,NaN,1586.52,...,0.0,0.0,NaN,12.00,180.0,NaN,NaN,5700.0,44.5,46.1
3983,3983,308519,2010,17741,3,NaN,20100305552600,1.0,NaN,2710.49,...,0.0,0.0,NaN,9.00,288.0,NaN,NaN,6050.0,18.4,24.5
3984,3984,308520,2010,17741,3,NaN,20100305552600,1.0,NaN,2710.49,...,0.0,0.0,NaN,10.00,385.0,NaN,NaN,6050.0,18.4,24.5
3985,3985,308521,2010,17741,3,NaN,20100305552600,1.0,NaN,2710.49,...,0.0,0.0,NaN,10.00,385.0,NaN,NaN,4720.0,30.9,29.5
3986,3986,308522,2010,17741,3,NaN,20100305552600,1.0,NaN,2710.49,...,0.0,0.0,NaN,10.50,423.0,NaN,NaN,6050.0,18.4,24.5
3987,3987,308523,2010,17741,3,NaN,20100305552600,1.0,NaN,2710.49,...,0.0,0.0,NaN,10.50,423.0,NaN,NaN,6050.0,18.4,24.5
4052,4052,308588,2010,17778,3,NaN,20100205565600,1.0,NaN,933.61,...,21.0,7242.0,NaN,12.74,510.0,NaN,NaN,7750.0,28.4,34.0
4061,4061,308597,2010,17785,3,NaN,20081204019000,1.0,NaN,2555.65,...,22.0,9997.0,NaN,33.10,1442.0,NaN,NaN,3820.0,47.8,59.7
4255,4255,308791,2010,17865,3,NaN,20081204010600,1.0,NaN,1937.33,...,0.0,0.0,NaN,7.75,209.0,NaN,NaN,4140.0,17.6,16.8
4259,4259,308795,2010,17867,3,NaN,20091206247100,1.0,NaN,4042.30,...,0.0,0.0,NaN,8.00,200.0,NaN,NaN,4760.0,32.8,33.6
4261,4261,308797,2010,17868,3,NaN,20081201480500,1.0,NaN,2983.22,...,0.0,0.0,NaN,8.90,178.0,NaN,NaN,5700.0,44.5,46.1
4264,4264,308800,2010,17869,3,NaN,20081201480600,1.0,NaN,2812.21,...,0.0,0.0,NaN,22.00,660.0,NaN,NaN,8740.0,28.4,32.8
4265,4265,308801,2010,17870,3,NaN,20081204010700,1.0,NaN,1472.58,...,0.0,0.0,NaN,12.00,480.0,NaN,NaN,2300.0,59.6,54.9
4266,4266,308802,2010,17870,3,NaN,20081204010700,1.0,NaN,1472.58,...,21.0,6366.0,NaN,17.00,680.0,NaN,NaN,4840.0,32.8,36.6
4282,4282,308818,2010,17875,3,NaN,20081202906100,1.0,NaN,2983.22,...,21.0,9997.0,NaN,13.00,598.0,NaN,NaN,9200.0,50.8,41.9
4283,4283,308819,2010,17875,3,NaN,20081202906100,1.0,NaN,2983.22,...,0.0,0.0,NaN,20.50,820.0,NaN,NaN,5000.0,50.3,50.7
4285,4285,308821,2010,17876,3,NaN,20081204010800,1.0,NaN,1427.40,...,21.0,6502.0,NaN,20.50,820.0,NaN,NaN,5700.0,44.5,46.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176633,176633,12935359,2017,14505,3,NaN,20151205558700,1.0,NaN,1535.78,...,21.0,2732.0,NaN,15.98,687.0,NaN,NaN,5240.0,35.5,40.4
176634,176634,12935360,2017,14505,3,NaN,20151205558700,1.0,NaN,1535.78,...,0.0,0.0,NaN,10.00,150.0,NaN,NaN,4610.0,36.3,41.7
176642,176642,12935368,2017,14510,3,NaN,20161205613800,1.0,NaN,2051.28,...,21.0,4574.0,NaN,18.00,500.0,NaN,NaN,5610.0,29.2,34.9
176644,176644,12935370,2017,14512,3,NaN,20161205608400,1.0,NaN,2553.37,...,0.0,0.0,NaN,19.00,760.0,NaN,NaN,8760.0,61.0,55.9
176645,176645,12935371,2017,14512,3,NaN,20161205608400,1.0,NaN,2553.37,...,21.0,3294.0,NaN,17.00,765.0,NaN,NaN,4700.0,50.3,44.2
176660,176660,12935386,2017,14517,3,NaN,20161205588800,1.0,NaN,2126.01,...,0.0,0.0,NaN,8.00,160.0,NaN,NaN,4760.0,32.8,33.6
176683,176683,12935409,2017,14527,3,NaN,20170305611200,1.0,NaN,4787.58,...,22.0,4551.0,NaN,22.00,880.0,NaN,NaN,350.0,61.5,69.2
176696,176696,12935422,2017,14545,3,NaN,20151205554500,1.0,NaN,2184.77,...,0.0,0.0,NaN,12.25,490.0,NaN,NaN,5110.0,35.5,31.8
176800,176800,12935526,2017,14599,3,NaN,20151205498100,1.0,NaN,1747.38,...,0.0,0.0,NaN,10.00,300.0,NaN,NaN,5860.0,35.5,33.9
176809,176809,12935535,2017,14604,3,NaN,20151205482200,1.0,NaN,2150.47,...,0.0,0.0,NaN,10.75,430.0,NaN,NaN,5620.0,35.5,27.4
176817,176817,12935543,2017,14608,3,NaN,20161205565700,1.0,NaN,2472.19,...,22.0,7819.0,NaN,34.00,1365.0,NaN,NaN,3130.0,61.5,66.5
176855,176855,12935581,2017,14624,3,NaN,20161205573900,1.0,NaN,2315.55,...,0.0,0.0,NaN,13.53,595.0,NaN,NaN,3600.0,36.3,41.7
176894,176894,12935620,2017,14652,3,NaN,20161205535500,1.0,NaN,1967.34,...,0.0,0.0,NaN,11.65,431.0,NaN,NaN,4720.0,30.9,29.5
176902,176902,12935628,2017,14658,3,NaN,20161205569100,1.0,NaN,2140.52,...,21.0,6852.0,NaN,12.50,475.0,NaN,NaN,3600.0,36.3,41.7
176935,176935,12935661,2017,14686,3,NaN,20151205504300,1.0,NaN,1962.65,...,0.0,0.0,NaN,14.00,350.0,NaN,NaN,6440.0,40.6,44.6
177033,177033,12935759,2017,14746,3,NaN,20151205498400,1.0,NaN,2689.33,...,21.0,1674.0,NaN,7.50,173.0,NaN,NaN,3600.0,36.3,41.7
177057,177057,12935783,2017,14753,3,NaN,20151205494300,1.0,NaN,2689.33,...,21.0,3383.0,NaN,15.00,596.0,NaN,NaN,5860.0,35.5,33.9
177098,177098,12935824,2017,14774,3,NaN,20151205477600,1.0,NaN,2295.01,...,22.0,6875.0,NaN,19.64,786.0,NaN,NaN,8140.0,40.1,41.9
177101,177101,12935827,2017,14778,3,NaN,20170305533000,1.0,NaN,2458.51,...,0.0,0.0,NaN,10.50,390.0,NaN,NaN,3930.0,21.9,42.1
177102,177102,12935828,2017,14778,3,NaN,20170305533000,1.0,NaN,2458.51,...,21.0,3316.0,NaN,14.00,700.0,NaN,NaN,4010.0,50.3,30.7
177107,177107,12935833,2017,14787,3,NaN,20161205539300,1.0,NaN,3205.90,...,10.0,0.0,NaN,12.00,480.0,NaN,NaN,4720.0,30.9,29.5
177380,177380,12936950,2017,15421,3,NaN,20161205738500,1.0,NaN,4792.41,...,0.0,0.0,NaN,10.00,250.0,NaN,NaN,4110.0,20.3,28.1
177399,177399,12936969,2017,15429,3,NaN,20151205689200,1.0,NaN,3504.34,...,21.0,7886.0,NaN,18.95,403.0,NaN,NaN,9100.0,32.4,32.1
177401,177401,12936971,2017,15429,3,NaN,20151205689200,1.0,NaN,3504.34,...,0.0,0.0,NaN,12.00,480.0,NaN,NaN,5240.0,35.5,40.4
177441,177441,12937011,2017,15449,3,NaN,20151205664300,1.0,NaN,4220.10,...,21.0,4935.0,NaN,8.50,740.0,NaN,NaN,4510.0,35.0,36.1
177593,177593,12937497,2017,15677,3,NaN,20161205738700,1.0,NaN,3512.72,...,21.0,3365.0,NaN,15.83,600.0,NaN,NaN,7840.0,28.4,29.6
177594,177594,12937498,2017,15677,3,NaN,20161205738700,1.0,NaN,3512.72,...,21.0,2389.0,NaN,28.00,1300.0,NaN,NaN,7810.0,32.1,34.7
177618,177618,12937522,2017,15691,3,NaN,20161205747500,1.0,NaN,2555.95,...,0.0,0.0,NaN,16.00,500.0,NaN,NaN,3950.0,14.7,37.2
177635,177635,12937539,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,21.0,3880.0,NaN,10.00,600.0,NaN,NaN,9620.0,17.5,24.0
177636,177636,12937540,2017,15702,3,NaN,20161205712000,1.0,NaN,4288.12,...,0.0,0.0,NaN,13.75,550.0,NaN,NaN,4000.0,26.4,30.7

In [68]:
len(d312)

675

In [69]:
d31.loc[d31.PAIDGH.isnull()]

,Unnamed: 0,Unnamed: 0.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,ASECWTH,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
76,76,4505,2010,2701,1,2635.4699,20091000264100,NaN,NaN,NaN,...,NaN,NaN,0.0,9.30,465.00,50.0,0.0,3600.0,36.3,41.7
84,84,4513,2010,2704,1,3786.7243,20081005433500,NaN,NaN,NaN,...,NaN,NaN,0.0,30.00,800.00,999.0,50.0,4520.0,35.0,36.1
100,100,4529,2010,2708,1,2745.0915,20091002928100,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,290.00,40.0,0.0,5850.0,35.5,31.9
102,102,4531,2010,2710,1,2544.1069,20091006186600,NaN,NaN,NaN,...,NaN,NaN,3800.0,14.00,560.00,40.0,0.0,2000.0,50.6,56.7
103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,NaN,...,NaN,NaN,0.0,25.00,1000.00,40.0,0.0,9100.0,32.4,32.1
119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,234.50,999.0,0.0,4060.0,15.3,21.1
138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,253.75,35.0,0.0,4060.0,15.3,21.1
248,248,11999,2010,6258,1,3813.9774,20081005464300,NaN,NaN,NaN,...,NaN,NaN,2000.0,38.00,800.00,999.0,0.0,8630.0,26.3,42.9
249,249,12000,2010,6258,1,3813.9774,20081005464300,NaN,NaN,NaN,...,NaN,NaN,2000.0,13.50,600.00,999.0,0.0,2000.0,50.6,56.7
250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,NaN,...,NaN,NaN,0.0,32.00,1280.00,40.0,0.0,6200.0,50.3,53.2
271,271,12031,2010,6271,1,2861.4301,20091001515500,NaN,NaN,NaN,...,NaN,NaN,0.0,9.50,380.00,40.0,0.0,2010.0,52.4,51.5
273,273,12033,2010,6272,1,2605.6782,20091001515700,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,361.11,999.0,36.0,2540.0,50.6,45.7
318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,480.00,40.0,0.0,4220.0,16.1,22.3
321,321,12122,2010,6314,1,2880.4128,20081005357400,NaN,NaN,NaN,...,NaN,NaN,0.0,37.50,750.00,20.0,0.0,2340.0,46.0,45.7
322,322,12123,2010,6314,1,2880.4128,20081005357400,NaN,NaN,NaN,...,NaN,NaN,0.0,38.50,730.76,999.0,52.0,2440.0,41.3,29.3
344,344,12169,2010,6333,1,3819.5067,20091005633300,NaN,NaN,NaN,...,NaN,NaN,0.0,39.00,1462.50,999.0,0.0,3150.0,36.7,56.0
433,433,28940,2010,15235,1,2734.2554,20091005624000,NaN,NaN,NaN,...,NaN,NaN,0.0,20.00,950.00,40.0,0.0,8910.0,41.2,38.2
436,436,28943,2010,15236,1,2721.6624,20091006184300,NaN,NaN,NaN,...,NaN,NaN,0.0,7.25,145.00,20.0,0.0,4720.0,30.9,29.5
469,469,29027,2010,15296,1,2807.5127,20081005550700,NaN,NaN,NaN,...,NaN,NaN,0.0,12.60,550.00,999.0,0.0,5620.0,35.5,27.4
470,470,29028,2010,15296,1,2807.5127,20081005550700,NaN,NaN,NaN,...,NaN,NaN,0.0,8.96,358.40,40.0,0.0,5240.0,35.5,40.4
487,487,29045,2010,15303,1,4079.5181,20091002927800,NaN,NaN,NaN,...,NaN,NaN,0.0,5.00,725.00,25.0,0.0,4040.0,19.9,24.5
531,531,29089,2010,15325,1,2906.0264,20091006532300,NaN,NaN,NaN,...,NaN,NaN,0.0,18.80,530.00,999.0,0.0,100.0,50.3,56.5
532,532,29090,2010,15325,1,2906.0264,20091006532300,NaN,NaN,NaN,...,NaN,NaN,0.0,12.00,300.00,999.0,0.0,5160.0,49.5,43.3
550,550,29130,2010,15343,1,3916.7585,20081005528100,NaN,NaN,NaN,...,NaN,NaN,410.0,13.75,550.00,999.0,0.0,5240.0,35.5,40.4
553,553,29133,2010,15344,1,3979.2145,20081005535800,NaN,NaN,NaN,...,NaN,NaN,0.0,16.67,616.79,37.0,0.0,5610.0,29.2,34.9
554,554,29134,2010,15344,1,3979.2145,20081005535800,NaN,NaN,NaN,...,NaN,NaN,0.0,8.00,200.00,25.0,0.0,4010.0,50.3,30.7
577,577,29185,2010,15370,1,2659.9043,20081005556000,NaN,NaN,NaN,...,NaN,NaN,0.0,8.00,64.00,8.0,0.0,4150.0,26.4,25.4
637,637,29355,2010,15440,1,2281.2721,20081005382200,NaN,NaN,NaN,...,NaN,NaN,0.0,30.00,1200.00,40.0,0.0,6230.0,39.9,38.9
659,659,29377,2010,15451,1,2852.4104,20091004933100,NaN,NaN,NaN,...,NaN,NaN,0.0,18.00,720.00,40.0,0.0,3400.0,61.0,56.7
703,703,36322,2010,18803,1,2659.9043,20091000263900,NaN,NaN,NaN,...,NaN,NaN,0.0,22.00,264.00,12.0,0.0,940.0,50.3,48.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199530,199530,14831415,2018,54598,5,3398.0577,20170205691500,NaN,NaN,NaN,...,NaN,NaN,NaN,14.83,593.20,40.0,0.0,9620.0,17.5,24.0
199531,199531,14831416,2018,54598,5,3398.0577,20170205691500,NaN,NaN,NaN,...,NaN,NaN,NaN,13.00,494.00,38.0,0.0,4220.0,16.1,22.3
199534,199534,14831419,2018,54600,5,3444.6243,20170205691900,NaN,NaN,NaN,...,NaN,NaN,NaN,26.00,1040.00,40.0,0.0,6230.0,39.9,38.9
199559,199559,14831473,2018,54629,5,4550.2334,20180205516200,NaN,NaN,NaN,...,NaN,NaN,NaN,18.62,595.84,32.0,0.0,2340.0,46.0,45.7
199575,199575,14831499,2018,54645,5,4987.8438,20170205697400,NaN,NaN,NaN,...,NaN,NaN,NaN,20.59,823.60,40.0,0.0,8100.0,28.4,33.7
199607,199607,14831550,2018,54676,5,4503.2797,20170205700800,NaN,NaN,NaN,...,NaN,NaN,NaN,10.00,360.00,36.0,0.0,310.0,50.3,41.0
199648,199648,14831609,2018,54704,5,4972.5775,20170205703700,NaN,NaN,NaN,...,NaN,NaN,NaN,12.98,519.20,40.0,0.0,2010.0,52.4,51.5
199649,199649,14831610,2018,54704,5,4972.5775,20170205703700,NaN,NaN,NaN,...,NaN,NaN,NaN,11.00,616.00,56.0,0.0,8965.0,28.4,31.7
199683,199683,14831669,2018,54738,5,3329.9105,20170205707700,NaN,NaN,NaN,...,NaN,NaN,NaN,23.00,1038.46,999.0,52.0,7750.0,28.4,34.0
199686,199686,14831678,2018,54745,5,3398.0577,20170205708600,NaN,NaN,NaN,...,NaN,NaN,NaN,15.30,612.00,40.0,0.0,5520.0,33.5,34.8
199721,199721,14831726,2018,54763,5,4501.2560,20170205709600,NaN,NaN,NaN,...,NaN,NaN,NaN,10.50,420.00,40.0,0.0,4140.0,17.6,16.8
199725,199725,14831732,2018,54771,5,4815.9518,20180205529300,NaN,NaN,NaN,...,NaN,NaN,NaN,11.50,460.00,40.0,0.0,5620.0,35.5,27.4
199726,199726,14831733,2018,54771,5,4815.9518,20180205529300,NaN,NaN,NaN,...,NaN,NaN,NaN,21.00,945.00,40.0,0.0,5610.0,29.2,34.9
199745,199745,14831758,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,12.98,519.20,40.0,0.0,2630.0,58.2,46.5
199746,199746,14831759,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,12.50,500.00,40.0,0.0,8740.0,28.4,32.8
199748,199748,14831761,2018,54783,5,3268.4282,20170205711400,NaN,NaN,NaN,...,NaN,NaN,NaN,20.00,800.00,40.0,0.0,1610.0,67.7,73.1
199753,199753,14831766,2018,54788,5,3398.0577,20170205712200,NaN,NaN,NaN,...,NaN,NaN,NaN,12.95,923.00,999.0,0.0,5700.0,44.5,46.1
199763,199763,14831786,2018,54796,5,3487.2109,20180205533100,NaN,NaN,NaN,...,NaN,NaN,NaN,3.63,350.00,999.0,0.0,4110.0,20.3,28.1
199793,199793,14831832,2018,54828,5,3268.4282,20170205716400,NaN,NaN,NaN,...,NaN,NaN,NaN,30.00,540.00,18.0,0.0,2440.0,41.3,29.3
199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,NaN,...,NaN,NaN,NaN,17.00,306.00,18.0,0.0,2310.0,59.6,64.1
199961,199961,14832109,2018,54987,5,5755.4387,20180205553000,NaN,NaN,NaN,...,NaN,NaN,NaN,1.00,40.00,40.0,0.0,5240.0,35.5,40.4
199985,199985,14832153,2018,55007,5,4548.1886,20180205554800,NaN,NaN,NaN,...,NaN,NaN,NaN,25.44,1250.00,999.0,52.0,1060.0,50.6,73.7
200002,200002,14832190,2018,55029,5,5399.0825,20180205556700,NaN,NaN,NaN,...,NaN,NaN,NaN,15.70,628.00,40.0,0.0,7750.0,28.4,34.0
200003,200003,14832191,2018,55029,5,5399.0825,20180205556700,NaN,NaN,NaN,...,NaN,NaN,NaN,15.50,620.00,40.0,0.0,7330.0,32.8,29.5
200028,200028,14832236,2018,55056,5,3398.0577,20170205738900,NaN,NaN,NaN,...,NaN,NaN,NaN,24.01,960.40,40.0,0.0,8640.0,28.4,29.7
200029,200029,14832237,2018,55056,5,3398.0577,20170205738900,NaN,NaN,NaN,...,NaN,NaN,NaN,8.75,350.00,40.0,0.0,6820.0,26.3,39.8
200049,200049,14832277,2018,55077,5,3399.8890,20180205560300,NaN,NaN,NaN,...,NaN,NaN,NaN,3.47,314.10,30.0,0.0,4110.0,20.3,28.1
200051,200051,14832289,2018,55083,5,4336.0718,20180205560800,NaN,NaN,NaN,...,NaN,NaN,NaN,20.00,500.00,999.0,0.0,9600.0,28.4,30.4
200052,200052,14832290,2018,55083,5,4336.0718,20180205560800,NaN,NaN,NaN,...,NaN,NaN,NaN,13.00,230.76,999.0,0.0,4220.0,16.1,22.3
200055,200055,14832293,2018,55085,5,3284.8946,20170205741300,NaN,NaN,NaN,...,NaN,NaN,NaN,25.25,2060.50,42.0,0.0,8965.0,28.4,31.7

In [70]:
len(d31.loc[d31.PAIDGH.isnull()])

9009

In [71]:
# d41 
d4 = df
d4['EARNWEEK'].value_counts().sort_index()

0.00          25
0.01           2
0.10           1
0.48           1
0.50           1
1.00           4
1.15           1
1.19           1
1.53           2
2.00           1
2.40           1
2.88           1
3.36           1
3.65           1
3.75           1
5.76           1
7.25           1
10.00          1
11.60          1
12.00          2
12.50          1
14.00          1
16.00          1
19.21          1
20.00          3
20.32          1
22.00          1
22.30          1
23.00          1
23.07          2
           ...
2654.00        1
2673.07        3
2676.92        1
2692.00        8
2692.30       25
2700.00        3
2708.33        1
2711.00        1
2711.53        2
2720.00        1
2730.76        1
2750.00       10
2769.00        3
2769.23        5
2788.00        2
2788.46        8
2800.00        4
2807.69        1
2815.00        3
2815.38        1
2826.00        1
2826.92        1
2846.00        3
2846.15        3
2850.00        2
2865.38        1
2884.00       29
2884.61      523
2885.00       54
9999.99    93361
Name: EARNWEEK, Length: 2893, dtype: int64

In [72]:
d4.loc[d4['EARNWEEK'].isin([0, 9999.99]), 'EARNWEEK']= np.nan
d4 = d4.loc[d4.EARNWEEK.notnull()]

In [73]:
d4['UHRSWORKT'].value_counts().sort_index()

0        13
1         3
2         8
3        11
4        30
5        25
6        27
7         9
8        68
9        10
10      116
11        2
12       79
13       10
14       18
15      146
16      105
17       10
18       44
19        4
20      563
21       17
22       24
23       18
24      167
25      288
26       19
27       27
28       61
29       16
       ...
60      485
61        1
62       11
63       10
64       10
65       71
66        6
67        2
68        5
69        1
70       86
72       11
73        2
74        2
75       15
76        2
77        2
78        2
79        3
80       63
84        4
85        5
86        1
87        1
90       11
96        2
99        4
100       4
125       1
997    1048
Name: UHRSWORKT, Length: 90, dtype: int64

In [76]:
d4.loc[d4['UHRSWORKT'].isin([0, 997]), 'UHRSWORKT'] = np.nan
d41 = d4[d4.UHRSWORKT.notnull()]

C:\Users\yfeng\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [78]:
d41.loc[:, ['EARNWEEK', 'UHRSWORKT']]

        EARNWEEK  UHRSWORKT
6         769.23       40.0
7         711.53       40.0
8         250.00        4.0
9        1384.00       40.0
76        465.00       50.0
83       2500.00       50.0
84        800.00       25.0
87       2000.00       40.0
100       290.00       40.0
102       560.00       40.0
103      1000.00       40.0
117       700.00       40.0
118       845.00       45.0
119       234.50       36.0
138       253.75       35.0
141      1634.61       50.0
142      1326.92       41.0
192       880.00       40.0
195       884.61       40.0
196       673.07       40.0
201       760.00       40.0
230       993.69       40.0
232      1100.00       40.0
248       800.00       42.0
249       600.00       38.0
250      1280.00       40.0
252      2884.61       74.0
255       180.00       40.0
270       669.00       40.0
271       380.00       40.0
...          ...        ...
199744   1153.84       40.0
199745    519.20       40.0
199746    500.00       40.0
199748    800.00       40.0
199750   1000.00       40.0
199752   1346.15       45.0
199753    923.00       40.0
199755    480.00       50.0
199763    350.00       30.0
199792    576.92       40.0
199793    540.00       18.0
199804   2653.00       37.0
199809   1442.30       40.0
199810    306.00       18.0
199864    300.00       40.0
199933   1300.00       40.0
199954    576.00       40.0
199961     40.00       40.0
199984    528.84       35.0
199985   1250.00       40.0
200002    628.00       40.0
200003    620.00       40.0
200027   2884.61       40.0
200028    960.40       40.0
200029    350.00       40.0
200049    314.10       30.0
200051    500.00       40.0
200052    230.76       25.0
200055   2060.50       42.0
200057   1634.61       40.0

[17210 rows x 2 columns]