In [1]:
import pandas as pd
q1 = pd.read_csv('C:/Users/Yutin/Desktop/Low_wage_report/q1_obs_22033 .csv')

In [12]:
#22033 obs in q1
ind_q1 = q1.IND.value_counts()
ind_q1 = pd.DataFrame(ind_q1)
ind_q1.columns = ['IND_detail']
ind_q1['IND_perecnt_%'] = ind_q1.IND_detail/22033*100
ind_q1

      IND_detail  IND_perecnt_%
8680        3493      15.853492
770         1671       7.584078
4970        1014       4.602188
6170         755       3.426678
7690         580       2.632415
5380         538       2.441792
7770         509       2.310171
7860         459       2.083239
8980         401       1.819997
5170         382       1.733763
4470         358       1.624835
6380         335       1.520447
8190         305       1.384287
6180         302       1.370671
7580         269       1.220896
7680         265       1.202741
8590         262       1.189125
8660         242       1.098352
9470         241       1.093814
4670         239       1.084737
6390         233       1.057505
8270         212       0.962193
4870         208       0.944038
8770         173       0.785186
3490         167       0.757954
7070         167       0.757954
7870         166       0.753415
6190         159       0.721645
3190         155       0.703490
5390         149       0.676258
...          ...            ...
5670           5       0.022693
2480           5       0.022693
7460           5       0.022693
4260           5       0.022693
290            5       0.022693
6695           5       0.022693
5591           5       0.022693
8990           5       0.022693
4680           5       0.022693
3670           4       0.018155
2590           4       0.018155
4480           4       0.018155
3970           4       0.018155
6880           4       0.018155
8780           4       0.018155
7570           3       0.013616
7170           3       0.013616
6280           3       0.013616
8970           2       0.009077
3470           2       0.009077
3365           2       0.009077
2470           2       0.009077
7880           2       0.009077
4490           2       0.009077
8670           2       0.009077
5295           1       0.004539
9180           1       0.004539
1570           1       0.004539
7370           1       0.004539
6672           1       0.004539

[235 rows x 2 columns]

In [13]:
ind_q1.to_csv('C:/Users/Yutin/Desktop/Low_wage_report/ind_q1.csv')