In [74]:
import pandas as pd
q1 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/Figure1/figure_q1.csv')
q2 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/Figure1/figure_q2.csv')
q3 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/Figure1/figure_q3.csv')
q4 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/Figure1/figure_q4.csv')

# Transition in Q1

In [75]:
q1[q1['EMPSTAT'].isin([30,31,32,33,34,35,36])]

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
11,3709,3709,306662,2010,16930,3,NaN,2.009020e+13,1,NaN,...,10,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
25,3834,3834,308290,2010,17635,3,NaN,2.010020e+13,1,NaN,...,21,2585,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
65,4145,4145,308681,2010,17823,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
73,4318,4318,308854,2010,17895,3,NaN,2.009010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
80,4389,4389,308925,2010,17921,3,NaN,2.009030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
82,4419,4419,308955,2010,17934,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
87,4449,4449,308985,2010,17945,3,NaN,0.000000e+00,1,NaN,...,21,6309,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
94,4509,4509,309045,2010,17963,3,NaN,2.009120e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
112,4724,4724,309260,2010,18052,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
119,4846,4846,309382,2010,18106,3,NaN,2.010010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
161,5380,5380,309916,2010,18363,3,NaN,2.009120e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
176,5516,5516,310052,2010,18460,3,NaN,2.010030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
180,5540,5540,310076,2010,18479,3,NaN,2.008120e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
181,5545,5545,310081,2010,18482,3,NaN,2.008120e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4060.0,15.3,21.1
193,5609,5609,310145,2010,18518,3,NaN,2.009010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
195,5647,5647,310183,2010,18552,3,NaN,2.009020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
199,5659,5659,310195,2010,18558,3,NaN,2.009020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
210,5778,5778,310314,2010,18622,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
216,5815,5815,310351,2010,18646,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
224,5863,5863,310399,2010,18680,3,NaN,0.000000e+00,1,NaN,...,21,2583,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
298,28766,28766,2137791,2011,16807,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
300,28779,28779,2137804,2011,16812,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
326,29014,29014,2139545,2011,17648,3,NaN,2.010020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
351,29237,29237,2139768,2011,17745,3,NaN,2.010120e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
368,29379,29379,2139910,2011,17810,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
381,29497,29497,2140028,2011,17864,3,NaN,2.010030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
392,29633,29633,2140164,2011,17922,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
394,29656,29656,2140187,2011,17929,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
401,29748,29748,2140279,2011,17979,3,NaN,2.010020e+13,1,NaN,...,21,4889,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
414,29821,29821,2140352,2011,18016,3,NaN,2.011010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000,152930,152930,11065723,2016,14827,3,NaN,0.000000e+00,1,NaN,...,21,8138,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2013,153004,153004,11065797,2016,14856,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2014,153009,153009,11065802,2016,14857,3,NaN,0.000000e+00,1,NaN,...,21,5244,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2091,175627,175627,12934269,2017,13960,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2104,175735,175735,12934461,2017,14063,3,NaN,2.016020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2109,175765,175765,12934491,2017,14081,3,NaN,2.016030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2110,175771,175771,12934497,2017,14084,3,NaN,2.016030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2111,175794,175794,12934520,2017,14093,3,NaN,2.016010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2112,175795,175795,12934521,2017,14093,3,NaN,2.016010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2121,175836,175836,12934562,2017,14118,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
2156,176277,176277,12935003,2017,14329,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2157,176284,176284,12935010,2017,14331,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2164,176372,176372,12935098,2017,14373,3,NaN,2.016020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2189,176589,176589,12935315,2017,14485,3,NaN,2.016030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2206,176709,176709,12935435,2017,14556,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2222,176848,176848,12935574,2017,14622,3,NaN,2.017010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2229,176970,176970,12935696,2017,14705,3,NaN,2.016030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2234,177022,177022,12935748,2017,14743,3,NaN,2.017010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2250,177110,177110,12935836,2017,14833,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2251,177112,177112,12935838,2017,14833,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2256,177156,177156,12935882,2017,14847,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2265,177207,177207,12935933,2017,14869,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2267,177225,177225,12935951,2017,14882,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2273,177237,177237,12935963,2017,14890,3,NaN,0.000000e+00,1,NaN,...,22,5153,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2293,177375,177375,12936945,2017,15418,3,NaN,2.016020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2294,177391,177391,12936961,2017,15425,3,NaN,2.017010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2300,177446,177446,12937016,2017,15452,3,NaN,2.017010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2309,177502,177502,12937072,2017,15477,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2310,177516,177516,12937086,2017,15481,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0
2316,177586,177586,12937490,2017,15674,3,NaN,2.017010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9920.0,0.0,0.0

In [76]:
len(q1[q1['EMPSTAT'].notna()])

2327

In [77]:
len(q1[q1['OCC'].notna()])

2327

In [78]:
len(q1[q1['OCCLY'].notna()])

2327

In [79]:
# q1ew: out of labor force:180 obs
len(q1[q1['EMPSTAT'].isin([30,31,32,33,34,35,36])])

180

In [80]:
# q1: unemployed:155
len(q1[q1['EMPSTAT'].isin([20,21,22])])

155

In [81]:
# same occ: 1762
q1.loc[(q1['OCC']==q1['OCCLY']) & (q1['OCCLY'].notna()) & (~q1['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]))]

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
0,3648,3648,306601,2010,16894,3,NaN,2.009120e+13,1,NaN,...,0,0,NaN,15.00,900.00,NaN,NaN,6260.0,17.5,36.4
1,3650,3650,306603,2010,16895,3,NaN,2.009120e+13,1,NaN,...,0,0,NaN,10.00,400.00,NaN,NaN,9620.0,17.5,24.0
2,3652,3652,306605,2010,16896,3,NaN,2.009120e+13,1,NaN,...,21,8982,NaN,99.99,400.00,NaN,NaN,9100.0,32.4,32.1
3,3654,3654,306607,2010,16898,3,NaN,2.009120e+13,1,NaN,...,0,0,NaN,11.00,440.00,NaN,NaN,4510.0,35.0,36.1
4,3660,3660,306613,2010,16901,3,NaN,2.009120e+13,1,NaN,...,21,4696,NaN,99.99,1060.00,NaN,NaN,9130.0,32.1,30.4
5,3669,3669,306622,2010,16908,3,NaN,2.010010e+13,1,NaN,...,22,6114,NaN,99.99,9999.99,NaN,NaN,7840.0,28.4,29.6
6,3672,3672,306625,2010,16908,3,NaN,2.010010e+13,1,NaN,...,0,6102,NaN,99.99,9999.99,NaN,NaN,8800.0,28.4,25.1
7,3675,3675,306628,2010,16910,3,NaN,2.010020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
8,3684,3684,306637,2010,16918,3,NaN,2.009120e+13,1,NaN,...,0,0,NaN,5.00,575.00,NaN,NaN,4040.0,19.9,24.5
10,3691,3691,306644,2010,16921,3,NaN,2.009010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
12,3712,3712,306665,2010,16931,3,NaN,2.009020e+13,1,NaN,...,22,4913,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
13,3718,3718,306671,2010,16935,3,NaN,2.009030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
14,3748,3748,306701,2010,16942,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,0.00,9999.99,NaN,NaN,4000.0,26.4,30.7
16,3754,3754,306707,2010,16943,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
18,3764,3764,306717,2010,16944,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4060.0,15.3,21.1
20,3777,3777,308233,2010,17609,3,NaN,2.009120e+13,1,NaN,...,0,0,NaN,10.00,370.00,NaN,NaN,9140.0,22.0,28.1
21,3788,3788,308244,2010,17615,3,NaN,2.009120e+13,1,NaN,...,22,5583,NaN,99.99,615.00,NaN,NaN,7010.0,33.9,51.4
22,3797,3797,308253,2010,17619,3,NaN,2.010010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9640.0,28.4,22.1
23,3798,3798,308254,2010,17620,3,NaN,2.010010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,6200.0,50.3,53.2
26,3853,3853,308309,2010,17648,3,NaN,2.010030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
28,3886,3886,308342,2010,17664,3,NaN,2.009010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
29,3893,3893,308349,2010,17667,3,NaN,2.009020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4
30,3897,3897,308353,2010,17667,3,NaN,2.009020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4
32,3919,3919,308375,2010,17679,3,NaN,0.000000e+00,1,NaN,...,21,5900,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
33,3920,3920,308376,2010,17679,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
34,3927,3927,308383,2010,17683,3,NaN,0.000000e+00,1,NaN,...,21,8596,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
36,3945,3945,308401,2010,17688,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
37,3950,3950,308406,2010,17691,3,NaN,0.000000e+00,1,NaN,...,21,8622,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
38,3953,3953,308409,2010,17692,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,6660.0,31.3,46.9
39,3955,3955,308411,2010,17693,3,NaN,0.000000e+00,1,NaN,...,21,8983,NaN,99.99,9999.99,NaN,NaN,6200.0,50.3,53.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2281,177286,177286,12936012,2017,14915,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,0.00,9999.99,NaN,NaN,4720.0,30.9,29.5
2282,177302,177302,12936028,2017,14925,3,NaN,0.000000e+00,1,NaN,...,22,9997,NaN,99.99,9999.99,NaN,NaN,4110.0,20.3,28.1
2283,177306,177306,12936032,2017,14926,3,NaN,0.000000e+00,1,NaN,...,21,3266,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
2284,177309,177309,12936035,2017,14926,3,NaN,0.000000e+00,1,NaN,...,21,9997,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
2285,177314,177314,12936040,2017,14928,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4000.0,26.4,30.7
2287,177333,177333,12936059,2017,14937,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,3930.0,21.9,42.1
2288,177340,177340,12936066,2017,14939,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4110.0,20.3,28.1
2290,177357,177357,12936083,2017,14948,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9140.0,22.0,28.1
2291,177366,177366,12936092,2017,14952,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,3930.0,21.9,42.1
2292,177367,177367,12936093,2017,14952,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4140.0,17.6,16.8
2295,177399,177399,12936969,2017,15429,3,NaN,2.015120e+13,1,NaN,...,21,7886,NaN,18.95,403.00,NaN,NaN,9100.0,32.4,32.1
2296,177418,177418,12936988,2017,15440,3,NaN,2.016010e+13,1,NaN,...,21,9997,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
2297,177439,177439,12937009,2017,15447,3,NaN,2.017010e+13,1,NaN,...,21,1724,NaN,99.99,9999.99,NaN,NaN,4110.0,20.3,28.1
2298,177441,177441,12937011,2017,15449,3,NaN,2.015120e+13,1,NaN,...,21,4935,NaN,8.50,740.00,NaN,NaN,4510.0,35.0,36.1
2304,177473,177473,12937043,2017,15460,3,NaN,2.017020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4000.0,26.4,30.7
2305,177475,177475,12937045,2017,15461,3,NaN,2.017020e+13,1,NaN,...,21,4130,NaN,99.99,9999.99,NaN,NaN,8965.0,28.4,31.7
2306,177476,177476,12937046,2017,15461,3,NaN,2.017020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,8965.0,28.4,31.7
2307,177489,177489,12937059,2017,15471,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
2313,177548,177548,12937452,2017,15652,3,NaN,2.017030e+13,1,NaN,...,21,9126,NaN,99.99,9999.99,NaN,NaN,7750.0,28.4,34.0
2314,177554,177554,12937458,2017,15655,3,NaN,2.017020e+13,1,NaN,...,21,9997,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
2315,177574,177574,12937478,2017,15665,3,NaN,2.016010e+13,1,NaN,...,21,7039,NaN,99.99,9999.99,NaN,NaN,6040.0,18.4,30.7
2317,177593,177593,12937497,2017,15677,3,NaN,2.016120e+13,1,NaN,...,21,3365,NaN,15.83,600.00,NaN,NaN,7840.0,28.4,29.6
2319,177611,177611,12937515,2017,15685,3,NaN,2.016030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,8140.0,40.1,41.9
2320,177612,177612,12937516,2017,15685,3,NaN,2.016030e+13,1,NaN,...,21,6629,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
2321,177635,177635,12937539,2017,15702,3,NaN,2.016120e+13,1,NaN,...,21,3880,NaN,10.00,600.00,NaN,NaN,9620.0,17.5,24.0
2322,177636,177636,12937540,2017,15702,3,NaN,2.016120e+13,1,NaN,...,0,0,NaN,13.75,550.00,NaN,NaN,4000.0,26.4,30.7
2323,177665,177665,12937569,2017,15715,3,NaN,0.000000e+00,1,NaN,...,21,9997,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
2324,177681,177681,12937585,2017,15720,3,NaN,0.000000e+00,1,NaN,...,21,6883,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
2325,177682,177682,12937586,2017,15720,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
2326,177686,177686,12937590,2017,15721,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8

In [82]:
# different q1 job
q1_occ = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q1_occ_list.csv')
q1_li = list(q1_occ.values.flatten())

In [83]:
q1_li

[840,
 1740,
 2160,
 3800,
 3910,
 3930,
 3940,
 4000,
 4020,
 4030,
 4040,
 4060,
 4110,
 4120,
 4140,
 4220,
 4230,
 4250,
 4510,
 4720,
 4760,
 4830,
 5100,
 5350,
 5510,
 5610,
 5860,
 6040,
 6200,
 6260,
 6330,
 6420,
 6515,
 6530,
 6660,
 6700,
 6720,
 7010,
 7150,
 7260,
 7330,
 7630,
 7720,
 7750,
 7840,
 8140,
 8460,
 8610,
 8800,
 8965,
 9120,
 9130,
 9140,
 9150,
 9600,
 9620,
 9640]

In [84]:
q2_occ = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q2_occ_list.csv')
q2_li = list(q2_occ.values.flatten())

In [85]:
q2_li

[160,
 410,
 600,
 1060,
 1107,
 1920,
 2025,
 2330,
 2440,
 2750,
 3245,
 3500,
 3600,
 3640,
 3655,
 3945,
 4210,
 4610,
 4700,
 4810,
 4840,
 5110,
 5120,
 5140,
 5240,
 5250,
 5320,
 5400,
 5420,
 5520,
 5540,
 5550,
 5560,
 5600,
 5620,
 5700,
 5810,
 5840,
 5940,
 6220,
 6250,
 6320,
 6355,
 6360,
 6400,
 6440,
 7200,
 7340,
 7420,
 7800,
 7810,
 8030,
 8130,
 8220,
 8500,
 8740]

In [86]:
q3_occ = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q3_occ_list.csv')
q3_li = list(q3_occ.values.flatten())

In [87]:
q3_li

[40,
 100,
 120,
 140,
 150,
 310,
 420,
 520,
 540,
 640,
 860,
 910,
 940,
 1006,
 1007,
 1010,
 1050,
 1530,
 1550,
 2000,
 2010,
 2050,
 2145,
 2300,
 2340,
 2600,
 2630,
 2800,
 2840,
 3030,
 3250,
 3300,
 3320,
 3420,
 3740,
 3850,
 4010,
 4710,
 4800,
 4820,
 4850,
 4900,
 4965,
 5000,
 5160,
 5360,
 5800,
 6230,
 7000,
 7410,
 7700,
 7900,
 8810,
 9000,
 9200,
 9750]

In [88]:
q4_occ = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q4_occ_list.csv')
q4_li = list(q4_occ.values.flatten())

In [89]:
q4_li

[10,
 20,
 50,
 110,
 135,
 136,
 220,
 230,
 300,
 350,
 425,
 430,
 530,
 565,
 630,
 650,
 710,
 735,
 740,
 800,
 830,
 850,
 950,
 1020,
 1300,
 1360,
 1410,
 1430,
 1460,
 1650,
 1720,
 1760,
 1820,
 1965,
 2040,
 2100,
 2200,
 2310,
 2320,
 2550,
 2810,
 2900,
 3000,
 3050,
 3060,
 3110,
 3255,
 3310,
 3400,
 3535,
 3645,
 3820,
 4300,
 4620,
 7020,
 7610,
 8760]

In [90]:
q1.loc[~q1['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q1['OCC'].isin(q1_li) &(q1['OCC'] != q1['OCCLY'])]

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,PAIDGH,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT
17,3755,3755,306708,2010,16943,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4250.0,22.5,28.6
24,3812,3812,308268,2010,17628,3,NaN,2.010010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
27,3870,3870,308326,2010,17656,3,NaN,2.008120e+13,1,NaN,...,21,7631,NaN,14.00,560.00,NaN,NaN,5510.0,19.1,22.3
102,4584,4584,309120,2010,17999,3,NaN,2.008120e+13,1,NaN,...,22,7354,NaN,22.50,900.00,NaN,NaN,9100.0,32.4,32.1
164,5397,5397,309933,2010,18379,3,NaN,2.010010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4030.0,26.4,16.8
177,5517,5517,310053,2010,18461,3,NaN,2.010030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4110.0,20.3,28.1
188,5577,5577,310113,2010,18500,3,NaN,2.009010e+13,1,NaN,...,21,3116,NaN,99.99,9999.99,NaN,NaN,6720.0,28.4,32.6
219,5838,5838,310374,2010,18664,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,0.00,9999.99,NaN,NaN,9100.0,32.4,32.1
241,6024,6024,311646,2010,19286,3,NaN,2.008120e+13,1,NaN,...,0,0,NaN,9.00,360.00,NaN,NaN,9620.0,17.5,24.0
293,28734,28734,2137759,2011,16791,3,NaN,2.010120e+13,1,NaN,...,0,0,NaN,19.50,780.00,NaN,NaN,4110.0,20.3,28.1
294,28735,28735,2137760,2011,16791,3,NaN,2.010120e+13,1,NaN,...,0,0,NaN,10.00,169.00,NaN,NaN,4110.0,20.3,28.1
322,28996,28996,2139527,2011,17634,3,NaN,2.011030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4040.0,19.9,24.5
333,29092,29092,2139623,2011,17688,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
348,29197,29197,2139728,2011,17731,3,NaN,2.010030e+13,1,NaN,...,21,1312,NaN,99.99,9999.99,NaN,NaN,4110.0,20.3,28.1
362,29326,29326,2139857,2011,17786,3,NaN,2.011020e+13,1,NaN,...,22,7745,NaN,99.99,9999.99,NaN,NaN,4040.0,19.9,24.5
377,29475,29475,2140006,2011,17853,3,NaN,2.010030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4000.0,26.4,30.7
400,29733,29733,2140264,2011,17968,3,NaN,2.010010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,3940.0,17.5,32.3
413,29817,29817,2140348,2011,18014,3,NaN,2.011010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
441,30035,30035,2140566,2011,18095,3,NaN,0.000000e+00,1,NaN,...,21,4714,NaN,99.99,9999.99,NaN,NaN,4040.0,19.9,24.5
446,30076,30076,2140607,2011,18116,3,NaN,2.010010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4230.0,12.4,20.7
466,30330,30330,2140861,2011,18227,3,NaN,2.011010e+13,1,NaN,...,0,0,NaN,10.20,377.00,NaN,NaN,4760.0,32.8,33.6
468,30337,30337,2140868,2011,18236,3,NaN,2.009120e+13,1,NaN,...,21,1855,NaN,12.00,480.00,NaN,NaN,4040.0,19.9,24.5
501,30647,30647,2141178,2011,18446,3,NaN,2.011020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
503,30652,30652,2141183,2011,18453,3,NaN,2.011030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9640.0,28.4,22.1
509,30691,30691,2141222,2011,18476,3,NaN,2.011030e+13,1,NaN,...,22,9251,NaN,99.99,9999.99,NaN,NaN,6515.0,31.2,37.2
566,31228,31228,2143038,2011,19362,3,NaN,2.010030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
590,53550,53550,3944937,2012,16898,3,NaN,0.000000e+00,1,NaN,...,10,0,NaN,99.99,9999.99,NaN,NaN,5610.0,29.2,34.9
618,53759,53759,3946480,2012,17624,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,0.00,9999.99,NaN,NaN,4720.0,30.9,29.5
646,54042,54042,3946862,2012,17783,3,NaN,2.012030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9100.0,32.4,32.1
654,54132,54132,3946952,2012,17823,3,NaN,2.011010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,6515.0,31.2,37.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,130470,130470,9311202,2015,17599,3,NaN,2.014120e+13,1,NaN,...,10,0,NaN,15.00,653.00,NaN,NaN,7720.0,28.4,34.0
1786,130480,130480,9311212,2015,17604,3,NaN,2.014020e+13,1,NaN,...,21,3032,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
1833,151210,151210,11063915,2016,13908,3,NaN,2.016030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4000.0,26.4,30.7
1835,151219,151219,11063924,2016,13911,3,NaN,2.015010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
1841,151255,151255,11063960,2016,13925,3,NaN,2.015030e+13,1,NaN,...,21,2930,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
1846,151282,151282,11063987,2016,13949,3,NaN,0.000000e+00,1,NaN,...,21,6505,NaN,0.00,9999.99,NaN,NaN,9640.0,28.4,22.1
1864,151435,151435,11064228,2016,14093,3,NaN,0.000000e+00,1,NaN,...,21,6604,NaN,0.00,9999.99,NaN,NaN,4250.0,22.5,28.6
1907,151958,151958,11064751,2016,14322,3,NaN,2.015030e+13,1,NaN,...,22,9997,NaN,99.99,9999.99,NaN,NaN,5860.0,35.5,33.9
1913,152066,152066,11064859,2016,14377,3,NaN,2.016020e+13,1,NaN,...,21,9726,NaN,99.99,9999.99,NaN,NaN,9640.0,28.4,22.1
1925,152185,152185,11064978,2016,14431,3,NaN,2.015120e+13,1,NaN,...,0,0,NaN,2.83,576.00,NaN,NaN,4110.0,20.3,28.1
1974,152738,152738,11065531,2016,14709,3,NaN,2.014120e+13,1,NaN,...,0,0,NaN,10.00,550.00,NaN,NaN,4040.0,19.9,24.5
1980,152788,152788,11065581,2016,14732,3,NaN,2.015010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
1994,152894,152894,11065687,2016,14790,3,NaN,2.016010e+13,1,NaN,...,22,8829,NaN,99.99,9999.99,NaN,NaN,6530.0,35.5,43.0
2008,152957,152957,11065750,2016,14838,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,0.00,9999.99,NaN,NaN,4760.0,32.8,33.6
2009,152963,152963,11065756,2016,14842,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,0.00,9999.99,NaN,NaN,4000.0,26.4,30.7
2018,153081,153081,11065874,2016,14896,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9620.0,17.5,24.0
2113,175797,175797,12934523,2017,14093,3,NaN,2.016010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4760.0,32.8,33.6
2115,175808,175808,12934534,2017,14104,3,NaN,0.000000e+00,1,NaN,...,10,0,NaN,0.00,9999.99,NaN,NaN,4230.0,12.4,20.7
2127,175872,175872,12934598,2017,14130,3,NaN,2.015120e+13,1,NaN,...,10,0,NaN,99.99,9999.99,NaN,NaN,9140.0,22.0,28.1
2130,175928,175928,12934654,2017,14157,3,NaN,2.017030e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4040.0,19.9,24.5
2143,176125,176125,12934851,2017,14262,3,NaN,2.016020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9130.0,32.1,30.4
2203,176689,176689,12935415,2017,14529,3,NaN,2.016010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4720.0,30.9,29.5
2210,176741,176741,12935467,2017,14571,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,0.00,9999.99,NaN,NaN,4760.0,32.8,33.6
2216,176815,176815,12935541,2017,14607,3,NaN,2.016010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4250.0,22.5,28.6
2218,176829,176829,12935555,2017,14613,3,NaN,2.016010e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4220.0,16.1,22.3
2244,177091,177091,12935817,2017,14770,3,NaN,2.017020e+13,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,6260.0,17.5,36.4
2245,177095,177095,12935821,2017,14773,3,NaN,2.016010e+13,1,NaN,...,21,9997,NaN,99.99,9999.99,NaN,NaN,9600.0,28.4,30.4
2286,177322,177322,12936048,2017,14930,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,9100.0,32.4,32.1
2289,177342,177342,12936068,2017,14940,3,NaN,0.000000e+00,1,NaN,...,0,0,NaN,99.99,9999.99,NaN,NaN,4110.0,20.3,28.1
2299,177442,177442,12937012,2017,15450,3,NaN,2.016020e+13,1,NaN,...,21,7795,NaN,99.99,9999.99,NaN,NaN,7720.0,28.4,34.0

In [92]:
#  diferent q1 job: 115
len(q1.loc[~q1['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q1['OCC'].isin(q1_li) &(q1['OCC'] != q1['OCCLY'])])

115

In [93]:
# different q2 job
len(q1.loc[~q1['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q1['OCC'].isin(q2_li) &(q1['OCC'] != q1['OCCLY'])])

34

In [94]:
# different q3 job
len(q1.loc[~q1['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q1['OCC'].isin(q3_li) &(q1['OCC'] != q1['OCCLY'])])

26

In [95]:
# different q4 job
len(q1.loc[(~q1['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22])) & (q1['OCC'].isin(q4_li)) &(q1['OCC'] != q1['OCCLY'])])

12

In [96]:
180+155+1762+115+34+26+12

2284

# q2

In [97]:
len(q2[q2['EMPSTAT'].notna()])

1889

In [98]:
len(q2[q2['OCC'].notna()])

1889

In [99]:
len(q2[q2['OCCLY'].notna()])

1889

In [100]:
# q2ew: out of labor force:79 obs
len(q2[q2['EMPSTAT'].isin([30,31,32,33,34,35,36])])

79

In [101]:
# q2: unemployed:87
len(q2[q2['EMPSTAT'].isin([20,21,22])])

87

In [103]:
# same occ: 1542
len(q2.loc[(q2['OCC']==q2['OCCLY']) & (q2['OCCLY'].notna()) & (~q2['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]))])

1542

In [104]:
#  diferent q1 job: 115
len(q2.loc[~q2['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q2['OCC'].isin(q1_li) &(q2['OCC'] != q2['OCCLY'])])

40

In [105]:
# different q2 job
len(q2.loc[~q2['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q2['OCC'].isin(q2_li) &(q2['OCC'] != q2['OCCLY'])])

46

In [106]:
# different q3 job
len(q2.loc[~q2['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q2['OCC'].isin(q3_li) &(q2['OCC'] != q2['OCCLY'])])

31

In [107]:
# different q4 job
len(q2.loc[(~q2['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22])) & (q2['OCC'].isin(q4_li)) &(q2['OCC'] != q2['OCCLY'])])

21

In [108]:
79+87+1542+40+46+31+21

1846

# q3

In [109]:
len(q3[q3['EMPSTAT'].notna()])

1496

In [110]:
len(q3[q3['OCC'].notna()])

1496

In [111]:
len(q3[q3['OCCLY'].notna()])

1496

In [112]:
# q3ew: out of labor force:44 obs
len(q3[q3['EMPSTAT'].isin([30,31,32,33,34,35,36])])

44

In [113]:
# q3: unemployed:43
len(q3[q3['EMPSTAT'].isin([20,21,22])])

43

In [115]:
# same occ: 1299
len(q3.loc[(q3['OCC']==q3['OCCLY']) & (q3['OCCLY'].notna()) & (~q3['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]))])

1299

In [116]:
#  diferent q1 job: 115
len(q3.loc[~q3['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q3['OCC'].isin(q1_li) &(q3['OCC'] != q3['OCCLY'])])

17

In [117]:

# different q2 job
len(q3.loc[~q3['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q3['OCC'].isin(q2_li) &(q3['OCC'] != q3['OCCLY'])])

18

In [118]:
# different q3 job
len(q3.loc[~q3['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q3['OCC'].isin(q3_li) &(q3['OCC'] != q3['OCCLY'])])

20

In [119]:


# different q4 job
len(q3.loc[(~q3['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22])) & (q3['OCC'].isin(q4_li)) &(q3['OCC'] != q3['OCCLY'])])

38

In [120]:
44+43+1299+17+18+20+38

1479

# q4

In [122]:
len(q4[q4['EMPSTAT'].notna()])

2132

In [123]:
len(q4[q4['OCC'].notna()])

2132

In [124]:
len(q4[q4['OCCLY'].notna()])

2132

In [125]:
# q4ew: out of labor force:54 obs
len(q4[q4['EMPSTAT'].isin([30,31,32,33,34,35,36])])

54

In [126]:
# q4: unemployed:35
len(q4[q4['EMPSTAT'].isin([20,21,22])])

35

In [127]:
# same occ: 1897
len(q4.loc[(q4['OCC']==q4['OCCLY']) & (q4['OCCLY'].notna()) & (~q4['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]))])

1897

In [128]:
#  diferent q1 job: 115
len(q4.loc[~q4['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q4['OCC'].isin(q1_li) &(q4['OCC'] != q4['OCCLY'])])

9

In [129]:
# different q2 job
len(q4.loc[~q4['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q4['OCC'].isin(q2_li) &(q4['OCC'] != q4['OCCLY'])])

13

In [130]:
# different q3 job
len(q4.loc[~q4['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22]) & q4['OCC'].isin(q3_li) &(q4['OCC'] != q4['OCCLY'])])

51

In [131]:
# different q4 job
len(q4.loc[(~q4['EMPSTAT'].isin([30,31,32,33,34,35,36,20,21,22])) & (q4['OCC'].isin(q4_li)) &(q4['OCC'] != q4['OCCLY'])])

43

In [132]:
54+35+1897+9+13+51+43

2102