In [110]:
import pandas as pd
q1 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q1_obs_22033 .csv')
q2 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q2_obs_17873.csv')
q3 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q3_obs_14148.csv')
q4 = pd.read_csv('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q4_obs_20653.csv')

In [111]:
q1['quartile']='q1'
q2['quartile']='q2'
q3['quartile']='q3'
q4['quartile']='q4'

In [112]:
q1

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,quartile
0,25,25,4385,2010,2621,1,3094.6308,20091100281000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1
1,32,32,4404,2010,2636,1,2989.8559,20081005418300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1
2,41,41,4413,2010,2640,1,2987.2396,20081202906200,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1
3,47,47,4449,2010,2660,1,3334.6547,20081101335300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4220.0,16.1,22.3,q1
4,51,51,4453,2010,2661,1,3016.0369,20081106102600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1
5,68,68,4497,2010,2696,1,3320.4949,20091205016600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9140.0,22.0,28.1,q1
6,73,73,4502,2010,2700,1,2658.6825,20091000264000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,6420.0,29.8,33.9,q1
7,93,93,4522,2010,2707,1,2936.5530,20081205882700,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4000.0,26.4,30.7,q1
8,103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,...,NaN,0.0,25.00,1000.00,40.0,0.0,9100.0,32.4,32.1,q1
9,109,109,4550,2010,2725,1,3142.3940,20091203081900,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1
10,112,112,4553,2010,2727,1,2857.6916,20090101460800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4510.0,35.0,36.1,q1
11,119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,...,NaN,0.0,7.25,234.50,999.0,0.0,4060.0,15.3,21.1,q1
12,120,120,4577,2010,2741,1,2934.0235,20081101345300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1
13,123,123,4619,2010,2773,1,4579.0155,20091205725000,NaN,NaN,...,NaN,4030.0,99.99,9999.99,999.0,0.0,5860.0,35.5,33.9,q1
14,133,133,4629,2010,2776,1,2903.7469,20100100277600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1
15,138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,...,NaN,0.0,7.25,253.75,35.0,0.0,4060.0,15.3,21.1,q1
16,184,184,4681,2010,2810,1,3663.0131,20091104332900,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4760.0,32.8,33.6,q1
17,202,202,4773,2010,2867,1,2388.6063,20091005633400,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,8800.0,28.4,25.1,q1
18,205,205,11927,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,8800.0,28.4,25.1,q1
19,207,207,11929,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1
20,215,215,11944,2010,6232,1,2910.5647,20081102626600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,8610.0,35.0,40.2,q1
21,250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,...,NaN,0.0,32.00,1280.00,40.0,0.0,6200.0,50.3,53.2,q1
22,264,264,12024,2010,6267,1,2858.1973,20091201589500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9100.0,32.4,32.1,q1
23,275,275,12035,2010,6272,1,2605.6782,20091001515700,NaN,NaN,...,NaN,0.0,99.99,692.00,999.0,0.0,4760.0,32.8,33.6,q1
24,277,277,12037,2010,6274,1,2640.2708,20091103166800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4000.0,26.4,30.7,q1
25,288,288,12070,2010,6289,1,2659.9043,20081005563500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4250.0,22.5,28.6,q1
26,318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,...,NaN,0.0,12.00,480.00,40.0,0.0,4220.0,16.1,22.3,q1
27,360,360,28849,2010,15196,1,2797.7074,20091203070100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,7260.0,21.6,43.5,q1
28,361,361,28850,2010,15197,1,2440.8800,20081102623300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1
29,366,366,28855,2010,15198,1,3303.7087,20081206425500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22003,199743,199743,14831752,2018,54781,5,4353.9024,20170205711200,NaN,NaN,...,NaN,NaN,99.99,1134.61,999.0,52.0,7010.0,33.9,51.4,q1
22004,199747,199747,14831760,2018,54783,5,3268.4282,20170205711400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4000.0,26.4,30.7,q1
22005,199755,199755,14831768,2018,54788,5,3398.0577,20170205712200,NaN,NaN,...,NaN,NaN,99.99,480.00,999.0,0.0,4000.0,26.4,30.7,q1
22006,199758,199758,14831771,2018,54789,5,3365.6145,20170505676000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1
22007,199763,199763,14831786,2018,54796,5,3487.2109,20180205533100,NaN,NaN,...,NaN,NaN,3.63,350.00,999.0,0.0,4110.0,20.3,28.1,q1
22008,199775,199775,14831802,2018,54806,5,2982.5319,20180405504500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1
22009,199780,199780,14831807,2018,54808,5,3357.6657,20170305707100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9600.0,28.4,30.4,q1
22010,199822,199822,14831877,2018,54863,5,3669.1699,20170305712500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1
22011,199831,199831,14831889,2018,54868,5,3503.7920,20180305538100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1
22012,199833,199833,14831898,2018,54875,5,3942.7924,20180405511100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,6530.0,35.5,43.0,q1
22013,199864,199864,14831955,2018,54902,5,5821.1694,20180205543300,NaN,NaN,...,NaN,NaN,99.99,300.00,999.0,0.0,4030.0,26.4,16.8,q1
22014,199866,199866,14831958,2018,54904,5,3410.2033,20170505687500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1
22015,199869,199869,14831961,2018,54904,5,3410.2033,20170505687500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,8965.0,28.4,31.7,q1
22016,199870,199870,14831962,2018,54905,5,3156.3941,20170305716600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1
22017,199877,199877,14831973,2018,54908,5,3104.2090,20170505688100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1
22018,199895,199895,14832000,2018,54921,5,5076.4210,20170505689100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9600.0,28.4,30.4,q1
22019,199921,199921,14832046,2018,54945,5,4268.1616,20170405705000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5610.0,29.2,34.9,q1
22020,199923,199923,14832048,2018,54946,5,3220.9441,20180305545800,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,840.0,50.3,48.4,q1
22021,199933,199933,14832073,2018,54959,5,3534.7323,20180205549800,NaN,NaN,...,NaN,NaN,99.99,1300.00,999.0,0.0,9130.0,32.1,30.4,q1
22022,199947,199947,14832089,2018,54966,5,4449.4833,20170505694800,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4250.0,22.5,28.6,q1
22023,199974,199974,14832122,2018,54989,5,4820.9959,20170505696900,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1
22024,199990,199990,14832158,2018,55010,5,3401.4693,20170305727800,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,8140.0,40.1,41.9,q1
22025,200002,200002,14832190,2018,55029,5,5399.0825,20180205556700,NaN,NaN,...,NaN,NaN,15.70,628.00,40.0,0.0,7750.0,28.4,34.0,q1
22026,200003,200003,14832191,2018,55029,5,5399.0825,20180205556700,NaN,NaN,...,NaN,NaN,15.50,620.00,40.0,0.0,7330.0,32.8,29.5,q1
22027,200036,200036,14832249,2018,55062,5,3322.7787,20170305732100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5610.0,29.2,34.9,q1
22028,200044,200044,14832259,2018,55068,5,4024.8577,20170505704100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1
22029,200049,200049,14832277,2018,55077,5,3399.8890,20180205560300,NaN,NaN,...,NaN,NaN,3.47,314.10,30.0,0.0,4110.0,20.3,28.1,q1
22030,200051,200051,14832289,2018,55083,5,4336.0718,20180205560800,NaN,NaN,...,NaN,NaN,20.00,500.00,999.0,0.0,9600.0,28.4,30.4,q1
22031,200052,200052,14832290,2018,55083,5,4336.0718,20180205560800,NaN,NaN,...,NaN,NaN,13.00,230.76,999.0,0.0,4220.0,16.1,22.3,q1
22032,200055,200055,14832293,2018,55085,5,3284.8946,20170205741300,NaN,NaN,...,NaN,NaN,25.25,2060.50,42.0,0.0,8965.0,28.4,31.7,q1

In [113]:
q2

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,quartile
0,0,0,4360,2010,2611,1,2633.6673,20091206245800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,6440.0,40.6,44.6,q2
1,1,1,4361,2010,2611,1,2633.6673,20091206245800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5700.0,44.5,46.1,q2
2,7,7,4367,2010,2613,1,3683.7540,20091200281200,NaN,NaN,...,NaN,0.0,99.99,711.53,999.0,52.0,5700.0,44.5,46.1,q2
3,37,37,4409,2010,2638,1,3096.3925,20081204010700,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4840.0,32.8,36.6,q2
4,43,43,4415,2010,2642,1,3039.3611,20081202906300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5600.0,35.5,42.3,q2
5,66,66,4495,2010,2695,1,2797.7074,20091201584200,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5620.0,35.5,27.4,q2
6,70,70,4499,2010,2699,1,2633.6673,20081206426500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5120.0,47.6,46.6,q2
7,76,76,4505,2010,2701,1,2635.4699,20091000264100,NaN,NaN,...,NaN,0.0,9.30,465.00,50.0,0.0,3600.0,36.3,41.7,q2
8,87,87,4516,2010,2705,1,3786.7243,20081005435500,NaN,NaN,...,NaN,0.0,99.99,2000.00,999.0,52.0,5810.0,44.9,41.2,q2
9,92,92,4521,2010,2706,1,2656.2591,20081005480300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5810.0,44.9,41.2,q2
10,114,114,4555,2010,2728,1,2819.8806,20090103898900,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5240.0,35.5,40.4,q2
11,121,121,4578,2010,2741,1,2934.0235,20081101345300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5550.0,42.3,47.0,q2
12,126,126,4622,2010,2774,1,2936.5530,20091206252200,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,8500.0,38.6,43.8,q2
13,132,132,4628,2010,2776,1,2903.7469,20100100277600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5520.0,33.5,34.8,q2
14,144,144,4640,2010,2781,1,3211.9624,20081102644300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5120.0,47.6,46.6,q2
15,158,158,4655,2010,2792,1,3502.5469,20091203090100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,8030.0,47.8,46.9,q2
16,162,162,4659,2010,2793,1,3888.9069,20091206022200,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5240.0,35.5,40.4,q2
17,189,189,4686,2010,2812,1,2901.7670,20091106323200,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,410.0,38.3,38.5,q2
18,206,206,11928,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5700.0,44.5,46.1,q2
19,237,237,11969,2010,6244,1,3394.4444,20091205015500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4210.0,45.3,36.1,q2
20,270,270,12030,2010,6271,1,2861.4301,20091001515500,NaN,NaN,...,NaN,0.0,99.99,669.00,999.0,0.0,6440.0,40.6,44.6,q2
21,292,292,12074,2010,6291,1,3083.6139,20091201593000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4700.0,50.3,44.2,q2
22,305,305,12087,2010,6297,1,3094.6308,20091103170300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4700.0,50.3,44.2,q2
23,322,322,12123,2010,6314,1,2880.4128,20081005357400,NaN,NaN,...,NaN,0.0,38.50,730.76,999.0,52.0,2440.0,41.3,29.3,q2
24,328,328,12129,2010,6318,1,3135.3102,20091106323300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,6440.0,40.6,44.6,q2
25,341,341,12166,2010,6332,1,3250.7058,20081204029400,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,3600.0,36.3,41.7,q2
26,345,345,12170,2010,6333,1,3819.5067,20091005633300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5240.0,35.5,40.4,q2
27,369,369,28858,2010,15199,1,4483.8606,20100101519900,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5620.0,35.5,27.4,q2
28,370,370,28859,2010,15200,1,2740.2533,20090106043800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,8220.0,28.4,37.0,q2
29,374,374,28863,2010,15201,1,3147.9523,20090106698800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5110.0,35.5,31.8,q2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17843,199731,199731,14831738,2018,54772,5,3358.0328,20170305703100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5240.0,35.5,40.4,q2
17844,199737,199737,14831744,2018,54775,5,4363.4123,20170505673600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4610.0,36.3,41.7,q2
17845,199739,199739,14831746,2018,54776,5,4468.2749,20170205710400,NaN,NaN,...,NaN,NaN,99.99,769.23,999.0,52.0,5700.0,44.5,46.1,q2
17846,199740,199740,14831747,2018,54776,5,4468.2749,20170205710400,NaN,NaN,...,NaN,NaN,99.99,1153.84,999.0,52.0,7340.0,32.8,39.9,q2
17847,199741,199741,14831748,2018,54777,5,3886.9433,20170405686500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,7340.0,32.8,39.9,q2
17848,199746,199746,14831759,2018,54783,5,3268.4282,20170205711400,NaN,NaN,...,NaN,NaN,12.50,500.00,40.0,0.0,8740.0,28.4,32.8,q2
17849,199750,199750,14831763,2018,54784,5,3353.9271,20180205531200,NaN,NaN,...,NaN,NaN,99.99,1000.00,999.0,0.0,5400.0,35.5,39.0,q2
17850,199753,199753,14831766,2018,54788,5,3398.0577,20170205712200,NaN,NaN,...,NaN,NaN,12.95,923.00,999.0,0.0,5700.0,44.5,46.1,q2
17851,199776,199776,14831803,2018,54807,5,3383.6768,20180305532300,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,8740.0,28.4,32.8,q2
17852,199786,199786,14831819,2018,54819,5,3410.2033,20170505679400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4700.0,50.3,44.2,q2
17853,199793,199793,14831832,2018,54828,5,3268.4282,20170205716400,NaN,NaN,...,NaN,NaN,30.00,540.00,18.0,0.0,2440.0,41.3,29.3,q2
17854,199849,199849,14831928,2018,54893,5,3177.4014,20180305540300,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5540.0,35.5,42.2,q2
17855,199867,199867,14831959,2018,54904,5,3410.2033,20170505687500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,8030.0,47.8,46.9,q2
17856,199868,199868,14831960,2018,54904,5,3410.2033,20170505687500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,3600.0,36.3,41.7,q2
17857,199871,199871,14831963,2018,54905,5,3156.3941,20170305716600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5620.0,35.5,27.4,q2
17858,199873,199873,14831965,2018,54905,5,3156.3941,20170305716600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5700.0,44.5,46.1,q2
17859,199896,199896,14832001,2018,54922,5,3317.3481,20180505492200,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,160.0,50.3,42.3,q2
17860,199911,199911,14832022,2018,54934,5,3678.0060,20180405517500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,3240.0,36.7,62.4,q2
17861,199915,199915,14832030,2018,54938,5,3277.2115,20170505691100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5120.0,47.6,46.6,q2
17862,199920,199920,14832045,2018,54945,5,4268.1616,20170405705000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5120.0,47.6,46.6,q2
17863,199925,199925,14832050,2018,54947,5,4435.7724,20180305545900,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4610.0,36.3,41.7,q2
17864,199935,199935,14832075,2018,54960,5,3468.9197,20170405707000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,6440.0,40.6,44.6,q2
17865,199961,199961,14832109,2018,54987,5,5755.4387,20180205553000,NaN,NaN,...,NaN,NaN,1.00,40.00,40.0,0.0,5240.0,35.5,40.4,q2
17866,199971,199971,14832119,2018,54989,5,4820.9959,20170505696900,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5540.0,35.5,42.2,q2
17867,199985,199985,14832153,2018,55007,5,4548.1886,20180205554800,NaN,NaN,...,NaN,NaN,25.44,1250.00,999.0,52.0,1060.0,50.6,73.7,q2
17868,199989,199989,14832157,2018,55009,5,3362.4266,20180305552600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,6355.0,49.2,51.0,q2
17869,200001,200001,14832189,2018,55027,5,3493.0976,20180305554000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,160.0,50.3,42.3,q2
17870,200006,200006,14832194,2018,55030,5,4009.8845,20180505503000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5400.0,35.5,39.0,q2
17871,200030,200030,14832238,2018,55057,5,3789.0902,20170405715200,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,7800.0,34.2,34.9,q2
17872,200046,200046,14832261,2018,55069,5,3184.1071,20180305557400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4700.0,50.3,44.2,q2

In [114]:
q3
# 14148 rows × 54 columns

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,quartile
0,5,5,4365,2010,2612,1,2633.6673,20091203069900,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5000.0,50.3,50.7,q3
1,9,9,4369,2010,2614,1,2695.4905,20081005569000,NaN,NaN,...,NaN,0.0,99.99,1384.00,999.0,0.0,2300.0,59.6,54.9,q3
2,10,10,4370,2010,2616,1,3250.7058,20081204857700,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,910.0,50.3,48.4,q3
3,11,11,4371,2010,2616,1,3250.7058,20081204857700,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,120.0,50.3,58.9,q3
4,28,28,4388,2010,2622,1,3947.8347,20091104313500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9750.0,17.5,27.6,q3
5,29,29,4389,2010,2623,1,2715.4737,20091104313600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5800.0,44.9,50.4,q3
6,35,35,4407,2010,2638,1,3096.3925,20081204010700,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2300.0,59.6,54.9,q3
7,38,38,4410,2010,2639,1,3039.3611,20081202906100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,9200.0,50.8,41.9,q3
8,39,39,4411,2010,2639,1,3039.3611,20081202906100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5000.0,50.3,50.7,q3
9,102,102,4531,2010,2710,1,2544.1069,20091006186600,NaN,NaN,...,NaN,3800.0,14.00,560.00,40.0,0.0,2000.0,50.6,56.7,q3
10,118,118,4559,2010,2731,1,3561.0132,20091004063000,NaN,NaN,...,NaN,0.0,99.99,845.00,999.0,0.0,310.0,50.3,41.0,q3
11,141,141,4637,2010,2779,1,3042.7988,20081005410200,NaN,NaN,...,NaN,0.0,99.99,1634.61,999.0,52.0,4700.0,50.3,44.2,q3
12,155,155,4652,2010,2790,1,3176.3751,20091203090000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,6230.0,39.9,38.9,q3
13,181,181,4678,2010,2808,1,2787.3050,20091002939000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5000.0,50.3,50.7,q3
14,216,216,11945,2010,6233,1,2807.6216,20081101331600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,6230.0,39.9,38.9,q3
15,223,223,11952,2010,6235,1,3181.1336,20091103155700,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,1010.0,50.6,60.5,q3
16,230,230,11962,2010,6240,1,3297.1629,20091002924700,NaN,NaN,...,NaN,0.0,99.99,993.69,999.0,0.0,2000.0,50.6,56.7,q3
17,240,240,11991,2010,6253,1,2956.7134,20091206249000,NaN,NaN,...,NaN,5860.0,99.99,9999.99,999.0,0.0,3820.0,47.8,59.7,q3
18,249,249,12000,2010,6258,1,3813.9774,20081005464300,NaN,NaN,...,NaN,2000.0,13.50,600.00,999.0,0.0,2000.0,50.6,56.7,q3
19,251,251,12002,2010,6260,1,3861.3800,20091002928300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,3250.0,59.7,62.3,q3
20,257,257,12008,2010,6261,1,2887.5143,20091104320600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4850.0,32.8,36.6,q3
21,271,271,12031,2010,6271,1,2861.4301,20091001515500,NaN,NaN,...,NaN,0.0,9.50,380.00,40.0,0.0,2010.0,52.4,51.5,q3
22,299,299,12081,2010,6294,1,3012.1940,20081204019000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,3820.0,47.8,59.7,q3
23,321,321,12122,2010,6314,1,2880.4128,20081005357400,NaN,NaN,...,NaN,0.0,37.50,750.00,20.0,0.0,2340.0,46.0,45.7,q3
24,335,335,12160,2010,6330,1,3124.3476,20081106113100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5160.0,49.5,43.3,q3
25,342,342,12167,2010,6332,1,3250.7058,20081204029400,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,4900.0,28.3,32.1,q3
26,383,383,28890,2010,15217,1,2770.8363,20081005471800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,310.0,50.3,41.0,q3
27,388,388,28895,2010,15219,1,3041.1266,20081103800400,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,5160.0,49.5,43.3,q3
28,419,419,28926,2010,15231,1,3038.8233,20090103891100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,3320.0,61.0,58.5,q3
29,420,420,28927,2010,15232,1,2998.6157,20090101452500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,540.0,46.9,47.3,q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14118,199605,199605,14831545,2018,54673,5,3101.5792,20170305692400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,540.0,46.9,47.3,q3
14119,199607,199607,14831550,2018,54676,5,4503.2797,20170205700800,NaN,NaN,...,NaN,NaN,10.00,360.00,36.0,0.0,310.0,50.3,41.0,q3
14120,199621,199621,14831573,2018,54685,5,3165.8435,20170305694300,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,540.0,46.9,47.3,q3
14121,199631,199631,14831588,2018,54698,5,3263.1435,20180305521200,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4010.0,50.3,30.7,q3
14122,199646,199646,14831603,2018,54702,5,4905.3550,20170205703300,NaN,NaN,...,NaN,NaN,99.99,1634.61,999.0,52.0,4700.0,50.3,44.2,q3
14123,199648,199648,14831609,2018,54704,5,4972.5775,20170205703700,NaN,NaN,...,NaN,NaN,12.98,519.20,40.0,0.0,2010.0,52.4,51.5,q3
14124,199657,199657,14831629,2018,54714,5,3101.5792,20170305698200,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5000.0,50.3,50.7,q3
14125,199658,199658,14831630,2018,54715,5,3825.1168,20180405496000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4850.0,32.8,36.6,q3
14126,199707,199707,14831699,2018,54749,5,3358.2910,20180505474900,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,9000.0,45.3,36.2,q3
14127,199718,199718,14831723,2018,54761,5,3134.5260,20170405685000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2340.0,46.0,45.7,q3
14128,199719,199719,14831724,2018,54761,5,3134.5260,20170405685000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2340.0,46.0,45.7,q3
14129,199734,199734,14831741,2018,54774,5,3747.0282,20170505673400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,120.0,50.3,58.9,q3
14130,199735,199735,14831742,2018,54774,5,3747.0282,20170505673400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2630.0,58.2,46.5,q3
14131,199742,199742,14831749,2018,54777,5,3886.9433,20170405686500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,1050.0,50.6,73.7,q3
14132,199745,199745,14831758,2018,54783,5,3268.4282,20170205711400,NaN,NaN,...,NaN,NaN,12.98,519.20,40.0,0.0,2630.0,58.2,46.5,q3
14133,199752,199752,14831765,2018,54788,5,3398.0577,20170205712200,NaN,NaN,...,NaN,NaN,99.99,1346.15,999.0,52.0,7700.0,45.3,47.0,q3
14134,199792,199792,14831831,2018,54828,5,3268.4282,20170205716400,NaN,NaN,...,NaN,NaN,99.99,576.92,999.0,52.0,5000.0,50.3,50.7,q3
14135,199805,199805,14831851,2018,54847,5,3678.4526,20170405693900,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4010.0,50.3,30.7,q3
14136,199834,199834,14831903,2018,54882,5,3270.5423,20180305539200,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,5000.0,50.3,50.7,q3
14137,199842,199842,14831921,2018,54892,5,3270.5423,20180305540100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4700.0,50.3,44.2,q3
14138,199876,199876,14831968,2018,54906,5,3313.7639,20170305716700,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,4010.0,50.3,30.7,q3
14139,199881,199881,14831983,2018,54913,5,3348.5871,20180405515500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2340.0,46.0,45.7,q3
14140,199891,199891,14831996,2018,54920,5,3220.4776,20180305543400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,120.0,50.3,58.9,q3
14141,199900,199900,14832005,2018,54924,5,3366.7196,20180505492400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2300.0,59.6,54.9,q3
14142,199913,199913,14832024,2018,54935,5,3273.9733,20180505493500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,8810.0,29.0,29.8,q3
14143,199914,199914,14832025,2018,54935,5,3273.9733,20180505493500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,1050.0,50.6,73.7,q3
14144,199919,199919,14832042,2018,54942,5,4229.0788,20180505494200,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2300.0,59.6,54.9,q3
14145,199942,199942,14832082,2018,54962,5,3370.9579,20180305548000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,120.0,50.3,58.9,q3
14146,199966,199966,14832114,2018,54988,5,3358.2910,20180505498800,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,1530.0,60.4,69.8,q3
14147,200045,200045,14832260,2018,55069,5,3184.1071,20180305557400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2010.0,52.4,51.5,q3

In [115]:
q4
# 20653 rows × 54 columns

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,EMCONTRB,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,quartile
0,8,8,4368,2010,2614,1,2695.4905,20081005569000,NaN,NaN,...,NaN,0.0,99.99,250.00,999.0,0.0,2320.0,59.6,66.4,q4
1,18,18,4378,2010,2620,1,2934.0235,20091100280900,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,1410.0,69.4,64.2,q4
2,26,26,4386,2010,2621,1,3094.6308,20091100281000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,110.0,50.3,56.5,q4
3,42,42,4414,2010,2641,1,3413.3112,20081206119500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,1720.0,68.8,73.3,q4
4,83,83,4512,2010,2704,1,3786.7243,20081005433500,NaN,NaN,...,NaN,0.0,99.99,2500.00,999.0,52.0,20.0,50.3,56.5,q4
5,106,106,4535,2010,2712,1,3041.1266,20091103164100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,1650.0,67.7,64.3,q4
6,115,115,4556,2010,2728,1,2819.8806,20090103898900,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,220.0,50.3,56.5,q4
7,129,129,4625,2010,2775,1,2998.6157,20100100277500,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,710.0,54.4,60.7,q4
8,148,148,4644,2010,2784,1,2910.5647,20091101751000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4
9,149,149,4645,2010,2784,1,2910.5647,20091101751000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4
10,156,156,4653,2010,2791,1,3502.5469,20091206022100,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,800.0,56.7,65.4,q4
11,164,164,4661,2010,2794,1,3396.0465,20100100279400,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4
12,165,165,4662,2010,2794,1,3396.0465,20100100279400,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2200.0,78.3,73.5,q4
13,191,191,4762,2010,2858,1,2956.7134,20091206022800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4
14,195,195,4766,2010,2866,1,4051.7611,20091006192700,NaN,NaN,...,NaN,0.0,99.99,884.61,999.0,52.0,2320.0,59.6,66.4,q4
15,196,196,4767,2010,2866,1,4051.7611,20091006192700,NaN,NaN,...,NaN,0.0,99.99,673.07,999.0,52.0,800.0,56.7,65.4,q4
16,210,210,11932,2010,6230,1,2808.9957,20091106314000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,1020.0,50.6,60.5,q4
17,214,214,11943,2010,6232,1,2910.5647,20081102626600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,10.0,50.3,70.5,q4
18,218,218,11947,2010,6234,1,3016.0369,20091101732000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,20.0,50.3,56.5,q4
19,232,232,11964,2010,6241,1,3926.2716,20091000261600,NaN,NaN,...,NaN,0.0,99.99,1100.00,999.0,0.0,430.0,50.3,56.5,q4
20,244,244,11995,2010,6255,1,2958.4310,20081101338600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,20.0,50.3,56.5,q4
21,252,252,12003,2010,6260,1,3861.3800,20091002928300,NaN,NaN,...,NaN,0.0,99.99,2884.61,999.0,52.0,3060.0,81.5,86.1,q4
22,262,262,12013,2010,6262,1,2843.7184,20091104320800,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2100.0,75.7,74.8,q4
23,280,280,12062,2010,6287,1,2856.7009,20091203084600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2320.0,59.6,66.4,q4
24,281,281,12063,2010,6287,1,2856.7009,20091203084600,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,30.0,50.0,56.9,q4
25,287,287,12069,2010,6289,1,2659.9043,20081005563500,NaN,NaN,...,NaN,0.0,99.99,1538.46,999.0,52.0,2320.0,59.6,66.4,q4
26,293,293,12075,2010,6291,1,3083.6139,20091201593000,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,1410.0,69.4,64.2,q4
27,327,327,12128,2010,6318,1,3135.3102,20091106323300,NaN,NaN,...,NaN,0.0,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4
28,348,348,12173,2010,6334,1,2695.4905,20091006881400,NaN,NaN,...,NaN,0.0,99.99,1153.84,999.0,52.0,230.0,59.6,63.7,q4
29,384,384,28891,2010,15217,1,2770.8363,20081005471800,NaN,NaN,...,NaN,0.0,99.99,547.00,999.0,0.0,3060.0,81.5,86.1,q4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20623,199785,199785,14831818,2018,54819,5,3410.2033,20170505679400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4
20624,199788,199788,14831825,2018,54825,5,3276.5854,20170405692500,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,350.0,61.5,69.2,q4
20625,199799,199799,14831838,2018,54830,5,4049.4631,20180305534600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,8760.0,61.0,55.9,q4
20626,199800,199800,14831839,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,1460.0,62.3,64.1,q4
20627,199801,199801,14831840,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4
20628,199809,199809,14831855,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,NaN,NaN,99.99,1442.30,999.0,52.0,800.0,56.7,65.4,q4
20629,199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,NaN,NaN,17.00,306.00,18.0,0.0,2310.0,59.6,64.1,q4
20630,199813,199813,14831859,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4
20631,199814,199814,14831860,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4
20632,199829,199829,14831887,2018,54868,5,3503.7920,20180305538100,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,130.0,56.0,53.9,q4
20633,199835,199835,14831906,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,10.0,50.3,70.5,q4
20634,199836,199836,14831907,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2320.0,59.6,66.4,q4
20635,199859,199859,14831942,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4
20636,199860,199860,14831943,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,3400.0,61.0,56.7,q4
20637,199863,199863,14831954,2018,54902,5,5821.1694,20180205543300,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,220.0,50.3,56.5,q4
20638,199892,199892,14831997,2018,54920,5,3220.4776,20180305543400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,30.0,50.0,56.9,q4
20639,199899,199899,14832004,2018,54924,5,3366.7196,20180505492400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,20.0,50.3,56.5,q4
20640,199936,199936,14832076,2018,54960,5,3468.9197,20170405707000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,1020.0,50.6,60.5,q4
20641,199944,199944,14832084,2018,54963,5,4228.5933,20180405520800,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,1300.0,70.5,73.2,q4
20642,199956,199956,14832103,2018,54979,5,3737.8669,20170405708700,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4
20643,199981,199981,14832149,2018,55006,5,2968.5652,20170305727400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4
20644,200000,200000,14832188,2018,55027,5,3493.0976,20180305554000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2550.0,46.0,45.7,q4
20645,200009,200009,14832197,2018,55032,5,3273.9733,20180505503200,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,110.0,50.3,56.5,q4
20646,200013,200013,14832217,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,800.0,56.7,65.4,q4
20647,200014,200014,14832218,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,220.0,50.3,56.5,q4
20648,200020,200020,14832228,2018,55051,5,3760.3273,20170305731000,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4
20649,200031,200031,14832244,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4
20650,200032,200032,14832245,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4
20651,200056,200056,14832294,2018,55086,5,3282.7580,20170505705700,NaN,NaN,...,NaN,NaN,99.99,9999.99,999.0,0.0,1460.0,62.3,64.1,q4
20652,200057,200057,14832299,2018,55092,5,2986.6895,20170205741900,NaN,NaN,...,NaN,NaN,99.99,1634.61,999.0,52.0,1410.0,69.4,64.2,q4

In [116]:
df = pd.concat([q1, q2, q3, q4])

In [117]:
df['counts']=[1]*len(df)
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,JTOCC,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,quartile,counts
0,25,25,4385,2010,2621,1,3094.6308,20091100281000,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1
1,32,32,4404,2010,2636,1,2989.8559,20081005418300,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1,1
2,41,41,4413,2010,2640,1,2987.2396,20081202906200,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1,1
3,47,47,4449,2010,2660,1,3334.6547,20081101335300,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4220.0,16.1,22.3,q1,1
4,51,51,4453,2010,2661,1,3016.0369,20081106102600,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1
5,68,68,4497,2010,2696,1,3320.4949,20091205016600,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9140.0,22.0,28.1,q1,1
6,73,73,4502,2010,2700,1,2658.6825,20091000264000,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,6420.0,29.8,33.9,q1,1
7,93,93,4522,2010,2707,1,2936.5530,20081205882700,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4000.0,26.4,30.7,q1,1
8,103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,...,0.0,25.00,1000.00,40.0,0.0,9100.0,32.4,32.1,q1,1
9,109,109,4550,2010,2725,1,3142.3940,20091203081900,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1,1
10,112,112,4553,2010,2727,1,2857.6916,20090101460800,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4510.0,35.0,36.1,q1,1
11,119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,...,0.0,7.25,234.50,999.0,0.0,4060.0,15.3,21.1,q1,1
12,120,120,4577,2010,2741,1,2934.0235,20081101345300,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1
13,123,123,4619,2010,2773,1,4579.0155,20091205725000,NaN,NaN,...,4030.0,99.99,9999.99,999.0,0.0,5860.0,35.5,33.9,q1,1
14,133,133,4629,2010,2776,1,2903.7469,20100100277600,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1
15,138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,...,0.0,7.25,253.75,35.0,0.0,4060.0,15.3,21.1,q1,1
16,184,184,4681,2010,2810,1,3663.0131,20091104332900,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4760.0,32.8,33.6,q1,1
17,202,202,4773,2010,2867,1,2388.6063,20091005633400,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,8800.0,28.4,25.1,q1,1
18,205,205,11927,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,8800.0,28.4,25.1,q1,1
19,207,207,11929,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1,1
20,215,215,11944,2010,6232,1,2910.5647,20081102626600,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,8610.0,35.0,40.2,q1,1
21,250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,...,0.0,32.00,1280.00,40.0,0.0,6200.0,50.3,53.2,q1,1
22,264,264,12024,2010,6267,1,2858.1973,20091201589500,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9100.0,32.4,32.1,q1,1
23,275,275,12035,2010,6272,1,2605.6782,20091001515700,NaN,NaN,...,0.0,99.99,692.00,999.0,0.0,4760.0,32.8,33.6,q1,1
24,277,277,12037,2010,6274,1,2640.2708,20091103166800,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4000.0,26.4,30.7,q1,1
25,288,288,12070,2010,6289,1,2659.9043,20081005563500,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,4250.0,22.5,28.6,q1,1
26,318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,...,0.0,12.00,480.00,40.0,0.0,4220.0,16.1,22.3,q1,1
27,360,360,28849,2010,15196,1,2797.7074,20091203070100,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,7260.0,21.6,43.5,q1,1
28,361,361,28850,2010,15197,1,2440.8800,20081102623300,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1
29,366,366,28855,2010,15198,1,3303.7087,20081206425500,NaN,NaN,...,0.0,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20623,199785,199785,14831818,2018,54819,5,3410.2033,20170505679400,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1
20624,199788,199788,14831825,2018,54825,5,3276.5854,20170405692500,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,350.0,61.5,69.2,q4,1
20625,199799,199799,14831838,2018,54830,5,4049.4631,20180305534600,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,8760.0,61.0,55.9,q4,1
20626,199800,199800,14831839,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,1460.0,62.3,64.1,q4,1
20627,199801,199801,14831840,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1
20628,199809,199809,14831855,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,NaN,99.99,1442.30,999.0,52.0,800.0,56.7,65.4,q4,1
20629,199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,NaN,17.00,306.00,18.0,0.0,2310.0,59.6,64.1,q4,1
20630,199813,199813,14831859,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1
20631,199814,199814,14831860,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1
20632,199829,199829,14831887,2018,54868,5,3503.7920,20180305538100,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,130.0,56.0,53.9,q4,1
20633,199835,199835,14831906,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,10.0,50.3,70.5,q4,1
20634,199836,199836,14831907,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,2320.0,59.6,66.4,q4,1
20635,199859,199859,14831942,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1
20636,199860,199860,14831943,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,3400.0,61.0,56.7,q4,1
20637,199863,199863,14831954,2018,54902,5,5821.1694,20180205543300,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,220.0,50.3,56.5,q4,1
20638,199892,199892,14831997,2018,54920,5,3220.4776,20180305543400,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,30.0,50.0,56.9,q4,1
20639,199899,199899,14832004,2018,54924,5,3366.7196,20180505492400,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,20.0,50.3,56.5,q4,1
20640,199936,199936,14832076,2018,54960,5,3468.9197,20170405707000,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,1020.0,50.6,60.5,q4,1
20641,199944,199944,14832084,2018,54963,5,4228.5933,20180405520800,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,1300.0,70.5,73.2,q4,1
20642,199956,199956,14832103,2018,54979,5,3737.8669,20170405708700,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1
20643,199981,199981,14832149,2018,55006,5,2968.5652,20170305727400,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1
20644,200000,200000,14832188,2018,55027,5,3493.0976,20180305554000,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,2550.0,46.0,45.7,q4,1
20645,200009,200009,14832197,2018,55032,5,3273.9733,20180505503200,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,110.0,50.3,56.5,q4,1
20646,200013,200013,14832217,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,800.0,56.7,65.4,q4,1
20647,200014,200014,14832218,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,220.0,50.3,56.5,q4,1
20648,200020,200020,14832228,2018,55051,5,3760.3273,20170305731000,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1
20649,200031,200031,14832244,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1
20650,200032,200032,14832245,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1
20651,200056,200056,14832294,2018,55086,5,3282.7580,20170505705700,NaN,NaN,...,NaN,99.99,9999.99,999.0,0.0,1460.0,62.3,64.1,q4,1
20652,200057,200057,14832299,2018,55092,5,2986.6895,20170205741900,NaN,NaN,...,NaN,99.99,1634.61,999.0,52.0,1410.0,69.4,64.2,q4,1

In [118]:
df.IND.value_counts().sort_index()

170       74
180       28
290        5
390        6
470       30
490        1
570      233
580       64
590       18
670       89
680       61
690        5
770     4939
1070      51
1080     155
1090      99
1170      66
1180     164
1190     195
1270     158
1280     167
1290      19
1370     117
1390      17
1480      55
1490       5
1570       1
1590      23
1670      11
1680     115
        ...
8570     112
8590     580
8660     348
8670      40
8680    4683
8690     100
8770     851
8780      47
8790      86
8870     139
8880      33
8970       2
8980     419
8990      18
9070      99
9080      36
9090      75
9160     433
9170     249
9180      39
9190      52
9290     165
9370     425
9380     222
9390      56
9470    1338
9480     383
9490      76
9570     237
9590     272
Name: IND, Length: 258, dtype: int64

In [119]:
#  merge industry
df.loc[(df['IND'] <= 291) & (df['IND'] >1), 'ind_merge'] = 1
df.loc[(df['IND'] >=370) & (df['IND'] < 491), 'ind_merge'] = 2
df.loc[(df['IND'] >=570) & (df['IND'] < 691), 'ind_merge'] = 3
df.loc[df['IND'] == 770, 'ind_merge'] = 4
df.loc[(df['IND'] >=1070) & (df['IND'] < 3991), 'ind_merge'] = 5
df.loc[(df['IND'] >=4070) & (df['IND'] < 4591), 'ind_merge'] = 6
df.loc[(df['IND'] >=4670) & (df['IND'] < 5791), 'ind_merge'] = 7
df.loc[(df['IND'] >=6070) & (df['IND'] < 6391), 'ind_merge'] = 8
df.loc[(df['IND'] >=6470) & (df['IND'] < 6791), 'ind_merge'] = 9
df.loc[(df['IND'] >=6870) & (df['IND'] < 7191), 'ind_merge'] = 10
df.loc[(df['IND'] >=7270) & (df['IND'] < 7791), 'ind_merge'] = 11
df.loc[(df['IND'] >=7860) & (df['IND'] < 8471), 'ind_merge'] = 12
df.loc[(df['IND'] >=8560) & (df['IND'] < 8691), 'ind_merge'] = 13
df.loc[(df['IND'] >=8770) & (df['IND'] < 9291), 'ind_merge'] = 14
df.loc[(df['IND'] >=9370) & (df['IND'] < 9591), 'ind_merge'] = 15
df.loc[(df['IND'] >=9670) & (df['IND'] < 9891), 'ind_merge'] = 16

In [120]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,HOURWAGE,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,quartile,counts,ind_merge
0,25,25,4385,2010,2621,1,3094.6308,20091100281000,NaN,NaN,...,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,5.0
1,32,32,4404,2010,2636,1,2989.8559,20081005418300,NaN,NaN,...,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1,1,7.0
2,41,41,4413,2010,2640,1,2987.2396,20081202906200,NaN,NaN,...,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1,1,13.0
3,47,47,4449,2010,2660,1,3334.6547,20081101335300,NaN,NaN,...,99.99,9999.99,999.0,0.0,4220.0,16.1,22.3,q1,1,13.0
4,51,51,4453,2010,2661,1,3016.0369,20081106102600,NaN,NaN,...,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,8.0
5,68,68,4497,2010,2696,1,3320.4949,20091205016600,NaN,NaN,...,99.99,9999.99,999.0,0.0,9140.0,22.0,28.1,q1,1,13.0
6,73,73,4502,2010,2700,1,2658.6825,20091000264000,NaN,NaN,...,99.99,9999.99,999.0,0.0,6420.0,29.8,33.9,q1,1,4.0
7,93,93,4522,2010,2707,1,2936.5530,20081205882700,NaN,NaN,...,99.99,9999.99,999.0,0.0,4000.0,26.4,30.7,q1,1,13.0
8,103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,...,25.00,1000.00,40.0,0.0,9100.0,32.4,32.1,q1,1,8.0
9,109,109,4550,2010,2725,1,3142.3940,20091203081900,NaN,NaN,...,99.99,9999.99,999.0,0.0,9620.0,17.5,24.0,q1,1,5.0
10,112,112,4553,2010,2727,1,2857.6916,20090101460800,NaN,NaN,...,99.99,9999.99,999.0,0.0,4510.0,35.0,36.1,q1,1,12.0
11,119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,...,7.25,234.50,999.0,0.0,4060.0,15.3,21.1,q1,1,13.0
12,120,120,4577,2010,2741,1,2934.0235,20081101345300,NaN,NaN,...,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,10.0
13,123,123,4619,2010,2773,1,4579.0155,20091205725000,NaN,NaN,...,99.99,9999.99,999.0,0.0,5860.0,35.5,33.9,q1,1,12.0
14,133,133,4629,2010,2776,1,2903.7469,20100100277600,NaN,NaN,...,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,8.0
15,138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,...,7.25,253.75,35.0,0.0,4060.0,15.3,21.1,q1,1,13.0
16,184,184,4681,2010,2810,1,3663.0131,20091104332900,NaN,NaN,...,99.99,9999.99,999.0,0.0,4760.0,32.8,33.6,q1,1,7.0
17,202,202,4773,2010,2867,1,2388.6063,20091005633400,NaN,NaN,...,99.99,9999.99,999.0,0.0,8800.0,28.4,25.1,q1,1,5.0
18,205,205,11927,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,99.99,9999.99,999.0,0.0,8800.0,28.4,25.1,q1,1,5.0
19,207,207,11929,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,99.99,9999.99,999.0,0.0,4720.0,30.9,29.5,q1,1,7.0
20,215,215,11944,2010,6232,1,2910.5647,20081102626600,NaN,NaN,...,99.99,9999.99,999.0,0.0,8610.0,35.0,40.2,q1,1,10.0
21,250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,...,32.00,1280.00,40.0,0.0,6200.0,50.3,53.2,q1,1,4.0
22,264,264,12024,2010,6267,1,2858.1973,20091201589500,NaN,NaN,...,99.99,9999.99,999.0,0.0,9100.0,32.4,32.1,q1,1,12.0
23,275,275,12035,2010,6272,1,2605.6782,20091001515700,NaN,NaN,...,99.99,692.00,999.0,0.0,4760.0,32.8,33.6,q1,1,7.0
24,277,277,12037,2010,6274,1,2640.2708,20091103166800,NaN,NaN,...,99.99,9999.99,999.0,0.0,4000.0,26.4,30.7,q1,1,13.0
25,288,288,12070,2010,6289,1,2659.9043,20081005563500,NaN,NaN,...,99.99,9999.99,999.0,0.0,4250.0,22.5,28.6,q1,1,11.0
26,318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,...,12.00,480.00,40.0,0.0,4220.0,16.1,22.3,q1,1,7.0
27,360,360,28849,2010,15196,1,2797.7074,20091203070100,NaN,NaN,...,99.99,9999.99,999.0,0.0,7260.0,21.6,43.5,q1,1,7.0
28,361,361,28850,2010,15197,1,2440.8800,20081102623300,NaN,NaN,...,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,8.0
29,366,366,28855,2010,15198,1,3303.7087,20081206425500,NaN,NaN,...,99.99,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20623,199785,199785,14831818,2018,54819,5,3410.2033,20170505679400,NaN,NaN,...,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0
20624,199788,199788,14831825,2018,54825,5,3276.5854,20170405692500,NaN,NaN,...,99.99,9999.99,999.0,0.0,350.0,61.5,69.2,q4,1,12.0
20625,199799,199799,14831838,2018,54830,5,4049.4631,20180305534600,NaN,NaN,...,99.99,9999.99,999.0,0.0,8760.0,61.0,55.9,q4,1,12.0
20626,199800,199800,14831839,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,99.99,9999.99,999.0,0.0,1460.0,62.3,64.1,q4,1,11.0
20627,199801,199801,14831840,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0
20628,199809,199809,14831855,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,99.99,1442.30,999.0,52.0,800.0,56.7,65.4,q4,1,10.0
20629,199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,17.00,306.00,18.0,0.0,2310.0,59.6,64.1,q4,1,12.0
20630,199813,199813,14831859,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1,12.0
20631,199814,199814,14831860,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1,6.0
20632,199829,199829,14831887,2018,54868,5,3503.7920,20180305538100,NaN,NaN,...,99.99,9999.99,999.0,0.0,130.0,56.0,53.9,q4,1,7.0
20633,199835,199835,14831906,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,99.99,9999.99,999.0,0.0,10.0,50.3,70.5,q4,1,14.0
20634,199836,199836,14831907,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,99.99,9999.99,999.0,0.0,2320.0,59.6,66.4,q4,1,12.0
20635,199859,199859,14831942,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1,12.0
20636,199860,199860,14831943,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,99.99,9999.99,999.0,0.0,3400.0,61.0,56.7,q4,1,12.0
20637,199863,199863,14831954,2018,54902,5,5821.1694,20180205543300,NaN,NaN,...,99.99,9999.99,999.0,0.0,220.0,50.3,56.5,q4,1,4.0
20638,199892,199892,14831997,2018,54920,5,3220.4776,20180305543400,NaN,NaN,...,99.99,9999.99,999.0,0.0,30.0,50.0,56.9,q4,1,5.0
20639,199899,199899,14832004,2018,54924,5,3366.7196,20180505492400,NaN,NaN,...,99.99,9999.99,999.0,0.0,20.0,50.3,56.5,q4,1,14.0
20640,199936,199936,14832076,2018,54960,5,3468.9197,20170405707000,NaN,NaN,...,99.99,9999.99,999.0,0.0,1020.0,50.6,60.5,q4,1,6.0
20641,199944,199944,14832084,2018,54963,5,4228.5933,20180405520800,NaN,NaN,...,99.99,9999.99,999.0,0.0,1300.0,70.5,73.2,q4,1,11.0
20642,199956,199956,14832103,2018,54979,5,3737.8669,20170405708700,NaN,NaN,...,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1,8.0
20643,199981,199981,14832149,2018,55006,5,2968.5652,20170305727400,NaN,NaN,...,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0
20644,200000,200000,14832188,2018,55027,5,3493.0976,20180305554000,NaN,NaN,...,99.99,9999.99,999.0,0.0,2550.0,46.0,45.7,q4,1,12.0
20645,200009,200009,14832197,2018,55032,5,3273.9733,20180505503200,NaN,NaN,...,99.99,9999.99,999.0,0.0,110.0,50.3,56.5,q4,1,11.0
20646,200013,200013,14832217,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,99.99,9999.99,999.0,0.0,800.0,56.7,65.4,q4,1,11.0
20647,200014,200014,14832218,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,99.99,9999.99,999.0,0.0,220.0,50.3,56.5,q4,1,4.0
20648,200020,200020,14832228,2018,55051,5,3760.3273,20170305731000,NaN,NaN,...,99.99,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0
20649,200031,200031,14832244,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,99.99,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1,6.0
20650,200032,200032,14832245,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,99.99,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1,12.0
20651,200056,200056,14832294,2018,55086,5,3282.7580,20170505705700,NaN,NaN,...,99.99,9999.99,999.0,0.0,1460.0,62.3,64.1,q4,1,5.0
20652,200057,200057,14832299,2018,55092,5,2986.6895,20170205741900,NaN,NaN,...,99.99,1634.61,999.0,52.0,1410.0,69.4,64.2,q4,1,5.0

In [121]:
df['INCTOT2']=df.INCTOT

In [122]:
df.loc[df['INCTOT']==0, 'INCTOT2']=np.nan

In [123]:
df.INCTOT2.value_counts().sort_index()

-9999.0       5
-9991.0       1
-9985.0       1
-9846.0       1
-2999.0       1
-2000.0       3
-500.0        1
-153.0        1
 1.0          3
 2.0          3
 5.0          1
 6.0          3
 11.0         1
 16.0         1
 20.0         1
 25.0         1
 32.0         1
 40.0         1
 43.0         2
 50.0         1
 70.0         1
 78.0         1
 81.0         1
 85.0         1
 97.0         1
 110.0        1
 175.0        1
 200.0        3
 242.0        1
 250.0        1
             ..
 418000.0     1
 419031.0     1
 419541.0     1
 423711.0     1
 430000.0     1
 433715.0     1
 456700.0     1
 474999.0     1
 500145.0     1
 500349.0     1
 500640.0     1
 501600.0     1
 504457.0     1
 505134.0     1
 506370.0     1
 506460.0     1
 524500.0     1
 550050.0     1
 703121.0     1
 780000.0     1
 801550.0     1
 910000.0     1
 1000240.0    2
 1036066.0    1
 1099999.0    1
 1100001.0    1
 1100499.0    1
 1126109.0    1
 1260002.0    1
 1260202.0    1
Name: INCTOT2, Length: 4391, dtype: int64

In [124]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,EARNWEEK,UHRSWORKORG,WKSWORKORG,OCC2010_y,PRESGL,PRENT,quartile,counts,ind_merge,INCTOT2
0,25,25,4385,2010,2621,1,3094.6308,20091100281000,NaN,NaN,...,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,5.0,NaN
1,32,32,4404,2010,2636,1,2989.8559,20081005418300,NaN,NaN,...,9999.99,999.0,0.0,9620.0,17.5,24.0,q1,1,7.0,NaN
2,41,41,4413,2010,2640,1,2987.2396,20081202906200,NaN,NaN,...,9999.99,999.0,0.0,4720.0,30.9,29.5,q1,1,13.0,NaN
3,47,47,4449,2010,2660,1,3334.6547,20081101335300,NaN,NaN,...,9999.99,999.0,0.0,4220.0,16.1,22.3,q1,1,13.0,NaN
4,51,51,4453,2010,2661,1,3016.0369,20081106102600,NaN,NaN,...,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,8.0,NaN
5,68,68,4497,2010,2696,1,3320.4949,20091205016600,NaN,NaN,...,9999.99,999.0,0.0,9140.0,22.0,28.1,q1,1,13.0,NaN
6,73,73,4502,2010,2700,1,2658.6825,20091000264000,NaN,NaN,...,9999.99,999.0,0.0,6420.0,29.8,33.9,q1,1,4.0,NaN
7,93,93,4522,2010,2707,1,2936.5530,20081205882700,NaN,NaN,...,9999.99,999.0,0.0,4000.0,26.4,30.7,q1,1,13.0,NaN
8,103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,...,1000.00,40.0,0.0,9100.0,32.4,32.1,q1,1,8.0,NaN
9,109,109,4550,2010,2725,1,3142.3940,20091203081900,NaN,NaN,...,9999.99,999.0,0.0,9620.0,17.5,24.0,q1,1,5.0,NaN
10,112,112,4553,2010,2727,1,2857.6916,20090101460800,NaN,NaN,...,9999.99,999.0,0.0,4510.0,35.0,36.1,q1,1,12.0,NaN
11,119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,...,234.50,999.0,0.0,4060.0,15.3,21.1,q1,1,13.0,NaN
12,120,120,4577,2010,2741,1,2934.0235,20081101345300,NaN,NaN,...,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,10.0,NaN
13,123,123,4619,2010,2773,1,4579.0155,20091205725000,NaN,NaN,...,9999.99,999.0,0.0,5860.0,35.5,33.9,q1,1,12.0,NaN
14,133,133,4629,2010,2776,1,2903.7469,20100100277600,NaN,NaN,...,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,8.0,NaN
15,138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,...,253.75,35.0,0.0,4060.0,15.3,21.1,q1,1,13.0,NaN
16,184,184,4681,2010,2810,1,3663.0131,20091104332900,NaN,NaN,...,9999.99,999.0,0.0,4760.0,32.8,33.6,q1,1,7.0,NaN
17,202,202,4773,2010,2867,1,2388.6063,20091005633400,NaN,NaN,...,9999.99,999.0,0.0,8800.0,28.4,25.1,q1,1,5.0,NaN
18,205,205,11927,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,9999.99,999.0,0.0,8800.0,28.4,25.1,q1,1,5.0,NaN
19,207,207,11929,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,9999.99,999.0,0.0,4720.0,30.9,29.5,q1,1,7.0,NaN
20,215,215,11944,2010,6232,1,2910.5647,20081102626600,NaN,NaN,...,9999.99,999.0,0.0,8610.0,35.0,40.2,q1,1,10.0,NaN
21,250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,...,1280.00,40.0,0.0,6200.0,50.3,53.2,q1,1,4.0,NaN
22,264,264,12024,2010,6267,1,2858.1973,20091201589500,NaN,NaN,...,9999.99,999.0,0.0,9100.0,32.4,32.1,q1,1,12.0,NaN
23,275,275,12035,2010,6272,1,2605.6782,20091001515700,NaN,NaN,...,692.00,999.0,0.0,4760.0,32.8,33.6,q1,1,7.0,NaN
24,277,277,12037,2010,6274,1,2640.2708,20091103166800,NaN,NaN,...,9999.99,999.0,0.0,4000.0,26.4,30.7,q1,1,13.0,NaN
25,288,288,12070,2010,6289,1,2659.9043,20081005563500,NaN,NaN,...,9999.99,999.0,0.0,4250.0,22.5,28.6,q1,1,11.0,NaN
26,318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,...,480.00,40.0,0.0,4220.0,16.1,22.3,q1,1,7.0,NaN
27,360,360,28849,2010,15196,1,2797.7074,20091203070100,NaN,NaN,...,9999.99,999.0,0.0,7260.0,21.6,43.5,q1,1,7.0,NaN
28,361,361,28850,2010,15197,1,2440.8800,20081102623300,NaN,NaN,...,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,8.0,NaN
29,366,366,28855,2010,15198,1,3303.7087,20081206425500,NaN,NaN,...,9999.99,999.0,0.0,9130.0,32.1,30.4,q1,1,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20623,199785,199785,14831818,2018,54819,5,3410.2033,20170505679400,NaN,NaN,...,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0,NaN
20624,199788,199788,14831825,2018,54825,5,3276.5854,20170405692500,NaN,NaN,...,9999.99,999.0,0.0,350.0,61.5,69.2,q4,1,12.0,NaN
20625,199799,199799,14831838,2018,54830,5,4049.4631,20180305534600,NaN,NaN,...,9999.99,999.0,0.0,8760.0,61.0,55.9,q4,1,12.0,NaN
20626,199800,199800,14831839,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,9999.99,999.0,0.0,1460.0,62.3,64.1,q4,1,11.0,NaN
20627,199801,199801,14831840,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0,NaN
20628,199809,199809,14831855,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,1442.30,999.0,52.0,800.0,56.7,65.4,q4,1,10.0,NaN
20629,199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,306.00,18.0,0.0,2310.0,59.6,64.1,q4,1,12.0,NaN
20630,199813,199813,14831859,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1,12.0,NaN
20631,199814,199814,14831860,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1,6.0,NaN
20632,199829,199829,14831887,2018,54868,5,3503.7920,20180305538100,NaN,NaN,...,9999.99,999.0,0.0,130.0,56.0,53.9,q4,1,7.0,NaN
20633,199835,199835,14831906,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,9999.99,999.0,0.0,10.0,50.3,70.5,q4,1,14.0,NaN
20634,199836,199836,14831907,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,9999.99,999.0,0.0,2320.0,59.6,66.4,q4,1,12.0,NaN
20635,199859,199859,14831942,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1,12.0,NaN
20636,199860,199860,14831943,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,9999.99,999.0,0.0,3400.0,61.0,56.7,q4,1,12.0,NaN
20637,199863,199863,14831954,2018,54902,5,5821.1694,20180205543300,NaN,NaN,...,9999.99,999.0,0.0,220.0,50.3,56.5,q4,1,4.0,NaN
20638,199892,199892,14831997,2018,54920,5,3220.4776,20180305543400,NaN,NaN,...,9999.99,999.0,0.0,30.0,50.0,56.9,q4,1,5.0,NaN
20639,199899,199899,14832004,2018,54924,5,3366.7196,20180505492400,NaN,NaN,...,9999.99,999.0,0.0,20.0,50.3,56.5,q4,1,14.0,NaN
20640,199936,199936,14832076,2018,54960,5,3468.9197,20170405707000,NaN,NaN,...,9999.99,999.0,0.0,1020.0,50.6,60.5,q4,1,6.0,NaN
20641,199944,199944,14832084,2018,54963,5,4228.5933,20180405520800,NaN,NaN,...,9999.99,999.0,0.0,1300.0,70.5,73.2,q4,1,11.0,NaN
20642,199956,199956,14832103,2018,54979,5,3737.8669,20170405708700,NaN,NaN,...,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1,8.0,NaN
20643,199981,199981,14832149,2018,55006,5,2968.5652,20170305727400,NaN,NaN,...,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0,NaN
20644,200000,200000,14832188,2018,55027,5,3493.0976,20180305554000,NaN,NaN,...,9999.99,999.0,0.0,2550.0,46.0,45.7,q4,1,12.0,NaN
20645,200009,200009,14832197,2018,55032,5,3273.9733,20180505503200,NaN,NaN,...,9999.99,999.0,0.0,110.0,50.3,56.5,q4,1,11.0,NaN
20646,200013,200013,14832217,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,9999.99,999.0,0.0,800.0,56.7,65.4,q4,1,11.0,NaN
20647,200014,200014,14832218,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,9999.99,999.0,0.0,220.0,50.3,56.5,q4,1,4.0,NaN
20648,200020,200020,14832228,2018,55051,5,3760.3273,20170305731000,NaN,NaN,...,9999.99,999.0,0.0,3130.0,61.5,66.5,q4,1,12.0,NaN
20649,200031,200031,14832244,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,9999.99,999.0,0.0,430.0,50.3,56.5,q4,1,6.0,NaN
20650,200032,200032,14832245,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,9999.99,999.0,0.0,2310.0,59.6,64.1,q4,1,12.0,NaN
20651,200056,200056,14832294,2018,55086,5,3282.7580,20170505705700,NaN,NaN,...,9999.99,999.0,0.0,1460.0,62.3,64.1,q4,1,5.0,NaN
20652,200057,200057,14832299,2018,55092,5,2986.6895,20170205741900,NaN,NaN,...,1634.61,999.0,52.0,1410.0,69.4,64.2,q4,1,5.0,NaN

In [125]:
df['EARNWEEK2'] = df['EARNWEEK']

In [126]:
df.loc[df['EARNWEEK'].isin([0, 9999.99]), 'EARNWEEK2']=np.nan

In [127]:
df.EARNWEEK2.value_counts().sort_index()

0.01         2
0.10         1
0.48         1
0.50         1
1.00         4
1.15         1
1.19         1
1.53         2
2.00         1
2.40         1
2.88         1
3.36         1
5.76         1
7.25         1
11.60        1
12.00        2
12.50        1
19.21        1
20.00        1
20.32        1
22.00        1
22.30        1
23.07        1
24.00        3
25.00        2
25.47        1
27.00        1
28.00        7
29.00        1
30.40        1
          ...
2653.84      2
2654.00      1
2673.07      3
2676.92      1
2692.00      6
2692.30     22
2700.00      3
2708.33      1
2711.00      1
2711.53      2
2720.00      1
2730.76      1
2750.00     10
2769.00      3
2769.23      5
2788.00      2
2788.46      7
2800.00      3
2807.69      1
2815.00      3
2815.38      1
2826.00      1
2826.92      1
2846.00      3
2846.15      2
2850.00      2
2865.38      1
2884.00     27
2884.61    487
2885.00     52
Name: EARNWEEK2, Length: 2595, dtype: int64

In [128]:
df['UHRSWORKT2']= df['UHRSWORKT']

In [129]:
df.UHRSWORKT2.value_counts().sort_index()

0        48
1        14
2        31
3        32
4       101
5       108
6       106
7        31
8       264
9        44
10      453
11       14
12      290
13       35
14       51
15      563
16      349
17       42
18      161
19       22
20     2103
21       79
22       96
23       57
24      589
25     1030
26       77
27       74
28      229
29       43
       ...
72       46
73        9
74        3
75       89
76       18
77        3
78       17
79        3
80      262
82        7
83        1
84       22
85       16
86        4
87        2
88        2
89        3
90       28
92        2
93        2
95        2
96        1
99       19
100      16
104       1
112       1
120       2
140       2
997    4618
999    4961
Name: UHRSWORKT2, Length: 102, dtype: int64

In [130]:
df.loc[df['UHRSWORKT'].isin([997,999,0]), 'UHRSWORKT2']=np.nan

In [131]:
df.UHRSWORKT2.value_counts().sort_index()

1.0        14
2.0        31
3.0        32
4.0       101
5.0       108
6.0       106
7.0        31
8.0       264
9.0        44
10.0      453
11.0       14
12.0      290
13.0       35
14.0       51
15.0      563
16.0      349
17.0       42
18.0      161
19.0       22
20.0     2103
21.0       79
22.0       96
23.0       57
24.0      589
25.0     1030
26.0       77
27.0       74
28.0      229
29.0       43
30.0     1666
         ...
70.0      468
71.0        2
72.0       46
73.0        9
74.0        3
75.0       89
76.0       18
77.0        3
78.0       17
79.0        3
80.0      262
82.0        7
83.0        1
84.0       22
85.0       16
86.0        4
87.0        2
88.0        2
89.0        3
90.0       28
92.0        2
93.0        2
95.0        2
96.0        1
99.0       19
100.0      16
104.0       1
112.0       1
120.0       2
140.0       2
Name: UHRSWORKT2, Length: 99, dtype: int64

In [132]:
df['Cal_hourly_wage']= df.EARNWEEK2/df.UHRSWORKT2

In [133]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,YEAR,SERIAL,MONTH,HWTFINL,CPSID,ASECFLAG,HFLAG,...,OCC2010_y,PRESGL,PRENT,quartile,counts,ind_merge,INCTOT2,EARNWEEK2,UHRSWORKT2,Cal_hourly_wage
0,25,25,4385,2010,2621,1,3094.6308,20091100281000,NaN,NaN,...,9130.0,32.1,30.4,q1,1,5.0,NaN,NaN,NaN,NaN
1,32,32,4404,2010,2636,1,2989.8559,20081005418300,NaN,NaN,...,9620.0,17.5,24.0,q1,1,7.0,NaN,NaN,NaN,NaN
2,41,41,4413,2010,2640,1,2987.2396,20081202906200,NaN,NaN,...,4720.0,30.9,29.5,q1,1,13.0,NaN,NaN,55.0,NaN
3,47,47,4449,2010,2660,1,3334.6547,20081101335300,NaN,NaN,...,4220.0,16.1,22.3,q1,1,13.0,NaN,NaN,NaN,NaN
4,51,51,4453,2010,2661,1,3016.0369,20081106102600,NaN,NaN,...,9130.0,32.1,30.4,q1,1,8.0,NaN,NaN,50.0,NaN
5,68,68,4497,2010,2696,1,3320.4949,20091205016600,NaN,NaN,...,9140.0,22.0,28.1,q1,1,13.0,NaN,NaN,35.0,NaN
6,73,73,4502,2010,2700,1,2658.6825,20091000264000,NaN,NaN,...,6420.0,29.8,33.9,q1,1,4.0,NaN,NaN,NaN,NaN
7,93,93,4522,2010,2707,1,2936.5530,20081205882700,NaN,NaN,...,4000.0,26.4,30.7,q1,1,13.0,NaN,NaN,NaN,NaN
8,103,103,4532,2010,2710,1,2544.1069,20091006186600,NaN,NaN,...,9100.0,32.4,32.1,q1,1,8.0,NaN,1000.00,40.0,25.000000
9,109,109,4550,2010,2725,1,3142.3940,20091203081900,NaN,NaN,...,9620.0,17.5,24.0,q1,1,5.0,NaN,NaN,40.0,NaN
10,112,112,4553,2010,2727,1,2857.6916,20090101460800,NaN,NaN,...,4510.0,35.0,36.1,q1,1,12.0,NaN,NaN,24.0,NaN
11,119,119,4560,2010,2731,1,3561.0132,20091004063000,NaN,NaN,...,4060.0,15.3,21.1,q1,1,13.0,NaN,234.50,36.0,6.513889
12,120,120,4577,2010,2741,1,2934.0235,20081101345300,NaN,NaN,...,9130.0,32.1,30.4,q1,1,10.0,NaN,NaN,56.0,NaN
13,123,123,4619,2010,2773,1,4579.0155,20091205725000,NaN,NaN,...,5860.0,35.5,33.9,q1,1,12.0,NaN,NaN,20.0,NaN
14,133,133,4629,2010,2776,1,2903.7469,20100100277600,NaN,NaN,...,9130.0,32.1,30.4,q1,1,8.0,NaN,NaN,30.0,NaN
15,138,138,4634,2010,2777,1,2906.0264,20081005433700,NaN,NaN,...,4060.0,15.3,21.1,q1,1,13.0,NaN,253.75,35.0,7.250000
16,184,184,4681,2010,2810,1,3663.0131,20091104332900,NaN,NaN,...,4760.0,32.8,33.6,q1,1,7.0,NaN,NaN,40.0,NaN
17,202,202,4773,2010,2867,1,2388.6063,20091005633400,NaN,NaN,...,8800.0,28.4,25.1,q1,1,5.0,NaN,NaN,NaN,NaN
18,205,205,11927,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,8800.0,28.4,25.1,q1,1,5.0,NaN,NaN,NaN,NaN
19,207,207,11929,2010,6229,1,2081.4572,20081204857800,NaN,NaN,...,4720.0,30.9,29.5,q1,1,7.0,NaN,NaN,12.0,NaN
20,215,215,11944,2010,6232,1,2910.5647,20081102626600,NaN,NaN,...,8610.0,35.0,40.2,q1,1,10.0,NaN,NaN,40.0,NaN
21,250,250,12001,2010,6259,1,3042.7988,20081005434300,NaN,NaN,...,6200.0,50.3,53.2,q1,1,4.0,NaN,1280.00,40.0,32.000000
22,264,264,12024,2010,6267,1,2858.1973,20091201589500,NaN,NaN,...,9100.0,32.4,32.1,q1,1,12.0,NaN,NaN,59.0,NaN
23,275,275,12035,2010,6272,1,2605.6782,20091001515700,NaN,NaN,...,4760.0,32.8,33.6,q1,1,7.0,NaN,692.00,45.0,15.377778
24,277,277,12037,2010,6274,1,2640.2708,20091103166800,NaN,NaN,...,4000.0,26.4,30.7,q1,1,13.0,NaN,NaN,36.0,NaN
25,288,288,12070,2010,6289,1,2659.9043,20081005563500,NaN,NaN,...,4250.0,22.5,28.6,q1,1,11.0,NaN,NaN,50.0,NaN
26,318,318,12119,2010,6313,1,3908.7225,20081005381500,NaN,NaN,...,4220.0,16.1,22.3,q1,1,7.0,NaN,480.00,40.0,12.000000
27,360,360,28849,2010,15196,1,2797.7074,20091203070100,NaN,NaN,...,7260.0,21.6,43.5,q1,1,7.0,NaN,NaN,39.0,NaN
28,361,361,28850,2010,15197,1,2440.8800,20081102623300,NaN,NaN,...,9130.0,32.1,30.4,q1,1,8.0,NaN,NaN,60.0,NaN
29,366,366,28855,2010,15198,1,3303.7087,20081206425500,NaN,NaN,...,9130.0,32.1,30.4,q1,1,11.0,NaN,NaN,40.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20623,199785,199785,14831818,2018,54819,5,3410.2033,20170505679400,NaN,NaN,...,3130.0,61.5,66.5,q4,1,12.0,NaN,NaN,12.0,NaN
20624,199788,199788,14831825,2018,54825,5,3276.5854,20170405692500,NaN,NaN,...,350.0,61.5,69.2,q4,1,12.0,NaN,NaN,36.0,NaN
20625,199799,199799,14831838,2018,54830,5,4049.4631,20180305534600,NaN,NaN,...,8760.0,61.0,55.9,q4,1,12.0,NaN,NaN,60.0,NaN
20626,199800,199800,14831839,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,1460.0,62.3,64.1,q4,1,11.0,NaN,NaN,40.0,NaN
20627,199801,199801,14831840,2018,54831,5,3448.0826,20170305709600,NaN,NaN,...,3130.0,61.5,66.5,q4,1,12.0,NaN,NaN,40.0,NaN
20628,199809,199809,14831855,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,800.0,56.7,65.4,q4,1,10.0,NaN,1442.30,40.0,36.057500
20629,199810,199810,14831856,2018,54850,5,4442.4016,20170205718000,NaN,NaN,...,2310.0,59.6,64.1,q4,1,12.0,NaN,306.00,18.0,17.000000
20630,199813,199813,14831859,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,2310.0,59.6,64.1,q4,1,12.0,NaN,NaN,40.0,NaN
20631,199814,199814,14831860,2018,54852,5,2943.5349,20180405509000,NaN,NaN,...,430.0,50.3,56.5,q4,1,6.0,NaN,NaN,55.0,NaN
20632,199829,199829,14831887,2018,54868,5,3503.7920,20180305538100,NaN,NaN,...,130.0,56.0,53.9,q4,1,7.0,NaN,NaN,37.0,NaN
20633,199835,199835,14831906,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,10.0,50.3,70.5,q4,1,14.0,NaN,NaN,50.0,NaN
20634,199836,199836,14831907,2018,54884,5,3368.3137,20170305714600,NaN,NaN,...,2320.0,59.6,66.4,q4,1,12.0,NaN,NaN,45.0,NaN
20635,199859,199859,14831942,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,2310.0,59.6,64.1,q4,1,12.0,NaN,NaN,32.0,NaN
20636,199860,199860,14831943,2018,54899,5,3226.3291,20180305540900,NaN,NaN,...,3400.0,61.0,56.7,q4,1,12.0,NaN,NaN,40.0,NaN
20637,199863,199863,14831954,2018,54902,5,5821.1694,20180205543300,NaN,NaN,...,220.0,50.3,56.5,q4,1,4.0,NaN,NaN,40.0,NaN
20638,199892,199892,14831997,2018,54920,5,3220.4776,20180305543400,NaN,NaN,...,30.0,50.0,56.9,q4,1,5.0,NaN,NaN,40.0,NaN
20639,199899,199899,14832004,2018,54924,5,3366.7196,20180505492400,NaN,NaN,...,20.0,50.3,56.5,q4,1,14.0,NaN,NaN,45.0,NaN
20640,199936,199936,14832076,2018,54960,5,3468.9197,20170405707000,NaN,NaN,...,1020.0,50.6,60.5,q4,1,6.0,NaN,NaN,40.0,NaN
20641,199944,199944,14832084,2018,54963,5,4228.5933,20180405520800,NaN,NaN,...,1300.0,70.5,73.2,q4,1,11.0,NaN,NaN,40.0,NaN
20642,199956,199956,14832103,2018,54979,5,3737.8669,20170405708700,NaN,NaN,...,430.0,50.3,56.5,q4,1,8.0,NaN,NaN,50.0,NaN
20643,199981,199981,14832149,2018,55006,5,2968.5652,20170305727400,NaN,NaN,...,3130.0,61.5,66.5,q4,1,12.0,NaN,NaN,40.0,NaN
20644,200000,200000,14832188,2018,55027,5,3493.0976,20180305554000,NaN,NaN,...,2550.0,46.0,45.7,q4,1,12.0,NaN,NaN,40.0,NaN
20645,200009,200009,14832197,2018,55032,5,3273.9733,20180505503200,NaN,NaN,...,110.0,50.3,56.5,q4,1,11.0,NaN,NaN,50.0,NaN
20646,200013,200013,14832217,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,800.0,56.7,65.4,q4,1,11.0,NaN,NaN,NaN,NaN
20647,200014,200014,14832218,2018,55044,5,4939.6006,20170605694400,NaN,NaN,...,220.0,50.3,56.5,q4,1,4.0,NaN,NaN,NaN,NaN
20648,200020,200020,14832228,2018,55051,5,3760.3273,20170305731000,NaN,NaN,...,3130.0,61.5,66.5,q4,1,12.0,NaN,NaN,40.0,NaN
20649,200031,200031,14832244,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,430.0,50.3,56.5,q4,1,6.0,NaN,NaN,45.0,NaN
20650,200032,200032,14832245,2018,55061,5,3303.3188,20180405529800,NaN,NaN,...,2310.0,59.6,64.1,q4,1,12.0,NaN,NaN,50.0,NaN
20651,200056,200056,14832294,2018,55086,5,3282.7580,20170505705700,NaN,NaN,...,1460.0,62.3,64.1,q4,1,5.0,NaN,NaN,45.0,NaN
20652,200057,200057,14832299,2018,55092,5,2986.6895,20170205741900,NaN,NaN,...,1410.0,69.4,64.2,q4,1,5.0,NaN,1634.61,40.0,40.865250

In [135]:
out1 = df.groupby(['quartile', 'ind_merge'])['INCTOT2','Cal_hourly_wage'].mean()
out2 = df.groupby(['quartile', 'ind_merge'])['counts'].sum()

In [136]:
out1

                          INCTOT2  Cal_hourly_wage
quartile ind_merge
q1       1.0         34079.333333        12.879762
         2.0         60000.000000        26.000000
         3.0         54308.750000        20.619759
         4.0         44806.024691        20.782586
         5.0         36094.981884        17.472677
         6.0         36121.271930        16.580828
         7.0         25432.539906        13.508891
         8.0         46723.233161        17.452228
         9.0         24496.000000        21.294025
         10.0        47138.538462        20.710452
         11.0        33488.964126        16.304635
         12.0        27449.475676        15.133878
         13.0        19644.162963        11.450259
         14.0        39239.981132        15.908522
         15.0        45318.438356        18.978984
q2       1.0         24004.000000        13.533241
         2.0         56605.000000        14.000000
         3.0         43796.529412        22.923174
         4.0         43816.227941        23.335276
         5.0         47040.370558        21.666836
         6.0         43239.480769        19.276851
         7.0         37826.937107        17.326137
         8.0         47872.928571        20.777460
         9.0         48469.823529        22.325771
         10.0        50662.541401        18.926015
         11.0        48091.666667        22.514483
         12.0        32172.144898        16.592317
         13.0        30605.000000        16.583605
         14.0        33264.118280        18.388714
         15.0        42752.848485        21.306680
q3       1.0         15443.000000         7.869167
         2.0                  NaN              NaN
         3.0         79694.833333        35.712692
         4.0         41242.514706        23.263082
         5.0         69888.461078        27.927022
         6.0         77821.673684        27.865137
         7.0         45627.329114        19.546888
         8.0         58301.566667        28.115506
         9.0         59053.030303        24.537364
         10.0        73643.526786        28.046504
         11.0        66124.251429        28.987966
         12.0        45647.601190        22.975503
         13.0        39971.008696        19.829995
         14.0        64657.800000        23.056334
         15.0        70218.619469        25.944830
q4       1.0                  NaN        20.000000
         2.0        398779.750000        38.999920
         3.0        141845.111111        37.301561
         4.0         92904.117021        32.930069
         5.0        117257.489270        39.543773
         6.0        134060.173913        37.078617
         7.0         67196.600000        27.454776
         8.0         69615.423077        29.405622
         9.0         97945.854545        32.677710
         10.0       115180.580000        39.157089
         11.0       111986.012658        36.369547
         12.0        73128.654693        30.090511
         13.0        49880.945455        21.457082
         14.0        63861.208333        27.931977
         15.0        78713.698795        33.811740

In [138]:
out2 = pd.DataFrame(out2)
out2

                    counts
quartile ind_merge
q1       1.0            64
         2.0             6
         3.0            73
         4.0          1671
         5.0          2835
         6.0           855
         7.0          4307
         8.0          1997
         9.0            85
         10.0          546
         11.0         2234
         12.0         1560
         13.0         4159
         14.0         1058
         15.0          583
q2       1.0            25
         2.0             4
         3.0           153
         4.0          1487
         5.0          1915
         6.0           486
         7.0          3110
         8.0           872
         9.0           396
         10.0         1464
         11.0         1488
         12.0         4755
         13.0          317
         14.0          806
         15.0          595
q3       1.0            14
         2.0             2
         3.0           126
         4.0           798
         5.0          1644
         6.0           872
         7.0           647
         8.0           239
         9.0           283
         10.0         2002
         11.0         1645
         12.0         3236
         13.0         1152
         14.0          487
         15.0         1001
q4       1.0             4
         2.0            25
         3.0           118
         4.0           983
         5.0          2320
         6.0           365
         7.0           593
         8.0           275
         9.0           483
         10.0         1474
         11.0         3886
         12.0         8371
         13.0          534
         14.0          392
         15.0          830

In [139]:
out1 = out1.reset_index()
out1

   quartile  ind_merge        INCTOT2  Cal_hourly_wage
0        q1        1.0   34079.333333        12.879762
1        q1        2.0   60000.000000        26.000000
2        q1        3.0   54308.750000        20.619759
3        q1        4.0   44806.024691        20.782586
4        q1        5.0   36094.981884        17.472677
5        q1        6.0   36121.271930        16.580828
6        q1        7.0   25432.539906        13.508891
7        q1        8.0   46723.233161        17.452228
8        q1        9.0   24496.000000        21.294025
9        q1       10.0   47138.538462        20.710452
10       q1       11.0   33488.964126        16.304635
11       q1       12.0   27449.475676        15.133878
12       q1       13.0   19644.162963        11.450259
13       q1       14.0   39239.981132        15.908522
14       q1       15.0   45318.438356        18.978984
15       q2        1.0   24004.000000        13.533241
16       q2        2.0   56605.000000        14.000000
17       q2        3.0   43796.529412        22.923174
18       q2        4.0   43816.227941        23.335276
19       q2        5.0   47040.370558        21.666836
20       q2        6.0   43239.480769        19.276851
21       q2        7.0   37826.937107        17.326137
22       q2        8.0   47872.928571        20.777460
23       q2        9.0   48469.823529        22.325771
24       q2       10.0   50662.541401        18.926015
25       q2       11.0   48091.666667        22.514483
26       q2       12.0   32172.144898        16.592317
27       q2       13.0   30605.000000        16.583605
28       q2       14.0   33264.118280        18.388714
29       q2       15.0   42752.848485        21.306680
30       q3        1.0   15443.000000         7.869167
31       q3        2.0            NaN              NaN
32       q3        3.0   79694.833333        35.712692
33       q3        4.0   41242.514706        23.263082
34       q3        5.0   69888.461078        27.927022
35       q3        6.0   77821.673684        27.865137
36       q3        7.0   45627.329114        19.546888
37       q3        8.0   58301.566667        28.115506
38       q3        9.0   59053.030303        24.537364
39       q3       10.0   73643.526786        28.046504
40       q3       11.0   66124.251429        28.987966
41       q3       12.0   45647.601190        22.975503
42       q3       13.0   39971.008696        19.829995
43       q3       14.0   64657.800000        23.056334
44       q3       15.0   70218.619469        25.944830
45       q4        1.0            NaN        20.000000
46       q4        2.0  398779.750000        38.999920
47       q4        3.0  141845.111111        37.301561
48       q4        4.0   92904.117021        32.930069
49       q4        5.0  117257.489270        39.543773
50       q4        6.0  134060.173913        37.078617
51       q4        7.0   67196.600000        27.454776
52       q4        8.0   69615.423077        29.405622
53       q4        9.0   97945.854545        32.677710
54       q4       10.0  115180.580000        39.157089
55       q4       11.0  111986.012658        36.369547
56       q4       12.0   73128.654693        30.090511
57       q4       13.0   49880.945455        21.457082
58       q4       14.0   63861.208333        27.931977
59       q4       15.0   78713.698795        33.811740

In [140]:
out2 = out2.reset_index()
out2

   quartile  ind_merge  counts
0        q1        1.0      64
1        q1        2.0       6
2        q1        3.0      73
3        q1        4.0    1671
4        q1        5.0    2835
5        q1        6.0     855
6        q1        7.0    4307
7        q1        8.0    1997
8        q1        9.0      85
9        q1       10.0     546
10       q1       11.0    2234
11       q1       12.0    1560
12       q1       13.0    4159
13       q1       14.0    1058
14       q1       15.0     583
15       q2        1.0      25
16       q2        2.0       4
17       q2        3.0     153
18       q2        4.0    1487
19       q2        5.0    1915
20       q2        6.0     486
21       q2        7.0    3110
22       q2        8.0     872
23       q2        9.0     396
24       q2       10.0    1464
25       q2       11.0    1488
26       q2       12.0    4755
27       q2       13.0     317
28       q2       14.0     806
29       q2       15.0     595
30       q3        1.0      14
31       q3        2.0       2
32       q3        3.0     126
33       q3        4.0     798
34       q3        5.0    1644
35       q3        6.0     872
36       q3        7.0     647
37       q3        8.0     239
38       q3        9.0     283
39       q3       10.0    2002
40       q3       11.0    1645
41       q3       12.0    3236
42       q3       13.0    1152
43       q3       14.0     487
44       q3       15.0    1001
45       q4        1.0       4
46       q4        2.0      25
47       q4        3.0     118
48       q4        4.0     983
49       q4        5.0    2320
50       q4        6.0     365
51       q4        7.0     593
52       q4        8.0     275
53       q4        9.0     483
54       q4       10.0    1474
55       q4       11.0    3886
56       q4       12.0    8371
57       q4       13.0     534
58       q4       14.0     392
59       q4       15.0     830

In [142]:
out = pd.merge(out1, out2, on =['quartile', 'ind_merge'], how = 'left')
out

   quartile  ind_merge        INCTOT2  Cal_hourly_wage  counts
0        q1        1.0   34079.333333        12.879762      64
1        q1        2.0   60000.000000        26.000000       6
2        q1        3.0   54308.750000        20.619759      73
3        q1        4.0   44806.024691        20.782586    1671
4        q1        5.0   36094.981884        17.472677    2835
5        q1        6.0   36121.271930        16.580828     855
6        q1        7.0   25432.539906        13.508891    4307
7        q1        8.0   46723.233161        17.452228    1997
8        q1        9.0   24496.000000        21.294025      85
9        q1       10.0   47138.538462        20.710452     546
10       q1       11.0   33488.964126        16.304635    2234
11       q1       12.0   27449.475676        15.133878    1560
12       q1       13.0   19644.162963        11.450259    4159
13       q1       14.0   39239.981132        15.908522    1058
14       q1       15.0   45318.438356        18.978984     583
15       q2        1.0   24004.000000        13.533241      25
16       q2        2.0   56605.000000        14.000000       4
17       q2        3.0   43796.529412        22.923174     153
18       q2        4.0   43816.227941        23.335276    1487
19       q2        5.0   47040.370558        21.666836    1915
20       q2        6.0   43239.480769        19.276851     486
21       q2        7.0   37826.937107        17.326137    3110
22       q2        8.0   47872.928571        20.777460     872
23       q2        9.0   48469.823529        22.325771     396
24       q2       10.0   50662.541401        18.926015    1464
25       q2       11.0   48091.666667        22.514483    1488
26       q2       12.0   32172.144898        16.592317    4755
27       q2       13.0   30605.000000        16.583605     317
28       q2       14.0   33264.118280        18.388714     806
29       q2       15.0   42752.848485        21.306680     595
30       q3        1.0   15443.000000         7.869167      14
31       q3        2.0            NaN              NaN       2
32       q3        3.0   79694.833333        35.712692     126
33       q3        4.0   41242.514706        23.263082     798
34       q3        5.0   69888.461078        27.927022    1644
35       q3        6.0   77821.673684        27.865137     872
36       q3        7.0   45627.329114        19.546888     647
37       q3        8.0   58301.566667        28.115506     239
38       q3        9.0   59053.030303        24.537364     283
39       q3       10.0   73643.526786        28.046504    2002
40       q3       11.0   66124.251429        28.987966    1645
41       q3       12.0   45647.601190        22.975503    3236
42       q3       13.0   39971.008696        19.829995    1152
43       q3       14.0   64657.800000        23.056334     487
44       q3       15.0   70218.619469        25.944830    1001
45       q4        1.0            NaN        20.000000       4
46       q4        2.0  398779.750000        38.999920      25
47       q4        3.0  141845.111111        37.301561     118
48       q4        4.0   92904.117021        32.930069     983
49       q4        5.0  117257.489270        39.543773    2320
50       q4        6.0  134060.173913        37.078617     365
51       q4        7.0   67196.600000        27.454776     593
52       q4        8.0   69615.423077        29.405622     275
53       q4        9.0   97945.854545        32.677710     483
54       q4       10.0  115180.580000        39.157089    1474
55       q4       11.0  111986.012658        36.369547    3886
56       q4       12.0   73128.654693        30.090511    8371
57       q4       13.0   49880.945455        21.457082     534
58       q4       14.0   63861.208333        27.931977     392
59       q4       15.0   78713.698795        33.811740     830

In [143]:
out.loc[out['ind_merge']==1, 'ind_merge'] = 'Agriculture, Forestry, Fishing and Hunting'
out.loc[out['ind_merge']==2, 'ind_merge'] = 'Mining'
out.loc[out['ind_merge']==3, 'ind_merge'] = 'Utilities'
out.loc[out['ind_merge']==4, 'ind_merge'] = 'Construction'
out.loc[out['ind_merge']==5, 'ind_merge'] = 'Manufacturing'
out.loc[out['ind_merge']==6, 'ind_merge'] = 'Wholesale Trade'
out.loc[out['ind_merge']==7, 'ind_merge'] = 'Retail Trade'
out.loc[out['ind_merge']==8, 'ind_merge'] = 'Transportation and Warehousing'
out.loc[out['ind_merge']==9, 'ind_merge'] = 'Information and Communications'
out.loc[out['ind_merge']==10, 'ind_merge'] = 'Finance, Insurance, Real Estate, and Rental and Leasing'
out.loc[out['ind_merge']==11, 'ind_merge'] = 'Professional, Scientific, Management, Administrative, and Waste Management Services'
out.loc[out['ind_merge']==12, 'ind_merge'] = 'Educational, Health and Social Services'
out.loc[out['ind_merge']==13, 'ind_merge'] = 'Arts, Entertainment, Recreation, Accommodations, and Food Services'
out.loc[out['ind_merge']==14, 'ind_merge'] = 'Other Services (Except Public Administration)'
out.loc[out['ind_merge']==15, 'ind_merge'] = 'Public Administration'

In [144]:
out

,quartile,ind_merge,INCTOT2,Cal_hourly_wage,counts
0,q1,"Agriculture, Forestry, Fishing and Hunting",34079.333333,12.879762,64
1,q1,Mining,60000.000000,26.000000,6
2,q1,Utilities,54308.750000,20.619759,73
3,q1,Construction,44806.024691,20.782586,1671
4,q1,Manufacturing,36094.981884,17.472677,2835
5,q1,Wholesale Trade,36121.271930,16.580828,855
6,q1,Retail Trade,25432.539906,13.508891,4307
7,q1,Transportation and Warehousing,46723.233161,17.452228,1997
8,q1,Information and Communications,24496.000000,21.294025,85
9,q1,"Finance, Insurance, Real Estate, and Rental an...",47138.538462,20.710452,546
10,q1,"Professional, Scientific, Management, Administ...",33488.964126,16.304635,2234
11,q1,"Educational, Health and Social Services",27449.475676,15.133878,1560
12,q1,"Arts, Entertainment, Recreation, Accommodation...",19644.162963,11.450259,4159
13,q1,Other Services (Except Public Administration),39239.981132,15.908522,1058
14,q1,Public Administration,45318.438356,18.978984,583
15,q2,"Agriculture, Forestry, Fishing and Hunting",24004.000000,13.533241,25
16,q2,Mining,56605.000000,14.000000,4
17,q2,Utilities,43796.529412,22.923174,153
18,q2,Construction,43816.227941,23.335276,1487
19,q2,Manufacturing,47040.370558,21.666836,1915
20,q2,Wholesale Trade,43239.480769,19.276851,486
21,q2,Retail Trade,37826.937107,17.326137,3110
22,q2,Transportation and Warehousing,47872.928571,20.777460,872
23,q2,Information and Communications,48469.823529,22.325771,396
24,q2,"Finance, Insurance, Real Estate, and Rental an...",50662.541401,18.926015,1464
25,q2,"Professional, Scientific, Management, Administ...",48091.666667,22.514483,1488
26,q2,"Educational, Health and Social Services",32172.144898,16.592317,4755
27,q2,"Arts, Entertainment, Recreation, Accommodation...",30605.000000,16.583605,317
28,q2,Other Services (Except Public Administration),33264.118280,18.388714,806
29,q2,Public Administration,42752.848485,21.306680,595
30,q3,"Agriculture, Forestry, Fishing and Hunting",15443.000000,7.869167,14
31,q3,Mining,NaN,NaN,2
32,q3,Utilities,79694.833333,35.712692,126
33,q3,Construction,41242.514706,23.263082,798
34,q3,Manufacturing,69888.461078,27.927022,1644
35,q3,Wholesale Trade,77821.673684,27.865137,872
36,q3,Retail Trade,45627.329114,19.546888,647
37,q3,Transportation and Warehousing,58301.566667,28.115506,239
38,q3,Information and Communications,59053.030303,24.537364,283
39,q3,"Finance, Insurance, Real Estate, and Rental an...",73643.526786,28.046504,2002
40,q3,"Professional, Scientific, Management, Administ...",66124.251429,28.987966,1645
41,q3,"Educational, Health and Social Services",45647.601190,22.975503,3236
42,q3,"Arts, Entertainment, Recreation, Accommodation...",39971.008696,19.829995,1152
43,q3,Other Services (Except Public Administration),64657.800000,23.056334,487
44,q3,Public Administration,70218.619469,25.944830,1001
45,q4,"Agriculture, Forestry, Fishing and Hunting",NaN,20.000000,4
46,q4,Mining,398779.750000,38.999920,25
47,q4,Utilities,141845.111111,37.301561,118
48,q4,Construction,92904.117021,32.930069,983
49,q4,Manufacturing,117257.489270,39.543773,2320
50,q4,Wholesale Trade,134060.173913,37.078617,365
51,q4,Retail Trade,67196.600000,27.454776,593
52,q4,Transportation and Warehousing,69615.423077,29.405622,275
53,q4,Information and Communications,97945.854545,32.677710,483
54,q4,"Finance, Insurance, Real Estate, and Rental an...",115180.580000,39.157089,1474
55,q4,"Professional, Scientific, Management, Administ...",111986.012658,36.369547,3886
56,q4,"Educational, Health and Social Services",73128.654693,30.090511,8371
57,q4,"Arts, Entertainment, Recreation, Accommodation...",49880.945455,21.457082,534
58,q4,Other Services (Except Public Administration),63861.208333,27.931977,392
59,q4,Public Administration,78713.698795,33.811740,830

In [145]:
len(df.INCTOT2.dropna())

7711

In [146]:
len(df.loc[df['quartile']== 'q1'].INCTOT2.dropna())

2252

In [147]:
len(df.loc[df['quartile']== 'q2'].INCTOT2.dropna())

1829

In [148]:
len(df.loc[df['quartile']== 'q3'].INCTOT2.dropna())

1514

In [149]:
len(df.loc[df['quartile']== 'q4'].INCTOT2.dropna())

2116

In [150]:
len(df.Cal_hourly_wage.dropna())

14851

In [151]:
len(df.loc[df['quartile']== 'q1'].Cal_hourly_wage.dropna())

4008

In [152]:
len(df.loc[df['quartile']== 'q2'].Cal_hourly_wage.dropna())

3708

In [153]:
len(df.loc[df['quartile']== 'q3'].Cal_hourly_wage.dropna())

2884

In [154]:
len(df.loc[df['quartile']== 'q4'].Cal_hourly_wage.dropna())

4251

In [155]:
out.to_excel('C:/Users/yfeng/Desktop/cps/Sep_17_new_Q1_low_wage_report/q1_q4_ten_counties_by_indus_wage2.xlsx')

In [156]:
len(df.loc[df['quartile']== 'q1'])

22033

In [157]:
len(df.loc[df['quartile']== 'q2'])

17873

In [158]:
len(df.loc[df['quartile']== 'q3'])

14148

In [159]:
len(df.loc[df['quartile']== 'q4'])

20653